### ISSUE TITLE
"file vyper.py (for module vyper) not found"

### ISSUE THREAD

**Issue by malaravannm** [ethereum/vyper#1001]
In windows 8 when I execute make, noticing "file vyper.py (for module vyper) not found".  Below included few lines of the messages for your reference. I am using Python 3.7. 

(vyper-venv) C:\Users\Malaravan\vyper>C:\cygwin64\bin\make
python setup.py install
C:\Users\Malaravan\AppData\Local\Programs\Python\Python37\Lib\distutils\dist.py:274: UserWarning: Un
known distribution option: 'long_description_markdown_filename'
  warnings.warn(msg)
C:\Users\Malaravan\~\vyper-venv\lib\site-packages\setuptools\dist.py:398: UserWarning: Normalizing '
0.1.0-beta.2' to '0.1.0b2'
  normalized_version,
running install
running bdist_egg
running egg_info
writing eth_vyper.egg-info\PKG-INFO
writing dependency_links to eth_vyper.egg-info\dependency_links.txt
writing requirements to eth_vyper.egg-info\requires.txt
writing top-level names to eth_vyper.egg-info\top_level.txt
**file vyper.py (for module vyper) not found**
reading manifest file 'eth_vyper.egg-info\SOURCES.txt'
writing manifest file 'eth_vyper.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
**file vyper.py (for module vyper) not found
file vyper.py (for module vyper) not found**

**Comment by fubuloubu** [comment]
Did you activate your virtual environment?

I haven't used it on windows, so I can't tell from that.

**Comment by jacqueswww** [comment]
Closing as no further information was supplied, assuming missing virtualevn.
