### ISSUE TITLE
VIP 1003: Modify public variable syntax

### ISSUE THREAD

**Issue by MohamedLEGH** [ethereum/vyper#1003]
VIP: 1003 
Title: Modify public variable syntax
Author: @MohamedLEGH
Type: Standard
Status: Draft
Created: 2018-08-20

## Simple Summary

Change public getter syntax from:
```
myVar: public(type)
myVar2: public(type)

myVar3: type
```

to
```
public:
  myVar: type
  myVar2: type

private:
  myVar3: type
```

To have a more simple style

## Abstract
I don't like the current public variable syntax.

## Motivation
Almost same idea as https://github.com/ethereum/vyper/issues/931

I think it's better to group public variables together and private variables together. Forcing to explicit which variable is private or public can help visibility and help to avoid errors.

## Specification
New syntax (C++ OO style)

## Backwards Compatibility
Not backwards compatible, user breaking change.

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/)

**Comment by fubuloubu** [comment]
Not valid Python syntax. Would require modifications to the parser, which is the reason #931 was closed.

**Comment by jacqueswww** [comment]
Yes, as this isn't valid python syntax and would break the `ast.parse` call we can consider non python like syntax suggestions. I do think using `public()` isn't the worst way to arrange ones variables (it's explicit which is a good thing).

**Comment by MohamedLEGH** [comment]
@jacqueswww I agree with you that using ```public()``` is not the worst way but I think we can find a better solution.

If we don't want to break the python syntax do we have other options ?

For example

Solution 1:

To only have private function and force users to write getter
```
myVar: type

def get_myVar():
  return myVar
```

Solution 2:

To create 2 function and init/declare variables inside 
```
def __public__():
  myVar: type
  myVar2: type

def __private__():
  myVar3: type

```

**Comment by fubuloubu** [comment]
Solution 1 is what the public modifier seeks to remove, we have already discussed the utility of this.

**Comment by ben-kaufman** [comment]
Personally I really don't mind the current syntax, though I understand your point. 
I don't have any idea for some other "Pythonic" way do to that but if we find something like that it might be good to consider

**Comment by MohamedLEGH** [comment]
Solution 3:
use of "class" keyword :

```
class public:
  myVar: type
  myVar2: type
class private:
  myVar3: type
```

**Comment by jacqueswww** [comment]
We discussed this issue and we don't see in merit in changing the public notation, we are already using.
There is no clear benefit in terms of security to group private / public variables, and this can easily be done by the programmer using comments.
