### ISSUE TITLE
Types not enforced on tuple return - bug

### ISSUE THREAD

**Issue by haydenadams** [ethereum/vyper#1006]
Attempting to compile:
```python
@public
def getTime() -> uint256:
    return block.timestamp
```
rightfully returns the error 
```
vyper.exceptions.TypeMismatchException: line 3: 
Return type units mismatch uint256(sec, positional) uint256
```

However, this compiles just fine:
```python
@public
def getTimeAndBalance() -> (bool, address):
    return block.timestamp, self.balance
```

**Comment by jacqueswww** [comment]
What's more effed up is that I actually read the check for this commented out in the code... meaning I must've done it midway through some other PR. And there is no test for it.
