### ISSUE TITLE
Unhandled Exception with Unbalanced Parens

### ISSUE THREAD

**Issue by fubuloubu** [ethereum/vyper#1023]
### Version Information
* vyper Version: 0.2.0-beta.2

### What's your issue about?
Missing a parenthesis results in a somewhat intuitive error (for those who don't now how compilers work):
```python
@public
def foo():
    convert(

# Returns "tokenize.TokenError: ('EOF in multi-line statement', (4, 0))" when compiled
```

### How can it be fixed?
We should catch this error and parse the location so that we can more accurately report it to users.

#### Cute Animal Picture
![pug eating pizza](http://cdn6.whiskeyriff.com/wp-content/uploads/dog-eating-pizza.jpg)

**Comment by jacqueswww** [comment]
On this.
