### ISSUE TITLE
VIP: Bitwise Operators

### ISSUE THREAD

**Issue by fubuloubu** [ethereum/vyper#1027]
## Simple Summary
Add support for bitwise operators to Vyper because they are very useful.

## Abstract
Vyper doesn't have bitwise operators, but EVM does:

| Opcode | Operation | Description |
| --- | --- | --- |
| 0x16 | AND | Bitwise AND operation |
| 0x17 | OR | Bitwise OR operation |
| 0x18 | XOR | Bitwise XOR operation |
| 0x19 | NOT | Bitwise NOT operation |

Additionally, bitshift operators are also useful, but not included in the EVM.
(Bitwise operations can be accomplished by dividing and multiplying by powers of 2)

## Motivation
Bitwise operators can enable very commonly used but sometimes "magical" operations to be composed. For example, I am working on a sparse merkle tree implementation, and I need a way to choose the paths in the binary tree via the bits set for a specific key id I am managing using the tree. There alternative ways that this can be supported, such as adding a `bitextract(a, x)` function that returns whether or not bit `x` is set in a `bytes32` variable `a`, but bitwise operators are a more general way these ideas can be supported. We can of course generate more specific widgets that allow for useful functionality

## Specification
Two options for implementations of these operators. We'll call them "Function-style" and "C-style".

| Operator | Function-style | C stye |
| --- | --- | --- |
| AND | `bitand(x, y)` | `x & y` |
| OR | `bitor(x, y)` | `x \| y` |
| XOR | `bitxor(x, y)` | `x ^ y` |
| NOT | `bitnot(x)` | `~x` or `!x` |

"Function-style" would be most Pythonic because it is clearer (and the verbosity would prevent being too creative with bitbashing on one line), but several of the C-style operators are actually supported directly by Python AST.

EDIT: "Function-style" is the choice we will take. Arguments must be `bytes32`

As an example, here is what I am trying to do with my merkle tree:
```python
for bit in range(N):  # N is key-size
    branch_right: bool = bitand(_key, 2**bit)  # I don't think `2**n` is valid Vyper
    # or `branch_right: bool = bitextract(_key, bit)`
    if branch_right:
        # iterate on one branch
    else:
        # iterate on the other branch
```

## Backwards Compatibility
No backwards compatibility issues

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/)

**Comment by jacqueswww** [comment]
Preliminary thought: I think I like functional style more.

**Comment by jacqueswww** [comment]
Approved, we should specify types (input <-> output). Assuming only `bytes32`.

**Comment by rohithpr** [comment]
https://github.com/ethereum/vyper/blob/master/vyper/functions/functions.py#L573-L585

`bitwise_(and|or|xor)` are already supported for uint256.

**Comment by fubuloubu** [comment]
Welp, we are dummies for missing this! Thanks for reminding us.

`bitextract(a, n)` (return `n`-th bit of `a`) is the only new proposal.

I will open a new VIP for just this widget
