### ISSUE TITLE
Bug: Unit types not always enforced in private calls from default function

### ISSUE THREAD

**Issue by haydenadams** [ethereum/vyper#1031]
### Version Information

* vyper Version: https://github.com/jacqueswww/vyper/tree/901_less_gas_for_private_functions

Idk if this issue is specific to #901, seems likely it was around before.

### Issue
Unit types not always enforced in `@private` calls from `__default__()`

Here is the relevant section of Uniswap code that lead me to the bug: 
```python
@private
def ethToToken(eth_sold: uint256(wei), min_tokens: uint256(wei), deadline: timestamp, buyer: address, recipient: address) -> uint256(wei):
    token_reserve: uint256 = self.token.balanceOf(self)
    tokens_bought: uint256(wei) = self.getInputPrice(eth_sold, self.balance, as_wei_value(token_reserve, 'wei'))
    # [unrelated code removed for brevity]
    return tokens_bought

@public
@payable
def __default__():
    # BUG: second parameter does not use as_wei_value() but function compiles and passes tests
    self.ethToToken(msg.value, 1, block.timestamp, msg.sender, msg.sender)

@public
@payable
def ethToTokenSwap(min_tokens: uint256(wei), deadline: timestamp) -> uint256(wei):
    return self.ethToToken(msg.value, min_tokens, deadline, msg.sender, msg.sender)
```

As you can see, the second parameter of ethToToken() has unit type `wei`. However passing in a unitless `uint256`, without using `as_wei_value()` works when called from the `__default()__` function.

#### Cute Animal Picture

![image](https://user-images.githubusercontent.com/9343483/45977690-573a8080-c018-11e8-8c28-47702ecab634.png)

**Comment by fubuloubu** [comment]
This may be a more subtle inconsistency: we automatically convert units for literals in-line without raising an error.

In most cases this is okay, as `my_var: uint256("my_unit"); self.my_var = 1  # my_units` is more readable than `my_var: uint256("my_unit"); self.my_var = convert(1, "my_unit")`. But in your case, it's a bit of a quandary because it sort of hides the fact that your `min_tokens(wei)` is 1 (should `wei` be a custom unit? e.g. `token`) which is a bit harder to appreciate when reading the code.

We may need to more fully think through the whole units thing :/

**Comment by fubuloubu** [comment]
Should you have to specify/convert units for literals? Can we enable a more readable syntax for literals that should have units? Maybe `1@"unit"` or `1-"unit"`?

**Comment by haydenadams** [comment]
hmm I'm on the fence here. I def prefer how it looks with the automatic conversion although it seems to clash with needing to convert everything else

**Comment by jacqueswww** [comment]
So I think I know why it does this, basically I don't think that our function signature storing in global context carries the concept of units alongside it, it only stores the raw ABI level types.

I do think we rather have to enforce units here, as it would be stricter and more consistent.
