### ISSUE TITLE
Meeting Monday 1 October 2018

### ISSUE THREAD

**Issue by jacqueswww** [ethereum/vyper#1038]
## General Bi-Weekly meeting.
Start: Monday 1 October 2018, 14:00 UTC (https://time.is/UTC)
Hangouts: https://meet.google.com/czc-kuep-jda

### Agenda
- #901 has been merged!
- Change tagline (Suggestion: "Pythonic Smart Contract Language for the EVM") [Approved]
- Repository access (cc @pipermerriam)
- Remix integration
- VIPs / Issues to discuss
  - https://github.com/ethereum/vyper/issues/1027
  - https://github.com/ethereum/vyper/issues/1026

### Notes

**Comment by fubuloubu** [comment]
Moar topics:
* Change tagline (Suggestion: "Pythonic Smart Contract Language for the EVM")
* Repository access (cc @pipermerriam)
* Remix integration

**Comment by jacqueswww** [comment]
@pipermerriam my merge permissions was recently revoked, if you could maybe change it back?

**Comment by jacqueswww** [comment]
#1026 - Approved
#1027 - Approved
