### ISSUE TITLE
Unit Mismatch error for wei_value operation

### ISSUE THREAD

**Issue by eltNEG** [ethereum/vyper#1065]
### Version Information

* vyper Version: https://vyper.online [Wednesday, November 7, 2018]
and
* vyper Version: 0.1.0b4
* pyethereum Version: x.x.x
* OS: linux
* Python Version (python --version): 3.6.6

### What's your issue about?
Unexpected error while compiling my contract. Check the second to the last line in the snippet below
ERROR: `vyper.exceptions.TypeMismatchException: line 177:8 Unit mismatch: {'wei': 1} {}`
Why do I need to convert amount to wei_value again when it has already been declared in the function argument?
Code:
```
@public
@constant
def func(amounts: wei_value[100]) -> bool:
    total: wei_value = as_wei_value(0, "wei")

    # calculate total
    for amount in amounts:
        total += amount # Error: mismatch units

    return True
```
### How can it be fixed?
Convert amount to wei_value
```
@public
@constant
def func(amounts: wei_value[100]) -> bool:
    total: wei_value = as_wei_value(0, "wei")
    
    for amount in amounts:
        total = as_wei_value(amount, "wei") # No error
    return True
```
#### Cute Animal Picture

> cute animal picture

**Comment by fubuloubu** [comment]
Ah, great catch. #1039 should probably account for this. What do you think @jacquesww?
