### ISSUE TITLE
"send" as a reserved keyword collides with the ERC777 specification

### ISSUE THREAD

**Issue by lsaether** [ethereum/vyper#1068]
### Version Information

* vyper Version: 0.1.0b4
* pyethereum Version: none
* OS: 4.18.16-arch1-1-ARCH
* Python Version (python --version): 3.7.1

### What's your issue about?

While implementing the https://github.com/ethereum/EIPs/issues/777 specification as a Vyper contract I was unable to due to the collision of the specification's `send` method with the reserved keyword `send` in Vyper used for sending ether. Trying to declare a `send` method on a contract throws the following exception: 
```
vyper.exceptions.FunctionDeclarationException: Function name invalid: send
```

### How can it be fixed?

I see three options:
- Vyper changes the `send` keyword to something else.
- ERC777 changes the `send` method to something else.
- As @mcdee suggested in the ERC777 issue, Vyper could allow for a contract method `send` that is different from the built-in function `send`. These two would be disambiguated by the way in which they are invoked. The built-in function could retain the naked invocation `send <address, amount>`  while a method declared on the contract would be invoked with `self.send()`. From the external point of view only the contract method would be accessible.
 
#### Cute Animal Picture

![image](https://user-images.githubusercontent.com/25539605/48189251-0bca0080-e340-11e8-93e3-e26e2f80a20f.png)

**Comment by ben-kaufman** [comment]
Thanks for raising that up. Personally, I think ERC-777 should change that in order to keep things more clear, as `send` is used both in Vyper and Solidity and I think it would be best to reserve that.
I'm not sure about that but I haven't seen much usage of this currently in production so I think changing the proposed ERC should be a problem.

Any thought from others here?

**Comment by mcdee** [comment]
@ben-kaufman a quick scan of 4byte shows the following submitted signatures with the name send:

```
send()
send(address)
send(address[])
send(address,address,address[],uint256[])
send(address,address[],address,uint256[])
send(address,address,uint256)
send(address,address[],uint256[])
send(address,bytes)
send(address,string)
send(address,uint256)
send(address[],uint256[])
send(address,uint256,bytes)
send(address[],uint256[],uint256)
send(address,uint256,uint256,uint256)
```

There might be other databases out there that could provide details of the prevalence of these methods, but it's far from just a problem with ERC-777 and blocking keywords from being method names is going to be a general compatibility issue.

**Comment by jacqueswww** [comment]
I think whitelisting `send` as a function name is our best option here. There are no other keywords we can use for the `send` functionality, and programmers will naturally want to create methods named `send`.
