### ISSUE TITLE
Literals of more than three-dimensional list can't be compiled?

### ISSUE THREAD

**Issue by nrryuya** [ethereum/vyper#1070]
(Vyper Version: 0.1.0b4)

This is compiled.
```
l: uint256[2][2] = [[0, 0], [0, 0]]
```
However, when compiling these, `AttributeError: 'ListType' object has no attribute 'typ'` occurs.
```
    l: uint256[2][2][2] = [[[0, 0], [0, 0]],[[0, 0], [0, 0]]]
```
```
    l: uint256[2][2][2][2] = [[[[0, 0], [0, 0]],[[0, 0], [0, 0]]], [[[0, 0], [0, 0]],[[0, 0], [0, 0]]]]
```

More than three-dimensional list can't be compiled in Vyper or the syntax above is wrong?
(In addition to that, should the compiler handle this exception? This should be another issue, though.)

**Comment by jacqueswww** [comment]
Fixed in #1152.
