### ISSUE TITLE
Converting sliced bytes to non-bytes32 doesn't work

### ISSUE THREAD

**Issue by fubuloubu** [ethereum/vyper#1072]
### Version Information
* vyper Version: 0.1.0b4

### What's your issue about?
Vyper doesn't like converting a slice of `bytes` (slice len <=32) to a type other than `bytes32`:

```python
# Compiles!
@public
@constant
def foo(_arg: bytes[100]) -> bytes32:
    return convert(slice(_arg, start=20, len=32), bytes32)

# Does not compile....
@public
@constant
def bar(_arg: bytes[100]) -> uint256:
    return convert(slice(_arg, start=20, len=32), uint256)

# Compiles! (Workaround)
@public
@constant
def baz(_arg: bytes[100]) -> uint256:
    return convert(convert(slice(_arg, start=20, len=32), bytes32), uint256)

# Note: above does not work for addresses!
```

### How can it be fixed?
Make it so!

#### Cute Animal Picture

![fluffy pony](https://i.ytimg.com/vi/sNv1s5lAZts/maxresdefault.jpg)

**Comment by jakerockland** [comment]
@fubuloubu I'm starting to look into this one. One note for now, this guy also compiles:

```
# Compiles!
@public
@constant
def who(_arg: bytes[100]) -> int128:
    return convert(slice(_arg, start=20, len=32), int128)
```

Seems like we may want to re-name this issue to be more specific to converting from `bytes` to `int128`, though perhaps we do want to also add converting from `bytes` to `address`? Though perhaps not converting from `bytes` to `decimal` as converting from `bytes32` to `decimal` is also not currently supported. Thoughts?

**Comment by jakerockland** [comment]
Yeah it definitely is a bit of a rabbit hole that has been unearthed haha 😂. Happy to work on that table though yeah, that sounds like a good plan of action to me 👍
