### ISSUE TITLE
BoolOps cannot accept >2 arguments

### ISSUE THREAD

**Issue by fubuloubu** [ethereum/vyper#1075]
### Version Information

* vyper Version: 0.2.0b4

### What's your issue about?
```python
# Fails: Expected two arguments for a bool op
def foo():
    a: bool = True and True and False

# Fails: Expected two arguments for a bool op
def foo():
    a: bool = True or True or False

# This passes for some reason lol
def foo():
    a: bool = True or True and False

# This also passes lol
def foo():
    a: bool = True and (True and False)
```

### How can it be fixed?
Handle chained BoolOps similar to how regular Ops work (addition etc)

#### Cute Animal Picture
![insane rhino](https://images.theconversation.com/files/227656/original/file-20180714-27015-1j06axb.jpg)

**Comment by jacqueswww** [comment]
@fubuloubu does this perhaps have to do with tri-ops notation like `1 < a < 10` which we don't support currently?

**Comment by fubuloubu** [comment]
No, just straight booleans.
```python
def(a: bool, b: bool, c: bool) -> bool:
    return a and b and c
```

**Comment by jakerockland** [comment]
@fubuloubu @jacqueswww I'm taking a crack at this one.
