### ISSUE TITLE
Meeting Wednesday Nov 14th

### ISSUE THREAD

**Issue by fubuloubu** [ethereum/vyper#1076]
Start: Wednesday 14 November 2018, 14:00 UTC (https://time.is/UTC)
Hangouts: https://meet.google.com/czc-kuep-jda

Agenda
* #1064 & #1074
* #1065
* #1068
* #300 (updated)

**Comment by jakerockland** [comment]
Can anyone join in on this call @fubuloubu?

**Comment by fubuloubu** [comment]
@jakerockland yup! It's open!

You definitely have some things to discuss :)

**Comment by jakerockland** [comment]
@fubuloubu Don't think I'm going to be able to call in this morning for this one so will have to stick to async for now on the discussion but will try to coordinate that that I can be on the next one. 😅 😓

**Comment by fubuloubu** [comment]
Yup

**Comment by jacqueswww** [comment]
Yes, I think we are leaving that one as is. Been on the table for a _very_ long time.
