### ISSUE TITLE
help with raw_call

### ISSUE THREAD

**Issue by asiva** [ethereum/vyper#1104]
Not sure if this is the right to ask for help.

I'd like to call a constant function on one contract (X) from another contract (Y). I have the ABI and address for X. X and Y are both on Ropsten. I can interact with X fine using, for example, MEW.

Here is the code for X:

```
@public
@constant
def read() -> bytes32:
    return 0x0000000000000000000000000000000000000000000000059f43ef8557c30000
```

And the ABI:
```
[{"name": "read", "outputs": [{"type": "bytes32", "name": "out"}], "inputs": [], "constant": true, "payable": false, "type": "function", "gas": 283}]
```
Contract Y looks like this:
```
feedaddress: public(address)
feed: public(bytes[32])

@public
def __init__():
    self.feedaddress = 0xAb3F6737b0cf41e8a6AE297A3833021f8af2a3aC

@public
def myread():
    self.feed = raw_call(self.feedaddress, 'read', outsize=32, gas=msg.gas)

@public
def setfeedaddress(_new: address):
    self.feedaddress = _new
```
It returns "Warning! Error encountered during contract execution [Reverted]" on etherscan. I've used ```raw_call(self.feedaddress, 'x57xdex26xa4', outsize=32, gas=msg.gas)``` as well as '0x57de26a4' and '57de26a4' which is the first four bytes of keccak256 as per the [documentation](https://vyper.readthedocs.io/en/latest/built-in-functions.html#raw-call) with plenty of gas and all return the same error as above. 

What am I doing wrong?

**Comment by fubuloubu** [comment]
Should it be `read()` for the signature?

**Comment by asiva** [comment]
I've tried that too. Actually the keccak examples are for "read()". Perhaps I should try keccak for "read"?

**Comment by jacqueswww** [comment]
@asiva You probably want to use method_id() for the function signature. I am just curious, but do you need raw_call specifically in this case, wouldn't a contract interface suffice?

**Comment by asiva** [comment]
Thanks @jacqueswww . The code above is for testing purposes. I'd like in the end to make use of a solidity based contract that's already live. My current understanding is that contract interfaces are for use with vyper contracts that are compiled together. Is that right?

Any illustration on how to use a method_id() would be great.

I see this code [from a test](https://github.com/ethereum/vyper/blob/d2e077a19bb1d6e855c1e3c62a2cfca7fea9f2e6/tests/parser/functions/test_method_id.py):

`ans: bytes[32] = raw_call(self, concat(method_id("double(int128)", bytes[4]), convert(5, bytes32)), gas=50000, outsize=32)
`

But I am not sure how it works.

**Comment by jacqueswww** [comment]
Contract interfaces are ABI compatible so you can use them ;)
```
contract Test:
    def read(a: bytes32): constant

**Comment by asiva** [comment]
The contract interface approach works great. I haven't tried the raw_call approach. I'll use Gitter for any further questions.

In case it's useful for anyone else later, following the original toy example above this works:

```
contract Beread:
    def read() -> bytes32: constant

feedaddress: public(address)
feed: public(bytes32)
beread: Beread


@public
def __init__():
    self.feedaddress = 0x161E2Eea68ac57F3C7220170435396Fd7089d9fE

@public
def myread():
    self.beread = self.feedaddress
    self.feed = self.beread.read()

@public
def setfeedaddress(_new: address):
    self.feedaddress = _new
    

```
