### ISSUE TITLE
Inconsistent type-checking depending on Assign vs AnnAssign

### ISSUE THREAD

**Issue by charles-cooper** [ethereum/vyper#1107]
### Version Information

* vyper Version: master / ~d934b291f53756b47cf0775c73742b48e3fafb58~ 921bb80cf59c9be0067ed20e1a7b6ad0b59598b3
* OS: linux
* Python Version (python --version):
```
$ python --version
Python 3.6.7
```
* Environment (output of `pip freeze`):
```
$ pip freeze
flake8==3.6.0
mccabe==0.6.1
pycodestyle==2.4.0
pycryptodome==3.7.2
pyflakes==2.0.0
vyper==0.1.0b4
```

### What's your issue about?
```python
# Fails with vyper.exceptions.TypeMismatchException: Invalid type, expected: decimal
#@private
#def _assign1():
#    y: int128 = 1
#    z: decimal = y

# Passes:
@private
def _assign2():
    y: int128 = 1
    z: decimal
    z = y

# By analogy with _assign1 this should fail but it does not.
@private
def _assign3():
    y: {a: {c: int128}, b: int128}
    z: {a: {c: decimal}, b: int128} = y
```

Ran into this while working on type-checking in #1102. This is actually in the test suite - https://github.com/ethereum/vyper/blob/921bb80cf59c9be0067ed20e1a7b6ad0b59598b3/tests/parser/syntax/test_maps.py#L135-L141.

### How can it be fixed?
I don't know whether `_assign1` is correct is or `_assign2` (I think the rejection in `_assign1` is correct), but basically one needs to reify the type-checking logic between `_check_valid_assign` (used by `ann_assign`) and `make_setter` (used by `assign`).

**Comment by fubuloubu** [comment]
Man, all three of those should fail. They all look pretty dubious!

**Comment by jakerockland** [comment]
Pushing a fix shortly (or at least partial fix as for me `_assign3` already fails) that enforces throwing an error for implicit type conversions.
