### ISSUE TITLE
Python command script on Windows

### ISSUE THREAD

**Issue by sgryphon** [ethereum/vyper#1128]
### Version Information

* vyper Version: v0.1.0-beta.5
* OS: win
* Python Version (python --version): 3.7
* Environment (output of `pip freeze`):
pycryptodome==3.7.2
vyper==0.1.0b5

### What's your issue about?

After installation, the command `vyper` does not work on Windows.

The installation does put a shell script in the Python folder %AppData%\Local\Programs\Python\Python37\Scripts

However, although this is on the path, it does not run on Windows.

Other programs often put an exe or similar file there instead.

### How can it be fixed?

I put a simple vyper.cmd file in the same folder, with the contents:

@python C:\Dev\vyper\build\scripts-3.7\vyper %*

This is a hack, because it hard codes to my development path, but something similar would work if configured with the correct location installed.

#### Cute Animal Picture

> put a cute animal picture here.

**Comment by JamesHutchison** [comment]
`@python %~dp0\vyper %*`

**Comment by jacqueswww** [comment]
I think the solution here is to use `console_scripts` with entrypoints, this way it will work on all platforms :)

**Comment by jacqueswww** [comment]
Starting on this.

**Comment by Kevin-Chen0** [comment]
Works, thank you!!
