### ISSUE TITLE
Monday 17th December 2018

### ISSUE THREAD

**Issue by jacqueswww** [ethereum/vyper#1140]
Start: Monday 17th December 2018, 13:00 UTC (https://time.is/UTC)
Hangouts: https://meet.google.com/czc-kuep-jda

Agenda:
- Slithr
- https://github.com/ethereum/vyper/issues/358
- Updates on `convert`.
- Nest tuples / structs.
- Look into introducing: https://github.com/ethereum/vyper/issues/711, for SMT checking.

**Comment by jakerockland** [comment]
Something to add to the agenda: follow-up discussion re: conversions VIP to make sure everybody is onboard with proposed additions to the VIP for specifying conversions to/from the `address` type.

**Comment by fubuloubu** [comment]
Inviting @montyly to chat about our language's AST/IR and also about the upcoming integration of Vyper with the [Slither](https://github.com/trailofbits/slither) static analysis tool.

**Comment by charles-cooper** [comment]
Another agenda topic I'd like to add - struct calling convention / ABI issues / scope of #1019
