### ISSUE TITLE
Unable to set constant variables at the start of a file.

### ISSUE THREAD

**Issue by derekzx** [ethereum/vyper#1159]
### Version Information

* vyper Version: 0.1.0
* OS: Ubuntu 18.04
* Python Version (python --version):
* Environment (output of `pip freeze`):

### What's your issue about?
Unable to set a constant uint256 at the start of a file.

*Output:
vyper.exceptions.TypeMismatchException: line 1: Invalid value for constant type, expected uint256
test_a : constant(uint256) = 21888242871839275222246405745257275088696311157297823662689037894645226208583

*Commands
vyper test.vy

*Only had one line of code in file
test_a : constant(uint256) = 21888242871839275222246405745257275088696311157297823662689037894645226208583

*Cute animal
![image](https://user-images.githubusercontent.com/17759758/50415978-0c1f4c00-0859-11e9-963f-b3ab709b31d8.png)

**Comment by jacqueswww** [comment]
Bug confirmed, interesting.. the bug seems to be related to distinguishing between a uint256 and int128 literal.

**Comment by jacqueswww** [comment]
Starting on this.

**Comment by jacqueswww** [comment]
@derekzx I just tried the following on _master_ and the compilation is succesful. I can confirm that 0.1.0b6 doesn't compile, however master seems to. Could you give master a go?

**Comment by derekzx** [comment]
@jacqueswww I might be doing this wrongly and not pulling the master branch but I am still having the error.

```
git branch
* master
```
however
```
vyper --version
0.1.0b6
```

**Comment by derekzx** [comment]
i have already run:
```
git pull
sudo make
```
within my vyper directory already, making sure I am up to date.

**Comment by derekzx** [comment]
More commands:
```
git remote show origin
* remote origin
  Fetch URL: https://github.com/ethereum/vyper.git
  Push  URL: https://github.com/ethereum/vyper.git
  HEAD branch: master
  Remote branches:
    master                                       tracked
    refs/remotes/origin/fubuloubu-issue-template stale (use 'git remote prune' to remove)
    sharding                                     tracked
    stable                                       tracked
  Local branch configured for 'git pull':
    master merges with remote master
  Local ref configured for 'git push':
    master pushes to master (up to date)
```
and
```
git show origin
commit cc6ed8f489b3e908bd16f044dc732b33db34db30 (HEAD -> master, origin/master, origin/HEAD)
Merge: 9ae0164 fa03b16
Author: Bryant Eisenbach <fubuloubu@gmail.com>
Date:   Tue Jan 15 14:32:38 2019 -0500

    Merge pull request #1197 from charles-cooper/fix-vyper-lll

    Fix vyper-lll binary
```

**Comment by fubuloubu** [comment]
Really wish `vyper --version` had the commit hash...
