### ISSUE TITLE
Unexpected ValueError message when compiling code with a final line of comments

### ISSUE THREAD

**Issue by derekzx** [ethereum/vyper#1161]
### Version Information

* vyper Version: 0.1.0
* OS: Ubuntu 18.0.4
* Python Version (python --version):
* Environment (output of `pip freeze`):

### What's your issue about?
Any file with a line of code which ends in comments instead of code (###....) will raise a ValueError

### Information
Input
```
@public
def test():
    c : uint256
    d : uint256
    e : uint256
    d, e = self.minustest(1006, 1)
    #bla
```
Output
```
ValueError: start (60,8) precedes previous end (61,0)
```

![image](https://user-images.githubusercontent.com/17759758/50449050-b1bce300-095f-11e9-919f-f78e81f44025.png)

**Comment by Ryan-Gordon** [comment]
I did some digging on this as I seen no one commented yet but this could be the culprit 

https://github.com/ethereum/vyper/blob/17a4f43992a39fa17e55943603853c5b1d64c60f/vyper/parser/pre_parser.py#L81

My rationale is : 
I have seen pre-parser uses tokenize, and I did some look up on the tokenize package code and I could see a function `untokenize`; which we use in this project here: 
https://github.com/ethereum/vyper/blob/17a4f43992a39fa17e55943603853c5b1d64c60f/vyper/parser/pre_parser.py#L81

this calls a function called `add_whitespace ` which has the exact error we are seeing https://github.com/python/cpython/blob/master/Lib/tokenize.py#L173

**Comment by Ryan-Gordon** [comment]
@derekzx could you give me a full example of this defect ?

To try and reproduce I installed latest vyper
Then I modified the code for `examples/name_registry/name_registry.vy`
to look like this : 

```

registry: map(bytes[100], address)

@public
def register(name: bytes[100], owner: address):
    assert self.registry[name] == ZERO_ADDRESS  # check name has not been set yet.
    self.registry[name] = owner


@public
@constant
def lookup(name: bytes[100]) -> address:
    return self.registry[name]
    #testcomment
```
and it compiled without error 

Just to be sure I tried to put a comment at the end of the file too but not enclosed in a function and that also compiled
But I might be missing a step

**Comment by Ryan-Gordon** [comment]
Also
Just incase I also stuck similar code into the vyper online compiler and it worked okay, no issue

**Comment by Ryan-Gordon** [comment]
@jacqueswww I think this issue could be resolved with latest master, same as #1159
Would you be able to confirm

**Comment by derekzx** [comment]
Try just sticking this code into the compiler:
```
@public
def __init__():
    X: uint256

#test
```
Running:
```
 vyper test.vy
Error compiling:  test.vy
ValueError: start (5,5) precedes previous end (6,0)
```

**Comment by derekzx** [comment]
This is from latest pull of vyper

**Comment by charles-cooper** [comment]
@derekzx I'm not seeing this as an issue anymore?
```bash
$ vyper --version 
0.1.0b7
$ vyper -f ir /dev/stdin <<EOF
@public
def __init__():
    X: uint256

#test
EOF

[seq,
  [mstore, 28, [calldataload, 0]],
  [mstore, 32, 1461501637330902918203684832716283019655932542976],
  [mstore, 64, 170141183460469231731687303715884105727],
  [mstore, 96, -170141183460469231731687303715884105728],
  [mstore, 128, 1701411834604692317316873037158841057270000000000],
  [mstore, 160, -1701411834604692317316873037158841057280000000000],
  # Line 1
  [assert, [iszero, callvalue]]]
```

**Comment by fubuloubu** [comment]
Original issue too?

```python
@public
def test():
    c : uint256
    #bla
```

I deleted some things from the original issue that look like it might have been something to do with tuples?

**Comment by charles-cooper** [comment]
```bash
$ vyper -f ir /dev/stdin <<EOF
> @public
> def test():
>     c : uint256
>     #bla
> EOF
[seq,
  [return,
    0,
    [lll,
      [seq,
        [mstore, 28, [calldataload, 0]],
        [mstore, 32, 1461501637330902918203684832716283019655932542976],
        [mstore, 64, 170141183460469231731687303715884105727],
        [mstore, 96, -170141183460469231731687303715884105728],
        [mstore, 128, 1701411834604692317316873037158841057270000000000],
        [mstore, 160, -1701411834604692317316873037158841057280000000000],
        # Line 1
        [if,
          [eq, [mload, 0], '4171824493' <test()>],
          [seq, [assert, [iszero, callvalue]], stop]],
        /* Default function */ [revert, 0, 0]],
      0]]]
```

**Comment by jacqueswww** [comment]
Closing, if it's still happening we can open a new issue.
