### ISSUE TITLE
`create_with_code_of()` name is somewhat misleading

### ISSUE THREAD

**Issue by GNSPS** [ethereum/vyper#1177]
### What's your issue about?

I was not familiar with the inner workings of the Vyper compiler before diving deep into the Uniswap codebase.
While inspecting their contracts I always assumed that `create_with_code_of()` would `CODECOPY` the whole code of the target contract but, once I dug into Vyper and much to my big surprise, it creates a forwarder (which makes a lot of sense reusability-wise).

### How can it be fixed?

Like I was fooled I believe that others might be and I would propose a more expressive name for this (given its name is already long), something along the lines of: `create_forwarder_to` or `create_delegated_copy_of`

#### Cute Animal Picture

![](http://i.imgur.com/NoIi9ol.jpg)

**Comment by fubuloubu** [comment]
That is a great point! We should discuss at our meeting on Monday

**Comment by jacqueswww** [comment]
Approved not decided on the right name yet, other suggested names:
`create_proxy`
`create_instance_of`

**Comment by jacqueswww** [comment]
@charles-cooper @fubuloubu I am keen on getting this fixed. I think the term _forwarder_ best describes the behaviour, as proxies is quite a broad IT term. Can I go ahead with `create_forwarder_to` ?

**Comment by fubuloubu** [comment]
SGTM

**Comment by jacqueswww** [comment]
Cool, I will pick this one up next - is simple enough hehe ;)
