### ISSUE TITLE
Vyper wiki tools and resources addition

### ISSUE THREAD

**Issue by kimushkaa** [ethereum/vyper#1187]
I suggest adding SmartCheck (https://tool.smartdec.net/) to the tools section on Wiki. SmartCheck is a linter that for Solidity and Vyper that checks code for security issues and bad practices.

@jacqueswww

**Comment by jacqueswww** [comment]
Done, thanks for mention :)

**Comment by fubuloubu** [comment]
p.s. @kimushkaa we noticed that your "private variable check" isn't up to date with our latest release of structs. those don't count as variables!

**Comment by eMarchenko** [comment]
@fubuloubu could you please add detailed issue to the [SmartCheck repo](https://github.com/smartdec/smartcheck)? So we can reproduce it and fix the rule.
