### ISSUE TITLE
Unexpected Crash in types.py (line 401)

### ISSUE THREAD

**Issue by mateuszk87** [ethereum/vyper#1194]
### Version Information

* vyper Version: 0.1.0b6
* OS: osx
* Python Version (python --version): Python 3.6.3

### What's your issue about?

It is possible to cause an unexpected crash. This can lead to security bugs in dependent systems (e.g. in future [VerifiedContracts](https://etherscan.io/verifyContract2). Actually, [this is why fuzzing solc is so interesting for us, too](https://github.com/Ethermat/solc-fuzzing)

### Reproduce Bug

 1. Vyper contract leading to the issue:
[30.txt](https://github.com/ethereum/vyper/files/2760996/30.txt)

 2. Command to run: `vyper 30.txt`

**Comment by jacqueswww** [comment]
Fixed in mega fuzzer-fix branch.

**Comment by mateuszk87** [comment]
cool :)
