### ISSUE TITLE
Logs are Malformed if Functions are Called in It

### ISSUE THREAD

**Issue by nisdas** [ethereum/vyper#1206]
### Version Information

* vyper Version: `0.1.0b7`
* OS: `Ubuntu 18.04`
* Python Version (python --version): `3.6.7`
* Environment (output of `pip freeze`): 
```
pkg-resources==0.0.0
pycryptodome==3.7.2
vyper==0.1.0b7
```

### What's your issue about?

Calling a function when emitting a log leads to a malformed log. However, a normal 
log is emitted when an object is placed in the log instead of a function.

Please include information like:

* full output of the error you received
This test is in `go` however this error is relevant as when unpacking and decoding logs emitted, I do get the below error.

```
--- FAIL: TestProcessChainStartLog (1.63s)
    log.go:31: log: Unable to unpack ChainStart log data unable to unpack logs: abi: cannot marshal in to go slice: offset 3321006415 would go over slice boundary (len=128)
```

* the code that caused the failure (see [this link](https://help.github.com/articles/basic-writing-and-formatting-syntax/) for help with formatting code)

The below code causes an error:

```py 

TestLog: event({testData: bytes[8] })

@private
@constant
def to_bytes(value: uint256) -> bytes[8]:
    return slice(concat("", convert(value, bytes32)), start=24, len=8)

@public
def test_func(value: uint256):

  # log will be malformed
   TestLog(self.to_bytes(value))
   
   loggedValue: bytes[8] = self.to_bytes(value)
   
   # log will be normal
   TestLog(loggedValue)

```

### How can it be fixed?

Fill this in if you know how to fix it.

#### Cute Animal Picture
![image](https://user-images.githubusercontent.com/33201827/51470844-ffd2d400-1daf-11e9-854c-08b60a85d164.png)

**Comment by jacqueswww** [comment]
Seems to be be problem with return value not being handled from private function call.

**Comment by nisdas** [comment]
@jacqueswww 
I know my example above doesnt show it, but I got the same error using a public function call.
```py
 TestLog: event({testData: bytes[8] })

@public
@constant
def to_bytes(value: uint256) -> bytes[8]:
    return slice(concat("", convert(value, bytes32)), start=24, len=8)

@public
def test_func(value: uint256):

  # log will be malformed
   TestLog(self.to_bytes(value))
   
   loggedValue: bytes[8] = self.to_bytes(value)
   
   # log will be normal
   TestLog(loggedValue)
```
The above also will lead to malformed log

**Comment by jacqueswww** [comment]
@nisdas are you sure this is a vyper problem, if I run it using py-evm / vyper-debug all seems in order:

```
vyper-run 1206_logging.vy "test_func(123)"

* Calling test_func(123)
- Returns:
'[]'
- Logs:
TestLog:
{'testData': b'\x00\x00\x00\x00\x00\x00\x00{'}
TestLog:
{'testData': b'\x00\x00\x00\x00\x00\x00\x00{'}
```
- Since both outputs are the same?
- Also: 
```
>>> int.from_bytes(b'\x00\x00\x00\x00\x00\x00\x00{', byteorder='big')
123
```

**Comment by jacqueswww** [comment]
I might be using too old a version, let met try again ;)

**Comment by jacqueswww** [comment]
What is the exact logging statement that is failing?

**Comment by nisdas** [comment]
@jacqueswww Could you try this test case ? this may be able to reproduce the error accurately, this is 
the same log structure in the contract I used

```py
 TestLog: event({testData1: bytes32,testData2: bytes[2064], testData3: bytes[8] })

@public
@constant
def to_bytes(value: uint256) -> bytes[8]:
    return slice(concat("", convert(value, bytes32)), start=24, len=8)

@private
@ constant
def to_bytes32(value: uint256) -> bytes32:
    return convert(value, bytes32)

@public
def test_func(value: uint256):

data2: bytes[2064] = concat(self.to_bytes32(value),self.to_bytes(value),"testing")

  # log will be malformed
   log.TestLog(self.to_bytes32(value),data2,self.to_bytes(value))
   
   loggedValue: bytes32 = self.to_bytes32(value)   
   loggedValue2: bytes[8] = self.to_bytes(value)

   # log will be normal
   log.TestLog(loggedValue,data2,loggedValue2)

```
if the error still doesn't come up then maybe its an issue with geth's abi decoder

**Comment by jacqueswww** [comment]
@nisdas this test case does fail, will investigate.

**Comment by nisdas** [comment]
@jacqueswww Thanks for putting up a quick PR! I just had one comment on the test output but other than that it looks fine.  Let me know when all the tests pass on the PR, then I can test it on my end off your branch :)
