### ISSUE TITLE
Meeting 28th January 2019

### ISSUE THREAD

**Issue by jacqueswww** [ethereum/vyper#1207]
Start: Monday 28th Janurary 2019, 15:00 UTC (https://time.is/UTC)
Hangouts: https://meet.google.com/czc-kuep-jda

Agenda:
- https://github.com/ethereum/vyper/issues/1198
- https://github.com/ethereum/vyper/issues/1199
- https://github.com/ethereum/vyper/issues/1204
- #1181
-  #1214
- #885 
- Finishing up https://github.com/ethereum/vyper/projects/5
- Preparing for https://github.com/ethereum/vyper/projects/6

**Comment by charles-cooper** [comment]
Also #1181?

**Comment by fubuloubu** [comment]
Discuss #1214!
