### ISSUE TITLE
VIP: String type

### ISSUE THREAD

**Issue by nrryuya** [ethereum/vyper#1210]
## Simple Summary
Add `string` type so that the context is clearer in web3, etc.

## Abstract
Add `string` type so that the context is clearer in web3, etc.
Like `bytes` type, add `string[N]` type in contracts and `string` in the ABIs.

## Motivation
For now, `bytes` is the substitute for `string` in Solidity (e.g. #1209) but it's not clear that they are intended to be read as a string or a byte array. Let's use a new type `string` for such cases.

## Specification
At EVM-level, `string[N]` is the same with `bytes[N]` but length or index access are not allowed like [Solidity](https://solidity.readthedocs.io/en/v0.5.2/types.html?highlight=string%20is%20equal%20to%20bytes%20but%20does%20not%20allow%20length%20or%20index%20access.). In the ABI, the type is represented as `string`.

```
# ERC20
name: public(string[5])
symbol: public(string[40])
```

## Backwards Compatibility
This is backwards compatibile.

## Dependencies
N/A

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/)

**Comment by jacqueswww** [comment]
We seem to already have a VIP for this: https://github.com/ethereum/vyper/issues/358 :)

**Comment by nrryuya** [comment]
>We seem to already have a VIP for this: #358 :)

Wow! Long time ago!

**Comment by jacqueswww** [comment]
Implemented, part of Beta-8 release :)
