### ISSUE TITLE
Gas consumption of logging bytes array

### ISSUE THREAD

**Issue by NIC619** [ethereum/vyper#1216]
### Version Information

* vyper Version: 0.1.0b7
* OS: osx
* Python Version (python --version): 3.6.0

### What's your issue about?

I was documenting the gas consumption of [eth2.0 deposit contract](https://github.com/ethereum/deposit_contract/blob/master/deposit_contract/contracts/validator_registration.v.py) and after a little experiments some unintuitive results came up.
**Summary**: with an event that logs a byte array, the larger the byte array data are logged, the **less** gas it cost(and transaction also runs faster in local testing environment).

* Vyper contract code(extracted and modified from the deposit contract) used for testing:
```
Deposit: event({data: bytes[2064]})

@public
def deposit2(deposit_input: bytes[2064]):
    log.Deposit(deposit_input)
```

* Results
    * [tx on rinkeby](https://rinkeby.etherscan.io/tx/0x6238be1f1d27bb53e9226420b7c5f94e2c48c15b0464be7b232abbedb4de7e97) with `deposit_input` being `b'\x01' * 2048`
            * estimated cost for logging: 2048 * 68 + 2064 * 8 + 21000 = 176776
            * actual gas cost = 183846
    * [tx on rinkeby](https://rinkeby.etherscan.io/tx/0xf73b476ddb0662fe7ec3d2254e6b3ff996dfcfcd91ae0f44ed6b4afd5e9ef6a6) with `deposit_input` being `b'\x01' * 1024`
            * estimated cost for logging: 1024 * 68 + 1040 * 8 + 21000 = 98952
            * actual gas cost = 209350
    * [tx on rinkeby](https://rinkeby.etherscan.io/tx/0x6143f0812476ccb05f0c8bee0d4e8f8c671bb1ddca75c94b75b14eb65509cf93) with `deposit_input` being `b'\x01'`
            * estimated cost for logging: 1 * 68 + 17 * 8 + 21000 = 21204
            * actual gas cost = 235204
___

* Try Solidity
```
pragma solidity ^0.4.24;

contract testlogbytes {
    event LogBytes(bytes log);
    
    function logbytes(bytes _log) public {
        emit LogBytes(_log);
    }
}
```

* Results
    * [tx on rinkeby](https://rinkeby.etherscan.io/tx/0x6238be1f1d27bb53e9226420b7c5f94e2c48c15b0464be7b232abbedb4de7e97) with `_log` being `b'\x01' * 2048`
            * estimated cost for logging: 2048 * 68 + 2064 * 8 + 21000 = 176776
            * actual gas cost = 183997
    * [tx on rinkeby](https://rinkeby.etherscan.io/tx/0x7b0b1464f835b67a290778bb0ab072bde86c6e7e2626c6212d97893510afe314) with `_log` being `b'\x01' * 1024`
            * estimated cost for logging: 1024 * 68 + 1040 * 8 + 21000 = 98952
            * actual gas cost = 103715
    * [tx on rinkeby](https://rinkeby.etherscan.io/tx/0x6143f0812476ccb05f0c8bee0d4e8f8c671bb1ddca75c94b75b14eb65509cf93) with `_log` being `b'\x01'`
            * estimated cost for logging: 1 * 68 + 17 * 8 + 21000 = 21204
            * actual gas cost = 24090

### How can it be fixed?

Fill this in if you know how to fix it.

#### Cute Animal Picture

> put a cute animal picture here.

![](https://cdn.pixabay.com/photo/2017/12/21/22/52/dog-3032728_1280.jpg)

**Comment by jacqueswww** [comment]
Very interesting, my initial reaction would be that vypers' performance has to be linear to being reverse of the stated results - because vyper will copy calldata to memory after applying clamps.

**Comment by jacqueswww** [comment]
@NIC619  I think I figured it out - currently vyper pads the bytearray with empty bytes - this would describe the above behaviour.
```
 [with,
              _bytearray_loc,
              /* pack_args_by_32:dest_placeholder */ 
              [add,
                2592,
                [mload, 2528]],
              [seq,
                [repeat,
                  2496,
                  [mload, _bytearray_loc],
                  2080,
                  [seq,
                    [if, [ge, [mload, 2496], 2080], break],
                    [mstore8,
                      [add, [add, _bytearray_loc, 32], [mload, 2496]],
                      0]]]]]
```

**Comment by jacqueswww** [comment]
This is also very interesting because this could indicate where py-evm needs to be optimised, my guess it has to with the `JUMP` opcode (big surprise haha).

**Comment by jacqueswww** [comment]
@NIC619 please try above with https://github.com/ethereum/vyper/pull/1217.

**Comment by NIC619** [comment]
@jacqueswww Great work! The fix works!
Actual gas cost with 2048 bytes input: 180662
Actual gas cost with 1024 bytes input: 102629
Actual gas cost with 1 bytes input: 28186


> This is also very interesting because this could indicate where py-evm needs to be optimised, my guess it has to with the `JUMP` opcode

Can you elaborate more on this? Would like to learn more about it.

**Comment by jacqueswww** [comment]
@NIC619 so basically the biggest performance hindrance on EVM currently is the fact that it doesn't use static jumps - which can be use to do branch prediction or caching when executing a program.
The LLL code I pasted above is basically a loop that zeroes bytes for the full length of an allocated string - so a very long loop using JUMPI & JUMP.

I had a 400 second (from 900s to 500s) decrease in test time on my local machine which would indicate that the way JUMP/JUMPI is handled in py-evm could be optimised. Hope that makes sense? :)
