### ISSUE TITLE
VIP: Drop 3.6 support

### ISSUE THREAD

**Issue by fubuloubu** [ethereum/vyper#1222]
## Simple Summary
Drop support for Python 3.6 (3.7+ only)

## Backwards Compatibility
OS support considerations are important. I think 3.6 is the default on Ubuntu

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/)

**Comment by jacqueswww** [comment]
Not sure why - especially if Ubuntu is defaulting to python 3.6. There are no components we specifically need of 3.7 that 3.6 doesn't have?

**Comment by fubuloubu** [comment]
Yeah, I don't think Web3py is dropping support for 3.6 for a while, and we don't have any features that require 3.7+

Mostly was a conversation @charles-cooper and I were having, but I don't think there's any need right now

**Comment by charles-cooper** [comment]
For posterity's sake, the main argument for pinning to >=3.7 is that dicts are required to be OrderedDicts in 3.7+. But I don't think that's a compelling enough reason in the face of Ubuntu bionic defaulting to 3.6. Instead we should find a linter that detects dicts and tells us to change them to OrderedDicts :)

**Comment by jacqueswww** [comment]
```
grep --color "\= {}" -R ./ | grep ".py"
```
:tongue:
