### ISSUE TITLE
Vyper Docker Failed to compile .vy files in both Kubuntu and Windows 10

### ISSUE THREAD

**Issue by sweetpotatoz** [ethereum/vyper#1228]
### Version Information

* vyper Version (output of `vyper --version`): docker ethereum/vyper      latest              ff682c06fdfe
* OS: both windows 10 and Kubuntu 18.04
* Python Version (output of `python --version`):  using docker container
* Environment (output of `pip freeze`): using docker container

### What's your issue about?
From https://github.com/ethereum/vyper/blob/master/docs/installing-vyper.rst

Please include information like:

* full output of the error you received
FileNotFoundError: [Errno 2] No such file or directory: 'crowdfund.vy'
crowdfund.vy is the example file that i copied to local {relative path and absolute path produce same error)

* what command you ran
docker container run --name crowdfund ethereum/vyper crowdfund.vy 

run in both kubuntu and Win. 10

* the code that caused the failure (see [this link](https://help.github.com/articles/basic-writing-and-formatting-syntax/) for help with formatting code)

### How can it be fixed?

Fill this in if you know how to fix it.

#### Cute Animal Picture

> put a cute animal picture here.

**Comment by sweetpotatoz** [comment]
however running inside the container is fine
docker build https://github.com/ethereum/vyper.git -t vyper:1
docker run -it --entrypoint /bin/bash vyper:1
vyper examples/crowdfund.vy

above are ok
but if i run docker container run --name crowdfund vyper:1 crowdfund.vy
same error again (not path issue)

**Comment by jacqueswww** [comment]
Seems like I'll have to push a new version, and see what's up :+1:

**Comment by sweetpotatoz** [comment]
managed to run it this way,

in Windows
docker container run -v //c/temp/vyper-test-contract.vy:/code/vyper-test-contract.vy ethereum/vyper vyper-test-contract.vy
Assuming vyper-test-contract.vy is the .vy contract file that we want to compile, and reside in host machine C:\temp

if we want to test .vy files that are already inside the container we can run without -v
docker container run ethereum/vyper examples/crowdfund.vy

crowdfund.vy is already inside the container /code/examples

seems that we cannot pass .vy files in our host machine directly to the vyper container excutables without using -v

**Comment by jacqueswww** [comment]
@sweetpotatoz I looked at the docker file and saw that the local dir is mapped to /code/. 
So for my this worked:
```
$ docker run vyper /code/one.vy
0x6100e856600035601c52740100000000000000000000000000000000000000006020526f7fffffffffffffffffffffffffffffff6040527fffffffffffffffffffffffffffffffff800000000000000000000000000000006060 ...
```

**Comment by jacqueswww** [comment]
See also updated docs: https://vyper.readthedocs.io/en/latest/installing-vyper.html#docker
