### ISSUE TITLE
ERC20 Contract example: use automatically generated getter for `balances`

### ISSUE THREAD

**Issue by ssteiger** [ethereum/vyper#1241]
### Version Information
--

### What's your issue about?

The example contract at:
https://github.com/ethereum/vyper/blob/master/examples/tokens/ERC20.vy

With vyper automatically generating getter methods for public state variables we could rename the state variable `balances` to `balanceOf`, declare it `public` and remove the `balanceOf()` method.

#### Rational
If we view the example contracts as educational material, we could use this chance to introduce people to the vyper feature of automatically generating getters for public state variables.

### How can it be fixed?
* change line 10 to: `balanceOf: public(map(address, uint256))`

* remove lines 37 - 45

* add a comment above line 10:
```
# NOTE: By declaring `balanceOf` as public, vyper automatically generates a 'balanceOf()' getter 
#       method to allow access to account balances.
#       The _KeyType will become a required parameter for the getter and it will return _ValueType.
#       See: https://vyper.readthedocs.io/en/v0.1.0-beta.8/types.html?highlight=getter#mappings
```

#### Cute Animal Picture

![image](https://user-images.githubusercontent.com/10925195/52534823-927ae900-2d46-11e9-86aa-8b3711a42c6f.png)

**Comment by fubuloubu** [comment]
Also: replace 7 other instances of `balance` with `balanceOf` (but that's probably obvious)

Nothing technically wrong with this approach!
