### ISSUE TITLE
Remove __init__ name from abi json.

### ISSUE THREAD

**Issue by jacqueswww** [ethereum/vyper#1244]
### What's your issue about?
Remove non-standard 'name' attribute from the constructor function.
Remove non-standard 'name' attribute from the default function.

e.g.
`{"name": "__init__", "outputs": [], "inputs": [], "constant": false, "payable": false, "type": "constructor"}`

### How can it be fixed?

For `__default__`:

* Investigate ABIv2 expectations for the "fallback" function feature
* Remove field "name" from ABI output (in Vyper, as in Python, `__[underscored_names]__` should _never_ be used externally)
* Change the "type" field to "fallback"
* It appears that the fallback cannot have the fields "inputs" or "outputs" as it does not decode data explicitly (leaving it to internal use of #1181 to decode passed data)

**Comment by fubuloubu** [comment]
Also check out `__default__`

**Comment by jacqueswww** [comment]
Starting on this.

**Comment by NikitaMishin** [comment]
This leads to error when run vyper-run (it assumes that constuctor has name)
