### ISSUE TITLE
Unknown Interface Exception

### ISSUE THREAD

**Issue by nickemmons** [ethereum/vyper#1246]
### Version Information

* vyper Version: 0.1.0b8
* OS: osx
* Python Version: 3.7.1

### What's your issue about?

Unknown interface exception when compiling to `abi`

Input:
```
vyper -f abi contracts/ballot.vy
```

Output:
```
Error compiling:  contracts/ballot.vy
vyper.exceptions.StructureException: line 3: Unknown interface BallotInterface
import interfaces.ballot_interface as BallotInterface
```

This is happeneing when trying to use a custom interface in a Vyper contract.  

Here is how it is imported:

```
import interfaces.ballot_interface as BallotInterface 
implements: BallotInterface
```

Here is the file structure
```
test_project/
    contracts/
        ballot.vy
    interfaces/
        ballot_interface.vy
```

### How can it be fixed?

[#1245](https://github.com/ethereum/vyper/pull/1245)

#### Cute Animal Picture

![Dog in a cup](https://images.pexels.com/photos/39317/chihuahua-dog-puppy-cute-39317.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260)

**Comment by fubuloubu** [comment]
I feel like paths should be relative, similar to how Python packages work.

So I would propose that `ballot.vy` look like:
```python
import ..interfaces.ballot_interface as BallotInterface 
implements: BallotInterface
```

@charles-cooper @jacqueswww thoughts?

**Comment by charles-cooper** [comment]
> I feel like paths should be relative, similar to how Python packages work.

I believe this issue is unrelated to path resolution, but I think the best option would be a compiler flag which sets the root directory, otherwise it will assume the root directory is the current directory.

**Comment by jacqueswww** [comment]
I don't like relative imports.

**Comment by nickemmons** [comment]
@jacqueswww Thanks, it works with the latest master.  Will close this issue now
