### ISSUE TITLE
`__default__` function ABI has wrong type

### ISSUE THREAD

**Issue by fubuloubu** [ethereum/vyper#1247]
### What's your issue about?
`__default__` fallback function produces an incompatible ABI output from the equivalent Solidity contract. Unsure what the "correct" functionality is per ABIv2 (cc @davesque), but this is a problem for integration with external tooling.

For example, this Solidity program:
```javascript
contract Untitled
{
    function () external {
        revert();
    }
}
```
produces:
```json
{"payable": false,"stateMutability": "nonpayable","type": "fallback"}
```
whereas this Vyper program:
```python
@public
def __default__():
    assert False
```
produces:
```json
{"name": "__default__","outputs": [],"inputs": [],"constant": false,"payable": false,"type": "function"}
```

### How can it be fixed?
- Investigate ABIv2 expectations for the "fallback" function feature
- Remove field "name" from ABI output (in Vyper, as in Python, `__[underscored_names]__` should *never* be used externally)
- Change the "type" field to "fallback"
- It appears that the fallback cannot have the fields "inputs" or "outputs" as it does not decode data explicitly (leaving it to internal use of #1181 to decode passed data)

Related to #1244

**Comment by davesque** [comment]
Yeah, Solidity is outputting the correct JSON ABI in this case.  The details are laid out in this section of the Solidity ABI spec: https://solidity.readthedocs.io/en/v0.5.3/abi-spec.html#json

Here's a screenshot with the relevant sections highlighted:
<img width="745" alt="screen shot 2019-02-11 at 9 24 57 pm" src="https://user-images.githubusercontent.com/791437/52611680-e5869600-2e43-11e9-9e1c-326d00529504.png">

**Comment by jacqueswww** [comment]
Closing in favor of #1244
