### ISSUE TITLE
VIP: Improve persistent contract address syntax

### ISSUE THREAD

**Issue by jacqueswww** [ethereum/vyper#1251]
## Simple Summary
Currently Vyper has redundant syntax, this proposals aims to choose the more explicit option.

## Abstract
Currently an artefact of #846 is that a persistent contract address can be defined as `token: address(Bar)` and `token: Bar`. This proposal elects to only allow `address(Bar)` as this is the more explicit of the two

## Motivation
Explicit is better than implicit.

## Specification
ContractType internally is represented as address type, having _address_ annotated in make this technical difference clearer.

## Backwards Compatibility
Not backwards compatibility, contract writers will have to change their code.

## Dependencies
None

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/)

**Comment by jacqueswww** [comment]
Note this is implemented in #1250

**Comment by fubuloubu** [comment]
I would propose that the syntax instead be `Bar(address)` as the interface serves as a "wrapper" around an address variable, adding explicit call mechanisms for the defined interface.

This also matches with the ad-hoc use case e.g.:
```python
def test(_contract: address):
     Bar(_contract).foo()
```
In this use case, the address variable is "applied" to the interface, which instantiates it. I think this suggestion makes the two align better.

**Comment by charles-cooper** [comment]
Or c-style ` Bar*` would make it clear that it's a pointer (aka address) to a contract which implements Bar

**Comment by fubuloubu** [comment]
Oh jeez, let's not introduce pointers lol

Plus, `Bar* address` probably wouldn't work well in Python AST without some weirdness in the parser.

**Comment by jacqueswww** [comment]
@charles-cooper @fubuloubu if the two of you can agree on either `self.token = Bar(adr)` or `self.token = adr` - I can go ahead an make the necessary changes. At this point there isn't much benefit in one over the other in my opinion, and would prefer getting the PR merged as the Meta issue is diverging the branches really fast.

**Comment by fubuloubu** [comment]
I like `Bar(adr)` (and `token: Bar`) for the syntax. `token: address (Bar)` would require a change from what's current, and we've had no complaints about it (unlike with mappings), so why change it?

**Comment by charles-cooper** [comment]
@jacqueswww @fubuloubu I think we should merge the PR and then we can discuss and tweak the syntax later (before RC).

**Comment by fubuloubu** [comment]
If the PR is merged now it causes a breaking change on syntax for the users we have. I would suggest against that.

**Comment by charles-cooper** [comment]
Oh, I see. Let's just go with Bar(address) and token: Bar as suggested then.

**Comment by fubuloubu** [comment]
The only changes in that case would be on assignment, bringing `self.foo = Foo(foo_address)` in line with `Foo(foo_address).bar()`

**Comment by jacqueswww** [comment]
@fubuloubu @charles-cooper  so we have consensus on the following?

```python
bar_contract: Bar

def test(param: address):
     self.bar_contract = Bar(param)
```

No other ways will be support henceforth.

**Comment by fubuloubu** [comment]
LGTM!

**Comment by charles-cooper** [comment]
Yep

**Comment by jacqueswww** [comment]
Done.
