### ISSUE TITLE
vyper-serve: implement/return all possible compile types

### ISSUE THREAD

**Issue by ssteiger** [ethereum/vyper#1270]
## Simple Summary
`vyper-serve`: Expose all possible compilation formats.

## Abstract
Currently `vyper-serve` only returns the following formats:
`['bytecode', 'bytecode_runtime', 'abi', 'source_map', 'method_identifiers', 'ir']` 

see code [here](https://github.com/ethereum/vyper/blob/e83d4b6d0b2c74d4dead2b0c402677f9d200cd6f/bin/vyper-serve#L88)

But vyper can be compiled to the following formats:
```
 bytecode (default) - Deployable bytecode
 bytecode_runtime   - Bytecode at runtime
 abi                - ABI in JSON format
 abi_python         - ABI in python format
 source_map         - Vyper source map
 method_identifiers - Dictionary of method signature to method identifier.
 combined_json      - All of the above format options combined as single JSON output.
 interface          - Print Vyper interface of a contract
 external_interface - Print Externa Contract of a contract, to be used as outside contract calls.
````

## Motivation
Providing endpoints to all possible compilation formats allowes for catering to more possible use cases.
Also this seems trivial to implement.

## Specification
Ok, no - lol.
> change this line https://github.com/ethereum/vyper/blob/e83d4b6d0b2c74d4dead2b0c402677f9d200cd6f/bin/vyper-serve#L88 from:
`['bytecode', 'bytecode_runtime', 'abi', 'source_map', 'method_identifiers', 'ir']`
>
> to:
> `['bytecode', 'bytecode_runtime', 'abi', 'abi_python', 'source_map', 'method_identifiers', 'combined_json' 'ir', 'interface', 'external_interface']`

## Backwards Compatibility
--

## Dependencies
--

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/)

**Comment by ssteiger** [comment]
Was there a reason for why the other formats were omitted from vyper-serve?

**Comment by jacqueswww** [comment]
@ssteiger I think the main reason was is that we forgot we added them later :tongue:  I would suggest we just change that line to expose them all e.g. `vyper.compiler.output_formats_map.keys()`.
