### ISSUE TITLE
State leakage across test runs when using parrellization

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/vyper#1273]
### What is wrong.

The tests at `tests/examples/safe_remote_purchase/test_safe_remote_purchase.py` fail when run using `pytest-xdist` to parallelize test runs.

```
    def test_abort(w3, assert_tx_failed, check_balance, get_contract, contract_code):
        a0, a1, a2 = w3.eth.accounts[:3]
        c = get_contract(contract_code, value=2)
        # Only sender can trigger refund
        assert_tx_failed(lambda: c.abort(transact={'from': a2}))
        # Refund works correctly
        c.abort(transact={'from': a0, 'gasPrice': 0})
>       assert check_balance() == (INIT_BAL_a0 - w3.toWei(2, 'ether'), INIT_BAL_a1)
E       assert (100000000000...0000000000000) == (9999980000000...0000000000000)
E         At index 0 diff: 1000000000000000000000000 != 999998000000000000000000
E         Use -v to get the full diff

tests/examples/safe_remote_purchase/test_safe_remote_purchase.py:62: AssertionError
```

replicate by installing `pytest-xdist` and running with

```
pytest tests/examples/safe_remote_purchase/test_safe_remote_purchase.py -n 2
```

It's likely this isn't deterministic and you may need to run the full suite.

### How can it be fixed.

Figure out where statefulness is leaking across test runs and fix it.

**Comment by pipermerriam** [comment]
Updating the `w3` and `tester` fixtures in `tests/conftest.py` did not remedy this.

**Comment by fubuloubu** [comment]
`patch_log_filter_remove`?

**Comment by jacqueswww** [comment]
Whilst we are optimising thests, is there a way to make eth tester mine blocks without doing PoW (PoA maybe?). I think this is a huge bottle neck atm. I adjusted the difficulty lower but hardly had any effect. I just know for alot of the example tests forwarding blocks takes most of the tests time. Parrallelisation should be the last optimization we make.

**Comment by pipermerriam** [comment]
@jacqueswww yes.  It's likely that `eth-tester` isn't taking advantage of this since it's relatively new.  We have an API for doing this (docs are broken so I'm linking you to the test suite where it's used)

https://github.com/ethereum/py-evm/blob/master/tests/core/builder-tools/test_chain_construction.py#L133

the `eth-tester` chain that the `PyEVMBackend` uses should be updated to use some version of this API to disable the POW check.

**Comment by pipermerriam** [comment]
> Parrallelisation should be the last optimization we make.

Can you explain the reasoning behind this?  In most CI environments I've been able to gain an easy 2-3x speed increase simply by parallelizing with `pytest-xdist`.

**Comment by jacqueswww** [comment]
@pipermeriam By last resort, I mean it should be the last step we switch on after all other optimisations have been made.

 So in any program I write, I see parrallelisation as the last resort, because it's cheating right? You are hiding the aggregate work that gets done. :-) Yeah I am a old riser and believe in the philosophy of `if you want fast programs, give a programmer a slow computer` :-P

**Comment by jacqueswww** [comment]
@pipermeriam Thinking of it some more, lately I have realized that I actually get far more consistent metrics on single core performance accross all processors and platforms. So it make it so much easier to have a quick yardstick guage. This is because the actual performance increase per core is tiny across processor generations.

**Comment by pipermerriam** [comment]
@jacqueswww I don't see the reasoning in either of those to not enable paralellization in the CI environment.

- Parallelization isn't required and won't be the default.  Locally, tests will still run single core unless you provide extra flags
- CI is a shared hosting environment making it an environment unsuitable for measuring performance.
- I agree with your logic in the context of writing an actual application, but I don't see how that logic extends to tests.  Fast test suite runs speed up the iteration cycle for development which has very tangible productivity boosts.

**Comment by fubuloubu** [comment]
Agreed on parallelizing all the tests. It's not that big a deal, easy win!

**Comment by jacqueswww** [comment]
Sure no problem.

Also, you are wrong that vyper isn't an `Application` actually you might be right as it's a `MetaApplication` :P the test run decreased by 400 seconds when I fixed a bug on ABI handling, pyetherum test suite was 2x faster than switching to eth tester - this is super useful. And I bet you if you guys enhance pyevm significantly one can pick it up. That's also why we leverage get_with_gas_estimation (will become get_contract eventually).

**Comment by fubuloubu** [comment]
In my mind, the ideal structure of the compiler is a series of functions that moves one data structure form to another. If each layer is a pure function, there should be no issue testing each one in parallel, as the data in and out of each layer is what's important (pre/post conditions for a test)

**Comment by jacqueswww** [comment]
That's not the truth though, it's about what you produce - because you could still be producing a long list of jumps and store codes with your pure functions, or reusing constants ineffectively  that are directly correlated to actual time on evm, thereby test time.

That level of testing is very primitive and

**Comment by jacqueswww** [comment]
So all I want leave here as food for thought, is there is and could be so much more to tests than just testing functions and coverage :-) {or I would like to think so}.

**Comment by pipermerriam** [comment]
> you are wrong that vyper isn't an `Application`

I wasn't intending to say Vyper isn't an application.  I was saying the tests aren't the application and thus I don't apply the same standards for performance gains (thus being fine with gaining speed through concurrency).  Sorry for any misunderstanding.

**Comment by jacqueswww** [comment]
Ah yes, sorry I misread that ;)

**Comment by pipermerriam** [comment]
> And I bet you if you guys enhance pyevm significantly one can pick it up

Yeah, we're aware, and it's very likely that the core EVM performance will get some :heart: in the near future.

**Comment by jacqueswww** [comment]
I am busy cleaning up conftest a little and bumping our test versions. Will look into the state leaking as part of it.

**Comment by jacqueswww** [comment]
@pipermerriam palatalisation made the tests run ~5x faster :smile:

**Comment by pipermerriam** [comment]
That's sexy

**Comment by fubuloubu** [comment]
That's awesome! So... you found the problem? (or somehow avoided it by upgrading? lol)

**Comment by jacqueswww** [comment]
Yes, if you check the PR. The tests were failing because of wrong assumptions in the tests regarding balances & pytest scoping.
