### ISSUE TITLE
Meeting 11th March 

### ISSUE THREAD

**Issue by jacqueswww** [ethereum/vyper#1305]
Start: Monday 11th March 2019, 15:00 UTC (https://time.is/UTC)

Jitsi: https://meet.jit.si/IndifferentSquidAdaptRegularly
Hangouts Fallback : https://meet.google.com/czc-kuep-jda

Agenda:
- #1277
- refactoring stuff (@pipermerriam @davesque)
- https://github.com/ethereum/vyper/issues/1328
- https://github.com/ethereum/vyper/issues/1268
- https://github.com/ethereum/vyper/issues/1019
- https://github.com/ethereum/vyper/pull/1325
- Beta 9 release

**Comment by charles-cooper** [comment]
Is this on Monday the 11th of March or Sunday the 10th?

**Comment by jacqueswww** [comment]
Monday the 10th sorry ;)

**Comment by jacqueswww** [comment]
https://github.com/ethereum/vyper/issues/1339

**Comment by jacqueswww** [comment]
Custom parser notes from meeting: https://github.com/ethereum/vyper/issues/563#issuecomment-471587519
