### ISSUE TITLE
Unused optimisation.

### ISSUE THREAD

**Issue by jacqueswww** [ethereum/vyper#1306]
### Version Information

master

### What's your issue about?
Investigate listed TODO: https://github.com/ethereum/vyper/blame/master/vyper/optimizer.py#L99
```python
    # Turns out this is actually not such a good optimization after all
    elif node.value == "with" and int_at(argz, 1) and not search_for_set(argz[2], argz[0].value) and False:
        o = replace_with_value(argz[2], argz[0].value, argz[1].value)
        return o
```

### How can it be fixed?

I have not fully investigated, but I suspect we can just drop the optimisation.

**Comment by charles-cooper** [comment]
it looks like the goal of the optimization was in the case of a with statement like
```
(with x <expr> (seq ... <uses x>...))
```
to replace instances of `x` with the original `<expr>`. this is indeed a poor optimization where the `with` statement is used to cache the output of a complex expression (or possibly even constants which require a PUSH), but could be a good optimization if the expression is only one opcode.
