### ISSUE TITLE
VIP: Remove sha3 alias

### ISSUE THREAD

**Issue by jacqueswww** [ethereum/vyper#1328]
## Simple Summary
Remove the `sha3` function, in favour of only using `keccak256`

## Abstract
Remove the `sha3` function, in favour of only using `keccak256`.

## Motivation

`keecak256` and `sha3` are currently aliases of each, however talking in general and standardised terms keccak256 is not the same function as sha3, therefore the proposal to remove `sha3` completely to avoid confusion.

## Specification
A call to sha3:
```
sha3(val)
```
Will throw a compiler error, with a message "sha3 function has been deprecated in favour of keccak256".

## Backwards Compatibility
This change is not backwards compatible.

## Dependencies
None

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/)

**Comment by jakerockland** [comment]
@jacqueswww can I go ahead and implement this one?

**Comment by jakerockland** [comment]
@jacqueswww I got restless 😂 🙃

**Comment by fubuloubu** [comment]
Closed by #1503
