### ISSUE TITLE
VIP: Allow 'address' to be passed as size of byte array

### ISSUE THREAD

**Issue by ssteiger** [ethereum/vyper#1332]
## Simple Summary
Allow the `address` constant to be passed as size when defining an array.

## Motivation
Currently vyper allows the use of two kinds of arrays:

byte arrays:
`example_bytes: bytes[100] = b"\x01\x02\x03"`

string arrays:
`example_str: string[100] = "Test String"`

For some contracts it would be nice to be able to pass an array of addresses as an argument
Example from the ERC777 standard:

```
def __init__(_name: string[32],
             _symbol: string[16],
             _totalSupply: uint256,
             _granularity: uint256,
             _defaultOperators: bytes[address]=""
            ):
```

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/)

**Comment by jacqueswww** [comment]
I think we can already do this, an array of addresses would be defined as:
```
_defaultOperators: address[5]
```

Which just means I can take an array of addresses up until 5 slots.
