### ISSUE TITLE
Meeting 25th March 2019

### ISSUE THREAD

**Issue by jacqueswww** [ethereum/vyper#1341]
Start: Monday 25th March 2019, 15:00 UTC (https://time.is/UTC)

Jitsi: https://meet.jit.si/IndifferentSquidAdaptRegularly
Hangouts Fallback : https://meet.google.com/czc-kuep-jda

- https://github.com/ethereum/vyper/pull/1361 Relative paths for imports. {approved, VIP created at https://github.com/ethereum/vyper/issues/1367}
- https://github.com/ethereum/vyper/issues/1355 Allow equality checks between string types.  {approved}
- https://github.com/ethereum/vyper/issues/1345 Return codes {approved}
- https://github.com/ethereum/vyper/issues/1362 CREATE code copy {approved}
- https://github.com/ethereum/vyper/issues/1360 Codebase hardning strategy {approved}
- https://github.com/ethereum/vyper/issues/1363 Road to a custom parser {approved}
- Parse function refactoring (@jacqueswww)

**Comment by fubuloubu** [comment]
Next: #1368
