### ISSUE TITLE
VIP: Change `throw` to `raise`, allow reason string

### ISSUE THREAD

**Issue by charles-cooper** [ethereum/vyper#1342]
## Motivation
`throw` is undocumented, and `raise` is already python syntax. Also, reason strings are now available for revert.

## Specification
Remove the `throw` function, and add `raise` to the grammar which requires a reason string. The behavior of `raise <reason_string>` should be the same as `assert False, <reason_string>`.

## Backwards Compatibility
Removes `throw` but it's undocumented.

## Dependencies
None but related to https://github.com/ethereum/vyper/pull/1325

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/)

**Comment by jacqueswww** [comment]
I am in favour of this :+1:
