### ISSUE TITLE
VIP - Allow equality checks between string types.

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/vyper#1355]
## Simple Summary

Ability to compare equality of two `string` variable is useful and somewhat trivial to support.

## Abstract

Currently, assuming two `string` type variable `a` and `b`, the compiler does not allow `a == b` comparisons.

Byte-wise comparison is expensive and violates the requirement that computation be "decidable", we can get around this by using `keccak`.

## Motivation

To allow equality checks between strings

## Specification

when the compiler encounters `a == b` when both `a` and `b` are strings, this should be converted to `keccak(a) == keccak(b)`.

Gas cost optimizations to be considered.

- Consider doing a *pre* check of their lengths
- Consider special casing `lengh-0` strings to always be equal

## Backwards Compatibility

None?

## Dependencies

Nope

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/)

**Comment by fubuloubu** [comment]
> Consider doing a pre-check of their lengths

In the happy case (lengths match) this will cost a small amount more, and `keccak(a) == keccak(b)` will still fail if `a` and `b` are not the same length.

> Consider special casing `length-0` strings to always be equal

Same criticism as above. `keccak(null_string) == keccak(null_string)`

**Comment by jacqueswww** [comment]
@fubuloubu I will model the gas gains of doing the length precheck and then we can decide if it's worth it?
