### ISSUE TITLE
Codebase Hardening Strategy

### ISSUE THREAD

**Issue by fubuloubu** [ethereum/vyper#1360]
Meta-issue about steps we should take to harden the codebase in advance of v0.1.0rc1

- [x] Add MyPy type-checking (Added #1118)
- [x] Linting, doctest, others (In progress #1259)
- [x] Refactor test cases into more general [fuzzer-based](https://www.owasp.org/index.php/Fuzzing) test cases (using [Hypothesis](https://hypothesis.works/) or other lib)
  - Validate clamps at ABI level (bypass eth-abi/web3py), but maybe symbolic analysis is better?
  - Added #1402
- [x] Explore restarting [Vyper Semantics for K](https://github.com/kframework/vyper-semantics)
  - Grant or engagement with an independant 3rd party, or Runtime Verification
  - Added #1403
- [x] Explore adding [symbolic analysis](https://github.com/trailofbits/manticore) test cases for more [complex internal features](https://github.com/ethereum/vyper/blob/master/vyper/functions/functions.py)
  - Super-strong verification that complex internal features are properly implemented
  - Small enough to be practical with this approach (but maybe not in CI...)
  - Added #1404
- [x] Develop [property-based](https://hypothesis.works/articles/how-not-to-die-hard-with-hypothesis/) verification of [example programs](https://github.com/ethereum/vyper/tree/master/examples)
  - (WIP: https://github.com/fubuloubu/hypothesis-ethereum)
  - Also helps demonstrate stronger verification exercises to newcomers
  - Added #1405

**Comment by davesque** [comment]
Can we add an item for adding type annotations across the codebase?

**Comment by fubuloubu** [comment]
Isn't that what #1118 (mentioned above) does?

**Comment by davesque** [comment]
@fubuloubu Yes.  I guess I misunderstood the meaning of checking that item off this list.  Most of the code base still doesn't have type annotations even though type checking *is* happening as part of the linting process.

**Comment by davesque** [comment]
@fubuloubu So maybe that item shouldn't be checked-off.

**Comment by fubuloubu** [comment]
I am checking off items as Issues get made and added to the RC1 Project (so we can keep track of all the ideas)

**Comment by davesque** [comment]
@fubuloubu Ah, I gotcha.

**Comment by jacqueswww** [comment]
https://github.com/ethereum/vyper/issues/1363

**Comment by fubuloubu** [comment]
@davesque Something that @jacqueswww mentioned on that call where your expertise may be helpful: We might want to more explicitly test the ABI interface in Vyper through lower-level checks, either with Hypothesis (starting there) or symbolic execution (more complex, but a higher degree of assurance)

**Comment by davesque** [comment]
@fubuloubu Ahh, sorry I missed it.  What parts of the vyper codebase constitute its interface with the ABI?

**Comment by jacqueswww** [comment]
@davesque  mostly clamp on function arg parsing, https://github.com/ethereum/vyper/blob/master/vyper/parser/parser.py#L270.  But we could 'course testing clamping further in the body of the functions as well ;)

**Comment by fubuloubu** [comment]
Added issues for all of these suggestions. No further suggestions where made in #1389, closing this meta-issue.
