### ISSUE TITLE
msg missing from reserved_words

### ISSUE THREAD

**Issue by mikeshultz** [ethereum/vyper#1364]
### Version Information

* vyper Version (output of `vyper --version`): master
* OS: n/a
* Python Version (output of `python --version`): n/a
* Environment (output of `pip freeze`): n/a

### What's your issue about?

`msg` appears to be missing from `vyper.utils.reserved_words`

### How can it be fixed?

Add `msg` to `vyper.utils.reserved_words`

**Comment by mikeshultz** [comment]
Since `contract` is also in `reserved_words`, is `struct` missing as well?

**Comment by davesque** [comment]
@mikeshultz Yep, I think those words belong in those collections.  Making a PR now to address this and other related things.

**Comment by jacqueswww** [comment]
One of the faster issues we can close ;)
