### ISSUE TITLE
Meeting 8th April 2019

### ISSUE THREAD

**Issue by jacqueswww** [ethereum/vyper#1368]
Start: Monday 8th April 2019, 15:00 UTC (https://time.is/UTC)

Jitsi: https://meet.jit.si/IndifferentSquidAdaptRegularly
Hangouts Fallback : https://meet.google.com/czc-kuep-jda

Agenda
  - #1347
  - #1371
  - https://github.com/ethereum/vyper/issues/806#issuecomment-479982918
 - https://github.com/ethereum/vyper/issues/711
 - #1382

**Comment by fubuloubu** [comment]
Next: #1389
