### ISSUE TITLE
ERC20 and address assignment error

### ISSUE THREAD

**Issue by hustnn** [ethereum/vyper#1372]
Can I know the relationship between ERC20 and address type? I am confused about it.

I have a storage:
token: ERC20

initilize with an address:
@public
def setup(token_addr: address):
assert (self.token == ZERO_ADDRESS) and token_addr != ZERO_ADDRESS
self.token = ERC20(token_addr)

contract Factory:
def getExchange(token_addr: address) -> address: constant

assert self.factory.getExchange(self.token) == self

We I can getExchange and got this error: vyper.exceptions.TypeMismatchException: Typecasting from base type address(ERC20) to address unavailable

**Comment by fubuloubu** [comment]
It looks like `factory.getExchange(address)` is barking at you. It should be `factory.getExchange(ERC20)`

@jacqueswww is this compiler check over-defined here?

**Comment by jacqueswww** [comment]
@hustnn @fubuloubu `self.factory` doesn't exist.

**Comment by jacqueswww** [comment]
@fubuloubu I think the best approach here is to just allow it getExchange() to access `ConractType` like ERC20. The reason is that it a.) seems natural b.) this is what happens internally anyways with `ContractType`.

**Comment by hustnn** [comment]
@jacqueswww yes,  self.factory is declared as Factory.

contract Factory:
    def getExchange(token_addr: address) -> address: constant

**Comment by fubuloubu** [comment]
@hustnn #1373 to fix a small bug with this functionality. Thanks for raising it up!

**Comment by hustnn** [comment]
@jacqueswww @fubuloubu 

So do I can still use my posting code after rebuilding vyper?

**Comment by fubuloubu** [comment]
@hustnn you should be able to yes! either on latest `master` or whenever the next release is!

**Comment by hustnn** [comment]
@jacqueswww @fubuloubu 

Hi, it seems not fixed completely.

I defined a function:

# @return Address of Token that is sold on this exchange.
@public
@constant
def tokenAddress() -> address(ERC20):
    return self.token

when I run  vyper -f abi exchange.vy, the error occur 
vyper.exceptions.InvalidTypeException: line 458: Invalid base unit
def tokenAddress() -> address(ERC20):

**Comment by jacqueswww** [comment]
@hustnn please just use `def tokenAddress() -> address` or even easier just do `token: public(ERC20)` if you'd like to make a getter.

**Comment by hustnn** [comment]
@jacqueswww
 def tokenAddress() -> address:
    return self.token

also failed with the error " Trying to return base type address(ERC20), output expecting address
    return self.token"
