### ISSUE TITLE
Cannot return ERC20 token address from contract

### ISSUE THREAD

**Issue by Pet3ris** [ethereum/vyper#1376]
Hi There,

I'm trying to compile the following contract running `master`:

**Input contract**

```python
from vyper.interfaces import ERC20

token: ERC20

@public
@constant
def tokenAddress() -> address:
    return self.token
```

**Output**

```
vyper.exceptions.TypeMismatchException: line 8: Trying to return base type address(ERC20), output expecting address
    return self.token
-----------^
```

I can fix it temporarily by changing the `address` to an `address(ERC20)`, this compiles to runtime bytecode, but doesn't compile when extracting the ABI:

**Input contract 2 `(-f abi)`**

```python
from vyper.interfaces import ERC20

token: ERC20

@public
@constant
def tokenAddress() -> address(ERC20):
    return self.token
```

**Output**

```
vyper.exceptions.InvalidTypeException: line 7: Invalid base unit
def tokenAddress() -> address(ERC20):
------------------------------^
```

**Comment by Pet3ris** [comment]
@jacqueswww - thanks a lot, may I selfishly suggest elements of the Uniswap contract for different ways of integrating `ERC20` tokens as it has its own as well as external :).

**Comment by jacqueswww** [comment]
Once I have assembled the PR, let's test it against uniswap before merging it ;)
