### ISSUE TITLE
Optimizer: 'ne' can compile to an xor

### ISSUE THREAD

**Issue by charles-cooper** [ethereum/vyper#1386]
Right now `ne(x, y)` compiles to `iszero(eq(x, y))`, which is 6 gas + stack operations. It could be `xor(x,y)` which is 3 gas.

**Comment by fubuloubu** [comment]
`ne(x, y)` to `xor(x, y)` (non-zero is true)

For clarification

**Comment by charles-cooper** [comment]
> ne(x, y) to xor(x, y) (non-zero is true)

Juts to add to that, here's a truth table

|   | 0b00 | 0b01 | 0b10 | 0b11 |
| --- | --- | --- | --- | --- |
| **0b00** | 0b00 | 0b01 | 0b10 | 0b11 |
| **0b01** | 0b01 | 0b00 | 0b11 | 0b10 |
| **0b10** | 0b10 | 0b11 | 0b00 | 0b01 |
| **0b11** | 0b11 | 0b10 | 0b01 | 0b00 |

**Comment by charles-cooper** [comment]
Another neat optimization that C compilers use is xor'ing a register with itself instead of setting the register value to 0. The EVM analog would be replacing the sequence `POP PUSH 0` with `XOR`. Although I'm not sure if that sequence is super common.

**Comment by charles-cooper** [comment]
Resolved in https://github.com/ethereum/vyper/pull/1387

**Comment by charles-cooper** [comment]
Reopening because the optimizer should also do this for `if_unchecked` statements. (One line change).
