### ISSUE TITLE
External Call to Struct not working

### ISSUE THREAD

**Issue by nickemmons** [ethereum/vyper#1392]
### Version Information

* vyper Version (output of `vyper --version`): 0.1.0b8
* OS: osx
* Python Version (output of `python --version`): 3.7.1

### What's your issue about?

I am unable to interact with structs in 1 contract (let’s call it contract A) that I get as a return value from a function in another contract (let’s call it contract B).

For example, I’m defining the struct in both contract A and B as follows:

```
struct Model:
    x: timedelta
    y: uint256
```

The function (in contract B) that returns the struct is this:

```
@public
@constant
def getModel(_model: address) -> Model:
    return self.models[_model]
```

I can pull it into contract A like this and have it compile successfully:

```
contract B:
    def getModel(_model: address) -> Model: constant
```

But when I try to interact with the members of the struct (i.e. x and y), like this:

```
m: uint256 = B(self.b).getModel(self.model).y
```

I get a compilation error saying `Invalid output type: struct`. Any idea why this would be happening (why it would compile fine when declaring the contract at the top but failing in the function body)?

**Comment by charles-cooper** [comment]
Seems to be an error in how the interface is imported. When the function is defined locally it compiles OK:
```python
struct Model:
    x: timedelta
    y: uint256

contract B:
    def getModel(_model: address) -> Model: constant

b: address
model: address

_models: map(address, Model)

@public
@constant
def getModelA(addr: address) -> Model :
    return self._models[addr]

@public
def foo() -> uint256 :
    # m: uint256 = B(self.b).getModel(self.model).y # <-- doesn't compile
    m: uint256 = self.getModelA(self.model).y
    return m
```
