### ISSUE TITLE
Overload of send

### ISSUE THREAD

**Issue by robinsierra** [ethereum/vyper#1396]
Vyper version: 0.1.0b9

### What's your issue about?

Vyper doesn't allow naming functions after built-in functions like `raw_call`. However, it is possible to call a function `send`. This seems like an inconsistency in the language.
```
@public
def send():
	pass
```

### How can it be fixed?

Disallow functions called `send`.

**Comment by fubuloubu** [comment]
Good find!

**Comment by jacqueswww** [comment]
I am afraid send is a whitelisted word, because `send` is already present as function in existing EIP's like ERC777. See #1068 .
