### ISSUE TITLE
update deploy doc

### ISSUE THREAD

**Issue by benjyz** [ethereum/vyper#1414]
### Version Information

* vyper Version (output of `vyper --version`): 0.1.0b9
* OS: osx
* Python Version : 3.6.5
* Environment (output of `pip freeze`):

bitcoin==1.1.42
cytoolz==0.9.0.1
eth-hash==0.2.0
eth-typing==2.1.0
eth-utils==1.5.2
mypy-extensions==0.4.1
pbkdf2==1.3
py-ecc==1.6.0
pycryptodome==3.8.1
PyYAML==5.1
rlp==1.1.0
scrypt==0.8.13
toolz==0.9.0
vyper==0.1.0b9

### What's your issue about?

update 
https://github.com/ethereum/vyper/blob/master/docs/testing-deploying-contracts.rst

* compiler.Compiler() does not exist
* compiler.compile_code(src)
* 
```
Traceback (most recent call last):
  File "contract.py", line 28, in <module>
    contract = chain.contract(src, language="vyper", sender=None, value=1000)    
  File "/Users/ben/github/pyethereum/ethereum/tools/tester.py", line 240, in contract
    interface = compiler.mk_full_signature(sourcecode)
AttributeError: 'dict' object has no attribute 'mk_full_signature'
```

**Comment by iamdefinitelyahuman** [comment]
I think this issue has been solved or is no longer relevant, as the referenced RST file no longer exists and I cannot find mention of ``compiler.Compiler()`` or ``compiler.compile_code(src)`` elsewhere in the documentation.
