### ISSUE TITLE
Short-circuiting bool operations not working

### ISSUE THREAD

**Issue by robinsierra** [ethereum/vyper#1436]
### Version Information

* vyper Version: 0.1.0b9

### What's your issue about?

The documentation states that boolean operations use the common short-circuiting rules. However, the following contract fails at runtime even though the right-hand side of the `and` should not be evaluated at all:

```
i: int128

@public
def fail():
    b: bool = self.i != 0 and 1 / self.i == 1

```
A version with a constant instead crashes at compile time:

```
i: int128

@public
def fail():
    b: bool = True or 1 / 0 == 0
```
The same is true for other operations like underflows of `uint256`.

**Comment by jacqueswww** [comment]
@robinsierra this seems to be a documentation error.
Note: https://vyper.readthedocs.io/en/v0.1.0-beta.9/types.html?highlight=short#operators
