### ISSUE TITLE
[meta] Tracker for EIP 1679 (Istanbul)

### ISSUE THREAD

**Issue by charles-cooper** [ethereum/vyper#1439]
The following are accepted for Istanbul:
- Add Blake2 precompile [EIP-152](https://eips.ethereum.org/EIPS/eip-152)
  - Adds new hash function used in ZKPs
  - Easy feature to add (requires VIP)
- Reduce alt_bn128 precompile gas costs [EIP-1108](https://eips.ethereum.org/EIPS/eip-1108)
  - Reduces gas cost for `ecadd` and `ecmul` operations
  - No functional change
  - We don't bn128 pairing precompile (requires VIP)
- Chain ID Opcode [EIP-1344](https://eips.ethereum.org/EIPS/eip-1344)
  - Adds a way to obtain and/or check a chain ID value on the particular chain
  - Easy feature to add (requires VIP)
- Repricing for trie-size-dependent opcodes [EIP-1884](https://eips.ethereum.org/EIPS/eip-1884)
  - No functional change
  - Increases a bunch of gas costs
- Calldata gas cost reduction [EIP-2028](https://eips.ethereum.org/EIPS/eip-2028)
  - No functional change
  - Reduces gas cost
- Increase SSTORE gas cost [EIP-2200](https://eips.ethereum.org/EIPS/eip-2200)
  - No functional change
  - Increases gas cost

Special thanks to Mariano Conti's tweetstorm on Istanbul [here](https://twitter.com/nanexcool/status/1133808376339677184)

**Comment by fubuloubu** [comment]
Add VIP for `alt_bn128`
