### ISSUE TITLE
Rename compiler to vyperc

### ISSUE THREAD

**Issue by raypulver** [ethereum/vyper#1441]
Vyper is the language, vyperc should be the compiler. This seems more consistent with the naming of solc for Solidity which people are used to.

**Comment by d1ll0n** [comment]
Agreed, this repo is a compiler and the name should reflect that.

**Comment by fubuloubu** [comment]
As an alternative, what about `vyc`?

(Pronounced "vice")

**Comment by charles-cooper** [comment]
I think `vyc` is a cool name, but some might consider it too short? Perhaps twitter can resolve this for us :)

**Comment by fubuloubu** [comment]
https://twitter.com/fubuloubu/status/1130650190833229825

**Comment by davesque** [comment]
I dunno.

Currently, there's a nice alignment between the repo name on github, the packaged module name, the package name on pypi (which took lots of work to acquire), and the binary script.  I like this.  I haven't ever felt confused by this and I think there are plenty of examples of languages whose names are synonymous with their compiler/interpreter name.  Take Python and Nim, for example.

My vote is just to keep it the way it is and not commit time to an issue that seems low in priority.

**Comment by fubuloubu** [comment]
Meeting June 3rd: We decided not to do this at this time.

If you want an alternative, use an [alias](https://mijingo.com/blog/creating-bash-aliases)
