### ISSUE TITLE
Passing address to contract interface throws

### ISSUE THREAD

**Issue by ssteiger** [ethereum/vyper#1442]
### Version Information

vyper Version: 0.1.0b9
OS: osx

### What's your issue about?

Compiling the following code:

A:
```python
contract ERC1820Registry:
    def setInterfaceImplementer(
        _addr: address,
        _interfaceHash: bytes32,
        _implementer: address,
    ): modifying

erc1820Registry: ERC1820Registry

@public
def __init__():
    #self.erc1820Registry = 0x1820a4B7618BdE71Dce8cdc73aAB6C95905faD24
    self.erc1820Registry = ERC1820Registry(0x1820a4B7618BdE71Dce8cdc73aAB6C95905faD24)
    self.erc1820Registry.setInterfaceImplementer(self, keccak256('ERC777Token'), self)

```
Alternative:

B:
```python
erc1820Registry: ERC1820Registry
erc1820Registry_Address: constant(address) = 0x1820a4B7618BdE71Dce8cdc73aAB6C95905faD24

@public
def __init__():
    self.erc1820Registry = ERC1820Registry(self.erc1820Registry_Address)
    self.erc1820Registry.setInterfaceImplementer(self, keccak256('ERC777Token'), self)
```

Both throw:
```
[Compiler Error] vyper.exceptions.StructureException: line 109: Not a top-level function: ERC1820Registry self.erc1820Registry = ERC1820Registry(0x1820a4B7618BdE71Dce8cdc73aAB6C95905faD24)
```

### How can it be fixed?

Possibly related: https://github.com/ethereum/vyper/issues/1375

Relevant section in docs: https://vyper.readthedocs.io/en/v0.1.0-beta.9/structure-of-a-contract.html#external-calls-using-interfaces

**Comment by fubuloubu** [comment]
First example compiles fine for me with the latest release, second one you defined `erc1820Registry_Address` as a `constant`, which means you should use it via `self.erc1820Registry = ERC1820Registry(erc1820Registry_Address)`. You added `self.` to it, referencing it as a state variable.

**Comment by ssteiger** [comment]
I reinstalled vyper and now (A) is working.
Thank you for helping! :-)
