### ISSUE TITLE
Update 'make' file to use pip3

### ISSUE THREAD

**Issue by ssteiger** [ethereum/vyper#1443]
When installing the latest version of vyper on mac using `make`
I get the following error:

```
File "/usr/local/bin/vyper", line 133
    f'Imported interface "{interface_path}{{.vy,.json}}" does not exist.'
                                                                        ^
SyntaxError: invalid syntax
```

what fixed it was changing the `make` file of vyper:
`pip` -> `pip3`

The docs say that `Vyper can only be built using Python 3.6 and higher.`

Should the make file be updated?

**Comment by jacqueswww** [comment]
@ssteiger hmmm I am not sure if pip3 is generixc accross all distros ?

**Comment by fubuloubu** [comment]
Perhaps the Makefile can check if `pip` or `pip3` should be what's called?

**Comment by ssteiger** [comment]
jup, its working now
