### ISSUE TITLE
Plugin for intelij-platform

### ISSUE THREAD

**Issue by NikitaMishin** [ethereum/vyper#1444]
## Simple Summary
Hello, we've been developing IntelliJ Platform plugin to support Vyper for a while. For now the plugin includes language grammar with deduced parser, basic syntax and error highlighting, some auto completion and navigation. Also the plugin integrates some development and testing tools: Vyper compiler, Vyper-run, SmartCheck static analyzer, MythX bytecode analyzer.
You can check it out [here](https://github.com/NikitaMishin/vyper-plugin)

## Abstract
Vyper plugin for IntelliJ Platform.

## Motivation
We have briefly checked out existing support for Vyper in some editors and IDE's and it seems they all are based on Python grammar. We provide an approach to specify Vyper grammar and integrate development tools. Still much is to be done though. 

It would be great if you mention us on Vyper plugins page since it could attract some developers to contribute :)

**Comment by NikitaMishin** [comment]
We made a [demo](https://www.youtube.com/watch?v=M6f6xgcP4Xo&feature=youtu.be ), by the way

**Comment by fubuloubu** [comment]
Nice! That's looking great!

**Comment by fubuloubu** [comment]
Added here: https://github.com/ethereum/vyper/wiki/Vyper-tools-and-resources#syntax--ide-integration

**Comment by jacqueswww** [comment]
@NikitaMishin this is looking great! :)

**Comment by NikitaMishin** [comment]
@jacqueswww ,
Hello,
Each third-grade student in our university must complete coursework within two semesters i.e they should choose till winter a theme of work and start working on a project. We would like to present to students some themes associated with your project (Vyper), also we have some ideas about our current work related to Vyper (vyper Intellij plugin). Within the plugin, we would like to add some features especially to automatic testing smart contact inside docker containers and maybe some more infrastructure. So, do you have some ideas and do you interesting in communication?

Kind regards,
Nikita Mishin.

**Comment by NikitaMishin** [comment]
@fubuloubu

**Comment by fubuloubu** [comment]
Not really sure any of the maintainers of this open source project has the bandwidth to instruct students on contributing to this repository, but we certainly welcome any contributions the students make. Check out https://github.com/ethereum/vyper/projects/6 for a list of things we are currently working on implementing.
