### ISSUE TITLE
Document `@version` syntax

### ISSUE THREAD

**Issue by charles-cooper** [ethereum/vyper#1449]
You can set a version pragma but it's undocumented. See test cases below for usage:
https://github.com/ethereum/vyper/blob/cdfb36d0c6d4a38ee3d9d34e001b141ec7c6f55f/tests/compiler/test_pre_parser.py#L74-L105

**Comment by charles-cooper** [comment]
here's an example:
```python
# foo.vy
#@version0.1.13b

@public
def foo():
  pass
```

the version validator checks the major and minor version (but not the patch).

**Comment by fubuloubu** [comment]
There can be a space between `version` and the version number, right?
