### ISSUE TITLE
Update to latest web3

### ISSUE THREAD

**Issue by charles-cooper** [ethereum/vyper#1461]
Apparently, it's not as easy as https://github.com/ethereum/vyper/pull/1460/commits/6703a0cb69d0c909762cce6f60275ce96b5a3ef6. Luckily, most of the changes look mechanical.

**Comment by jacqueswww** [comment]
@charles-cooper https://github.com/ethereum/vyper/pull/1459 already bumps it :)

**Comment by charles-cooper** [comment]
Neat!
