### ISSUE TITLE
Vyper treats strings as having length 32

### ISSUE THREAD

**Issue by robinsierra** [ethereum/vyper#1462]
### Version Information

* vyper Version: 0.1.0b9
* OS: osx

### What's your issue about?

When using `concat` Vyper treats all strings as having length 32. Therefore this
```
@public
def conc(a: string[33], b: string[33]) -> string[64]:
   c: string[64] = concat(a, b)
   return c
  ```
will compile and even run (returning a string of length 66) and the following
```
@public
def conc_fail(a: string[5], b: string[4]) -> string[9]:
    c: string[9] = concat(a, b)
    return c
```
leads to a compiler error "Cannot cast from greater max-length 64 to shorter max-length 9".

**Comment by fubuloubu** [comment]
That's wild, good find.
