### ISSUE TITLE
Default parameters do not get properly typechecked

### ISSUE THREAD

**Issue by charles-cooper** [ethereum/vyper#1469]
### Version Information

* vyper Version (output of `vyper --version`): f6cf2da3d542bf5a325ed28b7047a1ac25bb7a3a
* OS: linux
* Python Version (output of `python --version`): `Python 3.6.7`

### What's your issue about?
The following function passes the type checker.
```python
@public 
def foo(x: uint256 = -1):
    pass
```

### How can it be fixed?
Use the type checker on default function parameters

**Comment by jacqueswww** [comment]
Yup, also picked this up checking #1466 ;)
