### ISSUE TITLE
Incorrect version published as latest in Docker Hub

### ISSUE THREAD

**Issue by alcuadrado** [ethereum/vyper#1472]
### Version Information

* vyper Version (output of `vyper --version`): 0.1.0b9
* OS: MacOS 10.14.5 in the host
* Docker version: 2.0.0.3

### What's your issue about?

Pulling the `latest` tag from Docker Hub gets you 0.1.0b9, it should be 0.1.0b10

Please include information like:

Pulled it with `docker pull ethereum/vyper`, got the version with `docker run -v $(pwd):/code ethereum/vyper  --version`.

### How can it be fixed?

Beta 10 is already published, so I think the fix should be just pointing `latest` to it.

Thanks!

**Comment by jacqueswww** [comment]
@alcuadrado the b10 tag (https://hub.docker.com/r/ethereum/vyper/tags) is there if you'd like to try. I will push over latest as well ;)

**Comment by alcuadrado** [comment]
Thanks for your answer, @jacqueswww ! I'm using `0.1.0b10` now :)

**Comment by jacqueswww** [comment]
Cool, I have updated dockerhub latest as well.
```
docker run -v $(pwd):/code ethereum/vyper --version
0.1.0b10
```
