### ISSUE TITLE
Meeting 17th June

### ISSUE THREAD

**Issue by jacqueswww** [ethereum/vyper#1477]
Start: Monday 17th June 2019, 15:00 UTC (https://time.is/UTC)

~Jitsi: https://meet.jit.si/IndifferentSquidAdaptRegularly~
https://zoom.us/j/219889477

Agenda
- Webassembly / Yul to Webassembly update
- Array indexes as int128
- `assert transferFrom()` is a thing, maybe amend VIP #1150 https://github.com/ethereum/vyper/issues/1468 ?

**Comment by fubuloubu** [comment]
Yeah, Jitsi sucks lol

**Comment by charles-cooper** [comment]
Array indexes as int128

**Comment by fubuloubu** [comment]
Proposal: create new VIP from [conversation](https://github.com/ethereum/vyper/issues/1468#issuecomment-502225637) in #1468 to ensure all state-modifying external calls with returns are handled appropriately, without question.

**Comment by jacqueswww** [comment]
Meeting Notes:
On `assert transferFrom()` the best resolution  we came to:
- Is adding a special return assert statement `assert_modifiable()`.
- Separate VIP for enforcing to always handle return values via asserts and or assigning variables.

**Comment by charles-cooper** [comment]
evaluate some sort of tail-call restriction. external calls can only be the last instruction in a function, or maybe no state changes are allowed after a call.

**Comment by davesque** [comment]
@jacqueswww @charles-cooper What ended up being discussed about YUL and WASM?

**Comment by fubuloubu** [comment]
Next: #1509
