### ISSUE TITLE
bug: no clamping for negative array indices

### ISSUE THREAD

**Issue by charles-cooper** [ethereum/vyper#1483]
### Version Information

* vyper Version (output of `vyper --version`): beta-10

### What's your issue about?

no out-of-bounds check for negative array indices
```python
xs: uint256[10]

@public
def bar() -> uint256:
    return self.xs[-1]
```
generates this:
```python
          [eq, [mload, 0], '4273672062' <bar()>],
          [seq,
            [assert, [iszero, callvalue]],
            # Line 5
            [mstore, 0, [sload, [add, [sha3_32, '0' <self.xs>], [uclamplt, -1, 10]]]],
```

### How can it be fixed?

If array index is `int128`, add `uclampge 0` for the index

**Comment by charles-cooper** [comment]
Maybe the `uclamplt` implicitly works because a negative int128 interpreted as uint256 is a really big number.

**Comment by jacqueswww** [comment]
Yup! Pretty cool.
