### ISSUE TITLE
VIP: Structured errors format

### ISSUE THREAD

**Issue by alcuadrado** [ethereum/vyper#1492]
## Simple Summary

Vyper should output errors and warnings in a machine-consumable format.

## Abstract

Integrating Vyper into different toolchains is not ideal. When the compilation fails the only reasonable option is to show the entire compiler's stderr. It's not clear when/how to show warnings.

## Motivation

I'm integrating Vyper into [Buidler](https://buidler.dev) and couldn't find a way to print compilation errors in a nice way. I'm just printing the entire content of stderr now, but not happy with the result. Parsing stderr is not an option.

On the contrary, `solc` has a json-based interface with a documented format for errors and warnings.

## Specification

**TODO:** I'm not familiar with the codebase, so I can't come up with a spec.

## Backwards Compatibility

This could be available behind a flag, so it would be backward compatible.

## Dependencies

**TODO:** I'm not familiar with the rest of the VIPs.

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/)

**Comment by fubuloubu** [comment]
So, Vyper already makes this available through the Python API for the compiler, perhaps the solution here is to write a script with your own custom handler so you can format it to whatever Buidler requires.

See [here](https://github.com/ethereum/vyper/blob/0cf2a29faea603fa38488da421892326414cd24e/bin/vyper#L136) for an example of how that's done.

---

As an alternative, we could perhaps write a `vyper-json` script that gives direct access to the underlying Vyper API through JSON object structured to match the API. But, many integrations with existing tools require integration anyways, and using the Python API directly is way more expressive than making a JSON one available.

**Comment by alcuadrado** [comment]
> So, Vyper already makes this available through the Python API for the compiler, perhaps the solution here is to write a script with your own custom handler so you can format it to whatever Buidler requires.
> 
> See [here](https://github.com/ethereum/vyper/blob/0cf2a29faea603fa38488da421892326414cd24e/bin/vyper#L136) for an example of how that's done.

I agree that this is a much better option if you are working with Python. If you are not, you should implement something similar than what I propose here, or the `vyper-json` script you mentioned.

> As an alternative, we could perhaps write a `vyper-json` script that gives direct access to the underlying Vyper API through JSON object structured to match the API.

This is a great alternative! If you can include it in the official Docker images this would solve all my problems.

**Comment by fubuloubu** [comment]
@alcuadrado can you create another VIP that walks through adding the `vyper-json` binary with the json input-output format that would work (and be similar to how it's used with Solidity), including exposing compilation errors over that API so the compiler doesn't crash when it's streaming over multiple file inputs.

Then close this one as I think currently this works okay (for non-json use cases)

**Comment by jacqueswww** [comment]
Approved for implementing a `vyper-json` command that will always output json.

**Comment by alcuadrado** [comment]
Thanks for your answers and to consider this idea.

@fubuloubu I'll make a new VIP later this week, or during the weekend.

**Comment by alcuadrado** [comment]
Closing this issue. I created https://github.com/ethereum/vyper/issues/1520
