### ISSUE TITLE
Interface implementation not enforced

### ISSUE THREAD

**Issue by sbrichards** [ethereum/vyper#1496]
### Version Information

* vyper Version (output of `vyper --version`): 0.1.0b10
* OS: macOS Mojave 10.14.4
* Python Version (output of `python --version`): 3.7.3
* Environment (output of `pip freeze`):
pycryptodome==3.8.2
vyper==0.1.0b10

### What's your issue about?

I have a simple contract, counter.vy:
```
import counter_interface as CounterInterface

implements: CounterInterface

count: public(int128)

@public
def __init__():
    self.count = 100

@public
def increment():
    self.count += 1

@public
def decrement():
    self.count -= 1
```

And the imported interface, counter_interface.vy:
```
contract CounterInterface():
  def increment(): modifying
  def decrement(): modifying
```
When I run `$ vyper counter.vy`, it compiles as expected BUT even if I delete one of the methods, e.g. `increment()`, it still compiles.

I expected to receive something along the lines of:
```
Error compiling:  counter.vy
vyper.exceptions.StructureException: Contract does not comply to supplied Interface(s).
Missing interface functions:
	def increment(): modifying:
```

### How can it be fixed?

Fill this in if you know how to fix it.

**Comment by jacqueswww** [comment]
@sbrichards the above syntax isn't currently supported use this instead:
```
def increment(): modifying
def decrement(): modifying
```

**Comment by sbrichards** [comment]
@jacqueswww thanks for the reply. 

I tried that edit you suggested, then got this error when compiling:
```
$ vyper counter.vy
Error compiling:  counter.vy
vyper.exceptions.StructureException: line 1: Function visibility must be declared (@public or @private)
def increment() -> int128: modifying
```

So then I edited counter_interface.vy to:
```
@public
def increment() -> int128: modifying
@public
def decrement() -> int128: modifying
```
This now compiles successfully when running `vyper counter.vy`!

Unfortunately, I now hit a snag when compiling with truffle:
```
$ truffle compile

Compiling your contracts...
===========================
> Compiling ./contracts/counter.vy
> Compiling ./contracts/counter_interface.vy
> Compiling ./contracts/counter.vy
> Compiling ./contracts/counter_interface.vy
vyper.exceptions.StructureException: line 1: Missing or Unmatched return statements in function "increment". All control flow statements (like if) need balanced return statements.
@public

Compilation of /Users/samrichards/code/tu/vyper-sandbox/contracts/counter_interface.vy failed. See above.
Truffle v5.0.21 (core: 5.0.21)
Node v10.13.0
```
Looks like truffle is trying to compile the interface file independently. E.g. this raises the same error:
```
$ vyper counter_interface.vy
Error compiling:  counter_interface.vy
vyper.exceptions.StructureException: line 1: Missing or Unmatched return statements in function "increment". All control flow statements (like if) need balanced return statements.
@public
```
Any idea how to get around this? Should interface files be able to compile? Let me know if this is out of the scope of this issue. Thanks!

**Comment by jacqueswww** [comment]
@sbrichards I am not exactly sure how truffle execute the compilation, but my guess from your output is it's trying to compile an interface - could you remove that from the config file. Or just move interfaces into it's own directory such as `interfaces` which truffle does not try to auto-compile.

**Comment by sbrichards** [comment]
@jacqueswww thanks for the reply. Closing this out.
