### ISSUE TITLE
Transfer and Approval events in vyper/interfaces/ERC20.py do not have the 'indexed' keyword on their two first parameters

### ISSUE THREAD

**Issue by rajeevgopalakrishna** [ethereum/vyper#1502]
### Version Information

* vyper Version (output of `vyper --version`): `0.1.0b10`
* OS: `osx`
* Python Version (output of `python --version`): `Python 3.6.5`
* Environment (output of `pip freeze`): `pycryptodome==3.8.2 vyper==0.1.0b10`

### What's your issue about?

In `vyper/interfaces/ERC20.py`, Transfer and Approval events do not have the 'indexed' keyword on their two first parameters, as defined by the ERC20 specification.

```                                                                                                        
# Events                                                                                                                       
Transfer: event({_from: address, _to: address, _value: uint256})                                                               
Approval: event({_owner: address, _spender: address, _value: uint256})  
```

### How can it be fixed?
Change to:  
```
Transfer: event({_from: indexed(address), _to: indexed(address), _value: uint256})
Approval: event({_owner: indexed(address), _spender: indexed(address), _value: uint256})
```

**Comment by Amit-Weiss** [comment]
I have changed the relevant file using the solution suggested here. You can check PR https://github.com/ethereum/vyper/pull/1536
