### ISSUE TITLE
Meeting 1st July

### ISSUE THREAD

**Issue by davesque** [ethereum/vyper#1509]
Start: Monday 1st July 2019, 15:00 UTC (https://time.is/UTC)

Zoom: https://zoom.us/j/134854019
Agenda:
- https://github.com/ethereum/vyper/issues/1492
- YuL (round 2)
- https://github.com/ethereum/vyper/issues/1493

**Comment by davesque** [comment]
Went ahead and made an issue ticket for this.  Not sure what the agenda will be.  Feel free to edit and add.

**Comment by fubuloubu** [comment]
Next: #1518
