### ISSUE TITLE
[Question] is it possible to declare dynamic type array?

### ISSUE THREAD

**Issue by or2008** [ethereum/vyper#1510]
is there a way to use a fixed size array of unknown types, something like:

x = ["some string", 1, '0x912fD21d7a69678227fE6d08C64222Db41477bA0']

**Comment by jacqueswww** [comment]
Mixed type arrays are not supported in vyper, this was chosen because mixed list types could lead to confusion.

**Comment by or2008** [comment]
Ok, thank you very much
