### ISSUE TITLE
VIP: Allow environment variables and constants as "default value" in public functions

### ISSUE THREAD

**Issue by haydenadams** [ethereum/vyper#1525]
There are a number of Uniswap functions that have a recipient field. It would be great to default this field to msg.sender like so:

```python
@public
@payable
def ethToTokenSwap(minTokens: uint256, recipient: address = msg.sender):
```

Currently I have to do something along these lines:
```python
@public
@payable
def ethToTokenSwap(minTokens: uint256, recipient: address = 0x000...000):
   if(recipient == ZERO_ADDRESS):
      recipient = msg.sender
```

which isn't the worst but it would be great to have msg.sender, msg.value, and constants available here.

**Comment by jakerockland** [comment]
I'm a fan of this idea 👍

**Comment by fubuloubu** [comment]
So, allow constants and environment variables? I'm on board with that too
