### ISSUE TITLE
'installing vyper' page doesn't specify how to install on windows

### ISSUE THREAD

**Issue by Amit-Weiss** [ethereum/vyper#1531]
### Version Information

* vyper Version (output of `vyper --version`):  Not applicable - trying to download the latest
* OS: Windows 10 (Home edition, therefore using Docker is not possible)
* Python Version (output of `python --version`): 3.6

### What's your issue about?

The installation guide specifies numerous ways to install Vyper on different systems, including Mac OS and Ubuntu, but doesn't say anything about Windows. The option to use Docker is problematic, since (as far as I know) Docker cannot be installed on Windows 10 Home (only on Windows 10 Pro).  

### How can it be fixed?

If it possible to install Vyper on Windows 10 without Docker, a quick update of the documentation can fix this issue.

**Comment by fubuloubu** [comment]
You might be able to use the "Windows Subsystem for Linux" (info [here](https://docs.microsoft.com/en-us/windows/wsl/install-win10)) to install Ubuntu 18.04 LTS and use the Linux install instructions (or snapcraft/docker).

**Comment by Amit-Weiss** [comment]
Thanks @fubuloubu !
I will give that a try. In the meantime, I seem to have some success with Docker Toolbox.
However, I still think the 'installing Vyper' page could use an update to specify the different options you have with Windows.

**Comment by fubuloubu** [comment]
Well, we would definitely appreciate it if you could jot down some of what you've learned about it for us! It would really help us out 😎

**Comment by Amit-Weiss** [comment]
I added the relevant information in a pull request: https://github.com/ethereum/vyper/pull/1534
