### ISSUE TITLE
@nonreentrant should not compile on constant functions

### ISSUE THREAD

**Issue by haydenadams** [ethereum/vyper#1544]
Right now this compiles:

```python
@public
@constant
@nonreentrant('lock')
def tokenAddress() -> address:
    return self.token
```

however reentrancy should never be a problem in constant functions

**Comment by jacqueswww** [comment]
agreed, this should be a compiler error.

**Comment by davesque** [comment]
I'm currently looking into this.  Will try to have a PR in next day or so.

**Comment by davesque** [comment]
Actually, this is a pretty easy fix.  PR incoming.
