### ISSUE TITLE
[question] best practice to calculate a ratio in Vyper?

### ISSUE THREAD

**Issue by or2008** [ethereum/vyper#1573]
I am looking for a good way to calculate ratio in Vyper, I have 2 params that each represents balance, and I would like to calculate the ratio between them, and check if the ratio is above or below 50%

This is something I wrote, but I really do not know if it safe or even works:
please let me what do you think

```
@public
def calculateRatio(token_exchange_addr: address, token_addr: address) -> bool:
    eth_reserve: uint256(wei) = token_exchange_addr.balance
    token_reserve: uint256 = ERC20(token_addr).balanceOf(token_exchange_addr)

    ratio: decimal = convert(as_unitless_number(eth_reserve), decimal) / convert(token_reserve, decimal)

    if ratio < 0.50: return true

    return false
```

**Comment by robinsierra** [comment]
Checking whether the ratio `x / y < 0.5` is the same as checking whether `2 * x < y`, which doesn't need any type conversions.

**Comment by fubuloubu** [comment]
For this kind of simple example, the most optimal would be to do what @robinsierra says.

If you have a more complex relationship you wish to track, it may be more readable to track it via a decimal state variable as a ratio, but probably it would not be more efficient.

Also, you can change it to this (adding @robinsierra's suggestion):
```python
@public
def calculateRatio(token_exchange_addr: address, token_addr: address) -> bool:
    eth_reserve: uint256(wei) = token_exchange_addr.balance
    token_reserve: uint256 = ERC20(token_addr).balanceOf(token_exchange_addr)
    # Returns true if the amount of ether reserves is over 50% the amount of token reserves
    return 2 * eth_reserve < token_reserve
```

**Comment by or2008** [comment]
Thanks guys, the code you provided is really clean, I will definitely use it.

but lets say I want to test more complex ratio, for example 88% (or 0.88), is the type conversion I used is the correct way?

```
ratio: decimal = convert(as_unitless_number(eth_reserve), decimal) / convert(token_reserve, decimal)
```

**Comment by fubuloubu** [comment]
For checking the ratio `a / b < r` (where `r := r_n / r_d` and `r_n`/`r_d` are whole numbers), you could do `r_d * a < r_n * b`. For your example, it would be `100 * a < 88 * b`, or (reducing) `25 * a < 22 * b` (which is equivalent)

**Comment by fubuloubu** [comment]
If, however, you wanted to parameterize `r`, it would probably be prudent to switch to `decimal` in that case

**Comment by or2008** [comment]
@fubuloubu oh that's a great idea, Thank you very much!
