### ISSUE TITLE
Use entry_points instead of scripts

### ISSUE THREAD

**Issue by iamdefinitelyahuman** [ethereum/vyper#1574]
## Simple Summary
Vyper's compiler scripts should be installed via `entry_points` and made available as `vyper.cli`

## Abstract
Using `entry_points` instead of `scripts` removes the need for `if __name__ == "main":` within Vyper's command-line scripts.  Placing the functionality within a `main()` method simplifies writing unit tests. Migrating the scripts to `vyper/cli` allows them to be imported and accessed by other packages.

`entry_points` also provides [better cross-platform compatibility](https://setuptools.readthedocs.io/en/latest/setuptools.html#automatic-script-creation), and it's use is recommended over `scripts` within the [PyPA docs](https://python-packaging-user-guide.readthedocs.io/guides/distributing-packages-using-setuptools/#scripts).

## Motivation
* I need to write unit tests for #1570 
* 3rd party tooling written in python should be able to access the full range of the compiler's functionality without relying on a subprocess call to reach `bin/vyper`

## Specification
* modify `setup.py`
* replace `if __name__ == "main":` with `def main():` in all `bin` scripts
* move the `bin` folder to `vyper/cli`, add `.py` suffix to files

## Backwards Compatibility
Should not cause any issues as scripts will still be invoked via the same commands, and the `bin` folder was not previously available to import as a package.

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/)

**Comment by jacqueswww** [comment]
Yeah this doesn't really even need a VIP IMHO. https://github.com/ethereum/vyper/pull/1337 was also implement this if I recall correctly.

**Comment by jacqueswww** [comment]
Removed VIP, and yes - just do it :)
