### ISSUE TITLE
TXs locked in a smart contract on Multisend.co

### ISSUE THREAD

**Issue by iscry** [ethereum/vyper#1589]
Tried to use Multisend.co, which is built with Vyper, earlier today, but the TXs didn’t get to the destinations

https://etherscan.io/tx/0x0b3d1e716573ccdcfd2ba0151261d4be13a3acc0afc05ce4f0ece4510692e7c3

There were 3 TXs and all 3 seem to be locked.

Does anyone know when the TXs will get through?

Many thanks!

**Comment by fubuloubu** [comment]
Seemed to work just fine? Perhaps you might be better of working with the developers of multisend and asking them what the issue is

**Comment by charles-cooper** [comment]
Hi, according to etherscan the transfers went through. However, we don't have any particular insight into the workings of multisend.co and recommend you reach out to the author. Best of luck.

**Comment by iscry** [comment]
Great, thank you! All works! Sorry for offtoping :)

**Comment by fubuloubu** [comment]
No worries! It's sometimes hard to know where to post questions

**Comment by iscry** [comment]
It wasn't hard to answer, right?
