### ISSUE TITLE
Access to _placeholder_# generated variables can cause problems

### ISSUE THREAD

**Issue by smarx** [ethereum/vyper#1600]
### Version Information

* vyper Version (output of `vyper --version`): 0.1.0b12+commit.ab39d4e

### What's your issue about?

The compiler uses `_placeholder_1`, `_placeholder_2`, etc. variables. Users are able to read from and write to those variables, which can cause significant problems.

Below is the most dramatic example I came up with. Here, the callback pointer is overwritten, causing execution to jump to the wrong place. Both `getNumber()` and `getDoubleNumber()` return `42`. (If you comment out the assignment to `_placeholder_1`, `getDoubleNumber()` returns `84` as expected:

```python
@private
@constant
def meaningOfLife() -> uint256:
    _placeholder_1 = 215
    return 42
    
@public
@constant
def getNumber() -> uint256:
    return self.meaningOfLife()
    
@public
@constant
def getDoubleNumber() -> uint256:
    return self.meaningOfLife() * 2
```

(Note that `215` is specifically the location for the right `JUMPDEST`. If you use a different compiler version, that location might change, so you're likely to see a revert instead.)

### How can it be fixed?

The most obvious fix is probably to disallow users referencing variables that start with `_placeholder_`. They shouldn't be able to declare them or access them.  When fixing this, note that there may be other special variable names that need to be protected in the same way.

A better alternative might be to avoid collisions altogether. It's not clear to me why placeholder variables need names at all, or why those names have to exist in the same namespace as user-defined variables. I simply don't know the compiler code well enough to suggest a better fix, but I'm hoping there can be something more robust than naming conventions.

**Comment by charles-cooper** [comment]
@smarx thanks for the report. My idea is to block the user from accessing these variables at the parser level, as in https://github.com/ethereum/vyper/pull/1601/commits/5bb8bce2619631f217f04fe53535e6040a23f6df. Can you take a look and see if you think that will satisfactorily solve this issue?

**Comment by smarx** [comment]
That seems like a clever solution, and I mean that in both a positive and a negative way. :-)

I can't think of any reason why that wouldn't work.
