### ISSUE TITLE
Cannot ignore return values of functions called inside a for loop

### ISSUE THREAD

**Issue by iamdefinitelyahuman** [ethereum/vyper#1620]
### Version Information

* vyper Version: `0.1.0b12+commit.0a386af`
* OS: linux
* Python Version: `3.6.8`
* Environment: clean venv with only vyper and required dependencies

### What's your issue about?
The following code example fails to compile with `CompilerPanic: Third argument to repeat (clause to be repeated) must be zerovalent`
```python
@private
def _bar() -> bool:
    return True

@private
def foo() -> bool:
    for i in range(3):
        self._bar()
    return True
```
* Assigning the return value of `self._bar` to a memory variable allows the contract to compile
* Not assigning the return value from `self._bar` is possible outside of the for loop

**Comment by charles-cooper** [comment]
Related: https://github.com/ethereum/vyper/issues/1511

**Comment by fubuloubu** [comment]
@charles-cooper does #1665 resolve this?

**Comment by charles-cooper** [comment]
yes, it does. cf https://github.com/ethereum/vyper/blob/f8d9f84d7051a79b4bf2836ba3a7e02edcad6b73/tests/parser/features/iteration/test_repeater.py#L89-L103
