### ISSUE TITLE
Question: How to get a given variable's representation in EVM state?

### ISSUE THREAD

**Issue by Pet3ris** [ethereum/vyper#1629]
Vyper Team,

I'm wondering if there is a compiler output to get how a given variable is represented in EVM state?

Variables would be any variables in Vyper code from given contract storage variables (where we would just need to know the "keccak index" of each variable) or temporary variables created in the scope of a function which would have locations in memory.

Alternatively, if there is no way to get that output directly from the compiler or ABI, is there a canonical way to determine these across Vyper versions?

**Comment by fubuloubu** [comment]
Do you mean the symbol table?
https://www.geeksforgeeks.org/symbol-table-compiler/

**Comment by Pet3ris** [comment]
@fubuloubu - yes, that's exactly it!

Especially these elements.

Information used by compiler from Symbol table:

- Data type and name
- Declaring procedures
- Offset in storage
- If structure or record then, pointer to structure table.
- For parameters, whether parameter passing by value or by reference
- Number and type of arguments passed to function
- Base Address

**Comment by fubuloubu** [comment]
Should be able to obtain most of the information from the AST endpoint, but codegen would need to inform the offset info.

What do you mean by "Base Address"?

**Comment by Pet3ris** [comment]
I think base address refers to the starting address for an array, which effectively is same as "offset in storage".

Sounds great, I'll have a look through AST output. By codegen, do you mean a specific Python sub-module of Vyper/a functional component in the compiler or is it something packaged in the CLI?

**Comment by fubuloubu** [comment]
A functional component of the compiler, that stage that takes the AST and puts out the IR that we use (LLL)

**Comment by Pet3ris** [comment]
Gotcha :)
