### ISSUE TITLE
Vyper Wiki

### ISSUE THREAD

**Issue by markhotpyp** [ethereum/vyper#1634]
Sorry this issue is not about the compiler, but the wiki: https://github.com/ethereum/vyper/wiki/Vyper-tools-and-resources

Under **Syntax / IDE Integration** there is a link to a repo for **Sublime** that points to https://github.com/jacqueswww/sublime-vyper that has a file named Vyper.sublime-syntax that is a vyper contract and not a sublime package.

What's up with that?

**Comment by jacqueswww** [comment]
Moved issue to: https://github.com/jacqueswww/sublime-vyper/issues/2
Not sure how I did that, LOL
