### ISSUE TITLE
Install instructions are insufficient

### ISSUE THREAD

**Issue by fulldecent** [ethereum/vyper#1659]
Please update https://github.com/ethereum/vyper/blob/master/README.md

At current the instructions to run a test are:

```sh
python setup.py test
```

These instructions are insufficient to get a new-just-unboxed Mac to run the test suite (even if Xcode tools are installed).

**Comment by fubuloubu** [comment]
Did you have any issues with the [install instructions](https://vyper.readthedocs.io/en/latest/installing-vyper.html#macos)?

Also, what Python env are you using? I would recommend [pyenv](https://github.com/pyenv/pyenv#homebrew-on-macos) for managing you vyper environment.

**Comment by fulldecent** [comment]
Added this literal step at https://github.com/ethereum/vyper/pull/1660
