### ISSUE TITLE
Vyper ignores scientific notation in decimal literals

### ISSUE THREAD

**Issue by robinsierra** [ethereum/vyper#1680]
### Version Information

* vyper version: 0.1.0b13

### What's your issue about?

Vyper ignores scientific notation in decimal literals, e.g.,
```
@public
def foo() -> decimal:
    return 2e-8
```
and instead just returns the part before the `e` (in this case 2).

### How can it be fixed?

I don't think scientific notation is necessary for decimals, so probably just disallow this.

**Comment by fubuloubu** [comment]
Good catch!

**Comment by robinsierra** [comment]
Thanks. I was wondering how you manage to get the decimal digits from the scientific notation without getting rounding errors. Turns out, you don't. :)

**Comment by charles-cooper** [comment]
why do we have a custom parser in get_number_as_fraction. we should use the `decimal` library.

**Comment by fubuloubu** [comment]
@charles-cooper can you submit that suggestion as a new feature request?

**Comment by charles-cooper** [comment]
@fubuloubu why don't we just fix it now?

**Comment by fubuloubu** [comment]
Because it needs a whole new set of test cases

**Comment by charles-cooper** [comment]
@fubuloubu I'm not convinced about that, it should be a non-semantic change (just decreases probability of weird bugs like this).

**Comment by fubuloubu** [comment]
Non-semantic change, yes, but it's sort of a clever hack to enable a new class of syntax for decimal variables. Need to make sure than all the different combinations introduced does not create inconsistent and/or lossy behavior that will be difficult to debug.
