### ISSUE TITLE
Meeting 11th November 2019

### ISSUE THREAD

**Issue by fubuloubu** [ethereum/vyper#1683]
Start time: 15:00 UTC (https://time.is/UTC)

Vidchat link: https://meet.google.com/czc-kuep-jda
Jitsi backup: https://meet.jit.si/IndifferentSquidAdaptRegularly

Agenda:
- [x] #1677
- [x] Compiler Documentation (@kfichter)
- [x] Audit issues w/ "discussion" label
  - [x] #1709
  - [x] #1684
  - [x] #1693
  - [x] #1696
  - [x] #1697
  - [x] #1702
  - [x] #1711
- [x] #1669

**Comment by charles-cooper** [comment]
also https://github.com/ethereum/vyper/issues/1711

**Comment by fubuloubu** [comment]
Next: #1734
