### ISSUE TITLE
Code that ends in a comment (with no newline) cannot be compiled

### ISSUE THREAD

**Issue by smarx** [ethereum/vyper#1701]
This was previously [reported](https://github.com/ethereum/vyper/issues/1161) for Vyper, but it’s actually [a Python bug](https://bugs.python.org/issue35107):

```python
@public
def __init__():
   pass

# BUG (no newline)
```

**Comment by fubuloubu** [comment]
Can we... Just add an extra beeline before parsing with `ast.parse`?
