### ISSUE TITLE
Contributing?

### ISSUE THREAD

**Issue by kirkthaker** [ethereum/vyper#282]
I'd be interested in contributing to this project, but there's no roadmap or list of necessary future features (in order of importance) that I can find. If someone could upload that, it would be very helpful. Thanks.

**Comment by yograterol** [comment]
This project has some "future features" in the README

## Planned future features

- Declaring external contract ABIs, and calling to external contracts
- A mini-language for handling num256 and signed256 values and directly / unsafely using opcodes; will be useful for high-performance code segments
- Smart optimizations, including compile-time computation of arithmetic and clamps, intelligently computing realistic variable ranges, etc

I see some possible contributions:

- Better documentation.
- Tool like truffle with viper (maybe it is another project)
- More examples.

**Comment by vbuterin** [comment]
Documentation and examples are definitely highly welcome. Also more tests; one really useful specific task would be to find and integrate some testing framework that lets us check how much code coverage we have so we can try to get to 100%.

**Comment by DavidKnott** [comment]
@vbuterin @yograterol I'd love to build a Viper Read the Docs much like the [Solidity](https://solidity.readthedocs.io/en/latest/installing-solidity.html#building-from-source)  one.  Can I get started on that? (I strongly believe that good documentation will help Viper grow and become mainstream)

**Comment by Dexaran** [comment]
@vbuterin what do you mean by examples? Manuals/tutorials?
I can also write the ERC 223 implementation in Viper but the language doesn't support event yet as far as I know.

**Comment by yograterol** [comment]
@DavidKnott can you start in a branch and I can help you too, what do you think?

**Comment by DavidKnott** [comment]
@yograterol Sounds good to me, I'll create the skeleton and push it to a documentation branch later today!

**Comment by Sparke2** [comment]
I can translate any examples and Docs into russian language. Just let me know if you need a translator.

**Comment by yograterol** [comment]
I can translate to Spanish :D EN + ES + RU @DavidKnott keep in mind it for the tasks of documentation process plz.

**Comment by DavidKnott** [comment]
@yograterol @Sparke2 Thanks a lot!  I'm making an outline of documentation tasks right now and should have it done tonight.

**Comment by vbuterin** [comment]
> I can also write the ERC 223 implementation in Viper but the language doesn't support event yet as far as I know.

See `raw_log`. No event ABI yet though.

**Comment by jacqueswww** [comment]
Closing this, it's very old and the landscape has changed considerably since then. Anyone can just open new issue if there is still anything relevant here ;)
