### ISSUE TITLE
QUESTION: Is compiler written in Python also?

### ISSUE THREAD

**Issue by sgitt-vassky** [ethereum/vyper#290]
I'm wondering about is the compiler for Viper fully written in python? Is it using any external compiler for optimizations or is it a standalone compiler program?

**Comment by yograterol** [comment]
@sgitt-vassky 100% Python, you can check `viper/compile_lll.py`. Viper has not smart optimizations right now.

It is in the future planned features.

**Comment by Dexaran** [comment]
It will be better to write a frontend for LLVM for Viper syntax I think. This will allow to use LLVM to generate a high quality optimized bytecode. Personally I prefer GCC, but there is an LLVM backend for Ethereum VM as far as I know.

**Comment by Dexaran** [comment]
I suppose that it will be better to create a Viper frontend for eWasm when both Viper syntax and eWasm would be ready.

**Comment by yograterol** [comment]
@Dexaran it could be possible.
