### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by DavidKnott** [ethereum/vyper#291]
Documentation will help Viper become more widely adopted, here's a skeleton:
I've implemented the base in Sphinx in this [PR](https://github.com/ethereum/viper/pull/285)
**Introduction to Viper** --> Why Viper is necessary (strong type system, clearer code, easy accessibility and extensibility of the compiler code, etc)
**Installing Viper** --> Viper's still in the non-user friendly stage so it'd help to have directions that anyone can follow (`make` being the most basic etc)
**Viper by Example** --> I'd probably start with `Hello world` and an explanation of the syntax etc going into it and increase complexity from there
**Using the compiler** --> A step by step guide that shows someone how to turn their Viper code into byte code
**Contributing** --> It'd be great to get some guidelines in order to standardize and streamline contributions
@Dexaran  @yograterol  --> Obviously there's a lot more to be added but these seemed like good starting points

**Comment by DavidKnott** [comment]
I'm gonna get started on Viper by Example

**Comment by vbuterin** [comment]
Thanks!

Merged the PR as you currently have.

However, there is now duplication between the README.md in the main folder, and docs/index.rst, which creates headaches updating that section as well as adding a risk that the two will diverge leading to confusion.

Any ideas on how to best make sure the readme and the docs stay in sync? Perhaps the readme should be made smaller and more minimal, with links to specific sections in the docs?

**Comment by DavidKnott** [comment]
@vbuterin I'll make PR that changes the current README.md to be minimal and then link to the docs, (I'm using the [solidity](https://github.com/ethereum/solidity) repo for inspiration)

**Comment by mr-ubik** [comment]
@DavidKnott while I am rather new to Viper if you need any help on writing documentation/putting it on Read the Docs let me know.

**Comment by fubuloubu** [comment]
@DavidKnott is there a website or somewhere where the docs end up? I think that would be useful to include in the README

**Comment by DavidKnott** [comment]
@fubuloubu There is a website, in my next PR I'll change the readme to include it, thanks for reminding me.  That's the current site (locally I've added more and put in a theme but that's what's in master)
https://eth-viper.readthedocs.io/en/latest/

**Comment by DavidKnott** [comment]
@mr-ubik I'm going to make a pretty big docs PR (probably tomorrow), it'd be great to get your eyes on it because I've probably made some small errors here and there.

**Comment by yograterol** [comment]
@DavidKnott small pull requests are better, it's easier to review hahaha :+1: We wait for it

**Comment by JackieXu** [comment]
As a heads-up, I'm moving around some installation instruction from the README into the "Installing Viper" section of the docs.

Also adding some stuff to simplify the process.

**Comment by fubuloubu** [comment]
@JackieXu See #336. I did the README section, feel free to work on the actual docs portion of integrating that. Perhaps we should work on the same branch?

**Comment by JackieXu** [comment]
@fubuloubu Great work! I'm fine with working on the same branch, but I think that simply sending in pull requests is fine with everyone working on different segments of the documentation now. If not we can always switch over. 😄

**Comment by fubuloubu** [comment]
Cool, works for me.

If my PR is accepted, I moved the current README to a text file for reference while we sort out the docs. If you happen to finish, please delete it haha.

**Comment by DavidKnott** [comment]
Closing as the documentation tasks listed here are outdated
