### ISSUE TITLE
Improve and thoroughly test gas estimation

### ISSUE THREAD

**Issue by vbuterin** [ethereum/vyper#295]
Viper currently has a gas estimation feature (see https://github.com/ethereum/viper/blob/master/tests/test_parser.py#L30 ). However, the gas estimation in many places overshoots the actual gas consumption, it is still under-tested and there may well be areas where it under-estimates actual gas consumption. We need to reach a state where the gas estimator is 100% reliable, in the sense that it never undershoots, and overshooting is minimized, and _every_ function that is called in test_parser.py is also tested for gas estimation correctly.

I recommend creating a wrapper for `Chain.contract`, call it `ContractWithGasEstimation`, which has the property that (i) the constructor always assumes the language is viper, for simplicity, and (ii) when you call it, it checks the amount of gas spent and verifies that it is less than viper's gas estimate.

**Comment by jacqueswww** [comment]
@vbuterin @DavidKnott @fubuloubu I think we can be quite confident in the estimations at this stage, looking at the number of `get_contract_with_gas_estimation` calls in our tests (I grepped 417 matches) :smile:

**Comment by fubuloubu** [comment]
LGTM to close
