### ISSUE TITLE
EVM debugging tools

### ISSUE THREAD

**Issue by vbuterin** [ethereum/vyper#296]
It would be nice if we had functions:

* `get_function_contexts(viper_code)`: returns a map `{function_name: context}` where `context` is the Context object created when processing that function.
* `decode_memory(context, memory)`: converts the given memory (which would be passed in from an EVM debugger) into a map `{variable: value}` showing the current state of all variables.
* `pc_to_viper_code_position(pc, in_init_code=False)`: takes as input a program counter in EVM bytecode (could be contract code or init code) and outputs the corresponding position in Viper code.

A much further ideal would of course be some kind of crazy integration with pyethereum logging that gives a Viper-flavored log for a VM execution showing what all the variables are and the position in Viper code at any point.

**Comment by yograterol** [comment]
I am thinking about this, I want to add debugger to an online Viper compiler. I would check this idea.

**Comment by DavidKnott** [comment]
@vbuterin @yograterol I'm excited to do this, I'll get started on it!

**Comment by DavidKnott** [comment]
@yograterol Do have any ideas as to where I can get access to `memory` for `decode_memory`? (I was thinking through snapshot functionality)

**Comment by jacqueswww** [comment]
Closing, as https://github.com/status-im/vyper-debug allows you to break right into py-evm using `pdb` command :smile: Additionally vypder-debug in combination with the `debugger`  lll macro gives all the necessary information.
