### ISSUE TITLE
FEATURE: Identifier type

### ISSUE THREAD

**Issue by fubuloubu** [ethereum/vyper#324]
I propose an additional type `identifier` extending `sha3` (or some other acceptable hashing function with collision avoidance) to implement unique identifiers to be used in multi-party transaction logs (similar to how Firebase or other highly-scalable databases work). This would be useful for keeping track of quantities such as receipts, in-process/pending transactions, or other trackable quantities in a mapping as an alternative to a simple list, which has no collision avoidance and does not allow atomic operations on the data structure.

Usage as the key in a mapping data structure is much more natural than keeping track of items in a simple list (integer index), especially in context of #323 which would allow iteration without tracking indexes.

As an example, it might be used in the following context:
```python
bills: {from: address, amt: wei_value}[identifier]

...

def pay_bill(_id: identifier):
    assert self.bills[_id] is not None
    assert self.balance >= self.bills[_id].amt
    send(self.bills[_id].from, self.bills[_id].amt)
    del self.bills[_id] # effectively self.bills[_id] = None
```

**Comment by vbuterin** [comment]
How would the `identifier` be calculated?

**Comment by DavidKnott** [comment]
@fubuloubu Could you explain the advantages of using `identifier` as opposed to a list with integer indexing (it seems like the later is sufficient for avoiding collisions).   Also, as of now couldn't you use sha3 as the key in a mapping using the `uint256` data type?

**Comment by fubuloubu** [comment]
@vbuterin just a psuedorandomly generated hash using parameters available when adding new data to a map (maybe `sha3` of `block.timestamp`, `msg.sender`, and the data being inserted to ensure no collisions)
@DavidKnott I was thinking of the scenario when two people have added themselves to that integer indexed array around the same point in time, and then sent another transaction using that index before the block is fully confirmed. In this scenario, until the block is confirmed someone else could actually have that index instead thereby allowing undesirable behavior until that data is fully consistent. If the keys were psuedo-random, you would not have to wait until full consistency to operate on the data set. Large NoSQL databases that I have worked with use this to ensure consistency over latent distributed networks, which is why I saw it as a potentially useful concept to employ as a language primitive.

I was mostly thinking about this in context of being able to iterate over keys in a map e.g. #323, so I understand if this suggestion by itself has limited utility.

**Comment by jacqueswww** [comment]
@fubuloubu can we close, maybe merge it with #323 ?

**Comment by fubuloubu** [comment]
@jacqueswww

#323 describes implementing iterator functionality into mappings, I'm not sure if this is an effective use-case for the mapping type. An additional datatype overlaid on mappings may make sense here. Something like a linked list.

This issue describes an identifier type, which may be useful in general for mappings as a labeled datatype used to access values in mappings. The datatype would basically be the result of the keccak256 hash that is performed to obtain the key for the hashmap, and would be a unique data type that would allow database update like functionality in a distributed database like Ethereum. This might be some sort of concatenation of the msg.sender and block.number that gave a probalistically unique identifier when you don't necessarily need to construct the key yourself in the mappings. You would obtain one when you pushed something onto a mapping, and can use it to access the entry you pushed.

I'm not sure this really makes sense anymore, would suggest closing this issue.
