### ISSUE TITLE
OSX difficult install experience feedback

### ISSUE THREAD

**Issue by DustinWehr** [ethereum/vyper#326]
Followed instructions in readme.md. 
I can now compile examples/voting/ballot.v.py, which fortunately is all I need to do right now, but `python setup.py test` and `python3.6 setup.py test` both fail with python crashing and a console message similar to:
```
[1]    79735 illegal hardware instruction  python3.6 setup.py test
```
where the number part changes each time.

**Question** Does `python` need to point to `python3.6`? If so a note saying that would help some people like me.

I was able to get setup to succeed by first doing:
```
python3.6 -m pip install --user --upgrade Cython
```
Before that I was getting 
```
failed to import Cython: dlopen(/Library/Python/2.7/site-packages/Cython/Compiler/Scanning.so, 2): Symbol not found: _PyClass_Type
  Referenced from: /Library/Python/2.7/site-packages/Cython/Compiler/Scanning.so
  Expected in: flat namespace
 in /Library/Python/2.7/site-packages/Cython/Compiler/Scanning.so
error: Setup script exited with error: Cython does not appear to be installed
```
I added the extra arguments to `pip` following https://pip.pypa.io/en/stable/user_guide/#user-installs because `python3.6 -m pip install Cython` resulted in 
```
Requirement already satisfied: Cython in /Library/Python/2.7/site-packages
```

**Comment by DavidKnott** [comment]
@DustinWehr Thanks for the feedback!  You should be able to just use `python` as opposed to `python3.6` because the virtual environment you create should default to `python3.6`.  Can you give me the commands you ran to setup your virtual environment?

**Comment by DustinWehr** [comment]
I haven't managed to get setup to succeed in a virtual env, because I can't do 
```
python3.6 -m pip install --user --upgrade Cython
```
in the virtual env:
> Can not perform a '--user' install. User site-packages are not visible in this virtualenv.

Without the `--user` flag, I continue to get the error about Cython.

The command I used to setup the virtual env is the one from the linux instructions with different path:
```
virtualenv --python=python3.6 --no-site-packages viper
```

**Comment by DavidKnott** [comment]
I think I understand what's going on, I'll make a PR to improve the OSX installation instructions (making them more thorough).  Are you still having problems or did following the linux instructions get everything working?

**Comment by DustinWehr** [comment]
I just tried again following the instruction at https://eth-viper.readthedocs.io/en/latest/installing-viper.html **EXACTLY**. The first discrepancy comes when following the Note "For MacOS users" box:
>    (viper-venv) ➜  viper git:(master) pip install scrypt
>    Requirement already satisfied: scrypt in /Library/Python/2.7/site-packages

If I proceed:
>    (viper-venv) ➜  viper git:(master) python setup.py install

it runs for a bit, but ultimately fails with 
>    clang: error: no such file or directory: '“-I/usr/local/opt/openssl/include”'
>    clang: error: no such file or directory: '“-I/usr/local/opt/openssl/include”'
>        
>    No working compiler found, or bogus compiler options passed to
>    the compiler from Python's standard "distutils" module.  See
>    the error messages above.  Likely, the problem is not related
>    to CFFI but generic to the setup.py of any Python package that
>    tries to compile C code.  (Hints: on OS/X 10.8, for errors about
>    -mno-fused-madd see http://stackoverflow.com/questions/22313407/
>    Otherwise, see https://wiki.python.org/moin/CompLangPython or
>    the IRC channel #python on irc.freenode.net.)

This is all just so I can run the tests prior to submitting a PR with https://gist.github.com/DustinWehr/98c9310afab793588aa8e031f1d79aec
in order to close https://github.com/ethereum/viper/issues/370
So maybe someone could just do that for me @DavidKnott @fubuloubu

**Comment by fubuloubu** [comment]
I'm too cheap to have a Mac, never used one lol. But to me it seems like the virtualenv isn't working properly if it's getting requirements from Python2.7 since there's a Python3.5 package available in pypi it should prefer. I'm still no expert at virtual environments, I've made a few mistakes like this. For viper on my Ubuntu Linux 16.04 install I've had to roll my own python3.6 as described in the installation doc, and the only extra thing I do is create a symbolic link to python3.6 in the folder where all the python symbolic links live. You should get no references to any system libraries, or Python2.7 at all if the virtual env is installed correctly. Maybe the OSX virtualenv experience has some extra weirdness to it?

You did remember to source the activation script, right?

**Comment by DustinWehr** [comment]
@DavidKnott the OSX instruction says `make install` but the Makefile appears to require (I don't know make) `make init`.

**Comment by DavidKnott** [comment]
The easiest way to do it, is by typing make `make`

**Comment by DavidKnott** [comment]
Just made a pr for it.

**Comment by DustinWehr** [comment]
@DavidKnott Docker worked! Consider making that the first recommended method for Mac. Now I will test the new ballot.v.py code

**Comment by DavidKnott** [comment]
@DustinWehr I'm so glad it works for you!

**Comment by DavidKnott** [comment]
Closing, as the installation instructions have improved since this issue was created.
