### ISSUE TITLE
Cross-Type computations

### ISSUE THREAD

**Issue by fubuloubu** [ethereum/vyper#357]
### What's your issue about?
There are certain types that should be allow to compute cross-type computations. Some are implemented, but others have been skipped (creating a compiler error). Consider the right implicit type conversions for these datatypes such that data loss is not an issue (e.g. `div num num` has the potential to lose decimal point information if arg1 is not evenly divisible by arg2). Data loss either needs to be removed, or explcitly stated in the documentation of the behavior different types.

### How can it be fixed?

Add it

#### Cute Animal Picture

![PIG](https://static.boredpanda.com/blog/wp-content/uuuploads/cute-baby-animals/cute-baby-animals-10.jpg)

**Comment by jacqueswww** [comment]
@fubuloubu I think we have this handled now that we have strict conversion requirements?

**Comment by fubuloubu** [comment]
:+1:
