### ISSUE TITLE
FEATURE: Strings implementation

### ISSUE THREAD

**Issue by fubuloubu** [ethereum/vyper#358]
### What's your issue about?
I know Viper has strings (current syntax is `str: bytes <= N` and a literal is `b"My String"`) but I wanted to have a discussion about strings and how we think it should work and look so that it is as straightforward as possible.

Additionally there's only a few string primitive functions, so let's discuss if more are needed.

#### Cute Animal Picture
![pugly](https://az616578.vo.msecnd.net/files/responsive/embedded/any/desktop/2016/11/13/636146656314045851563022463_adorable-animals-in-ads.jpg)

**Comment by fubuloubu** [comment]
First off, I want there not to be a need to prepend a literal string with a b e.g. `b"My String"`. It;s annoying lol

**Comment by fubuloubu** [comment]
An offshoot of the maximum size, I had this idea where gas estimate could be linear instead of constant e.g. `gas = 54867 + 20*size(self.str) + ...` basically summarizing the gas cost for the size of any variable-sized globals in use inside it. This extend to arrays very easily. Probably much more complex to implement, but the resulting code can be much more reader/writer friendly (we can implement much more straightforward looping constructs maintaining the gas estimate guarentee).

**Comment by DavidKnott** [comment]
@fubuloubu Some functionality that needs to be added is the ability to make an array of byte arrays e.g. `bytes <= 3[3]`.  I don't like that syntax though, I almost prefer the syntax for bytes in general to just be  `bytes[3][3]`.  What're your thoughts?

**Comment by fubuloubu** [comment]
Yeah, I don't like the `bytes <= N` syntax at all TBH. `bytes[N]` is a better option.
My other thought would be something like `bytes(N)[M]` e.g. `M` entries of up to `N` bytes each (if that syntax is possible).
Or maybe `bytes(max=N)[M]`.
Or just simply `bytesN[M]`, where `N` is in some set `[1, J]` where `J` is some reasonable number like 256 (e.g. `bytes1[M]`, `bytes2[M]`, ..., `bytesJ[M]`).

If we're just talking strings, I'd prefer some more exact type for storing them e.g. the array `strings(max_len=M)` where each character is represented by a single, static byte set such as ASCII (1 byte), extended ASCII (2 bytes), or Unicode (UTF-32 = 4 bytes), up to a maximum number of characters `M`.

I think there needs to be more universal thinking in particular with strings, so my vote is for UTF-32 over storage in other formats.

**Comment by DavidKnott** [comment]
@fubuloubu The `string` in Solidity is a dynamic utf-8 encoded string.  What would be the goal of introducing a `string` type in Viper (given that a string can't be dynamic) / how would it differ from the current bytes in terms of functionality?  Would `strings(max_len=M)` be syntactic sugar?

**Comment by fubuloubu** [comment]
My bad, we know UTF-8 is dynamic but max 4 bytes, so we could do something like `string(N) := (bytes <= 4)[N]` (I didn't think of that initially, so UTF-8 can work that way). I mentioned UTF-32 since it would take the same number of reserved bytes (since EVM doesn't tightly pack storage anyways), for compatibility's sake using UTF-8 is smarter.

Yes, `string(N)` is syntactic sugar. I think `bytes(N) := bytes <= N` should only be reserved for working with generic raw data (e.g. pass-through of the data arg).

A string type would open the doors to more standard string functions like find/replace per character (if a 2/4-byte Unicode character was chosen, then find/replace per byte wouldn't work), `strip()`, `substr()`, etc.

**Comment by jacqueswww** [comment]
@fubuloubu what was the conclusion on this issue? Should we close the issue?

**Comment by fubuloubu** [comment]
If we wanted to add a string type that is very similar to bytes but assumes ASCII encoding, then `string[N]` would be a way to go to represent that

**Comment by haydenadams** [comment]
Personally I think there should be a string type to be friendly to frontends and solidity contracts that  expect ASCII token names/symbols.

**Comment by haydenadams** [comment]
@jacqueswww Kinda also think this should be added while Vyper is still in beta!

**Comment by jacqueswww** [comment]
@haydenadams Yup, you have a point :)

**Comment by fubuloubu** [comment]
Deprecated in favor of discussion in VIP #1210
