### ISSUE TITLE
FEATURE: Macros

### ISSUE THREAD

**Issue by fubuloubu** [ethereum/vyper#371]
What do you guys think of implementing macros/parameters/enumerations such that if there is some value being reused in the code, it is can be reused such that it's easier to read. Example:

```python
null_addr: macro(address) = 0x0000...0000
def check_null(addr: address):
    assert address != null_addr # replaced with 0x0000...0000 at compile-time
```

Not sure if that is the best syntax, but I hope you get the point.

**Comment by DavidKnott** [comment]
How would this functionality differ from Solidity's modifiers?

**Comment by fubuloubu** [comment]
No code substitutions, just values. The resulting assembly would simply have hard-coded values of a given type in the spot where the parameter was in use. It makes it much easier for the reader to follow to have a parameter instead of hard-coded values in multiple positions within some contract code.

Better example:
```python
stake: num[addr]
MAX_STAKE = num(1000)

def increase_stake(_stake_incr: num):
    assert _stake_incr + self.stake[msg.sender] <= MAX_STAKE
    self.stake[msg.sender] += _stake_incr

def move_stake(_to: address, _stake_amt: num):
    assert _stake_amt + self.stake[_to] <= MAX_STAKE
    self.stake[_to] += _stake_amt

def approve(threshold: decimal):
    assert (self.stake[msg.sender] / decimal(MAX_STAKE)) >= threshold
    selfdestruct(msg.sender)
```

**Comment by DavidKnott** [comment]
I like this idea.  What do you think about designing it so only constants can be assigned values at the global level?  The syntax could be something like:

    MAX_STAKE:  constant(num) = 1000

Also, I've always wanted to enforce constants being all capitals (usually it's just recommended) what do you think that?

**Comment by fubuloubu** [comment]
Perfect, I like it! Very clear

I don't know how you would enforce that with the Python parser, but I think it should be recommended versus enforced.

**Comment by fubuloubu** [comment]
I changed the name to be macros because #382 should be parameters

Alternative syntax for contants/macros:
```python
@constant
MAX_STAKE: num = 1000
```

which in the intermediate compilation stage would get removed from the resulting contract and all usages of that value will be replaced in the code below. @DavidKnott what do you think?

**Comment by DavidKnott** [comment]
I like your syntax a lot!

**Comment by jacqueswww** [comment]
@DavidKnott @fubuloubu  I like this idea, and it's definitely something we need. Especially useful as a form of enums/types ;)

**Comment by fubuloubu** [comment]
The crux of this was implemented with `constant`
