### ISSUE TITLE
FEATURE: Parameters

### ISSUE THREAD

**Issue by fubuloubu** [ethereum/vyper#382]
NOTE I renamed the prior "Parameters" to be Macros. Parameters should actually mean this.

Parameters should be like `public` where in addition to a getter it makes a setter that has a specific access group that can change them, and maybe creates an `event` log that sends when it is changed.

Example:
```python
@public # Propose alternative syntax for making something public?
owner: address

@parameter(owner) #Only owner can change maintainer
maintainer: address

@parameter(owner, maintainer) # Owner and maintainer can change the fee
fee: currency_value

def __init__():
   self.owner = msg.sender
...
```
which would produce something like this in the intermediate compilation stage:
```python
owner: address
maintainer: address
fee: currency_value

# Because owner is @public
@constant
def get_owner() -> address:
  return self.owner

# Because maintainer is @parameter
@constant
def get_maintainer() -> address:
  return self.maintainer
# Because maintainer is @parameter(owner)
def set_maintainer(_maintainer: address):
  assert msg.sender == self.owner # access control
  self.maintainer = _maintainer
  # Event log here? e.g. NewMaintainer(_maintainer)

# Because fee is @parameter
@constant
def get_fee() -> currency_value:
  return self.fee
# Because fee is @parameter(owner, maintainer)
def set_fee(_fee: address):
  assert msg.sender == self.owner or msg.sender == self.maintainer # access control
  # alternatively, assert msg.sender in [self.owner, self.maintainer]?
  self.fee = _fee
  # Event log here? e.g. NewFee(_fee)

def __init__():
   self.owner = msg.sender
...
```

Parameters are a common pattern, and this would be a very readable, easy way to represent that pattern.

![puppy](https://i.pinimg.com/originals/10/f2/d5/10f2d59bbc3c977d25edb32507adbc2d.jpg)

**Comment by DavidKnott** [comment]
@fubuloubu I'm definitely onboard with changing the syntax for public variables to `@public`.  As a smart-contract developer I'd used `@parameter` but I don't think it's intuitive, someone reading viper code won't naturally know what `@parameter` meant.  What do you think about using `@write` or `@setter`?

**Comment by fubuloubu** [comment]
Hmm, I don't think that is necessarily clearer, maybe `@update(addr1, [addr2, [...]])` showing that the listed address(es) can update the underlying parameter? I'm not sure if you should be allowed to use it without any addresses, like no access restrictions? Hmm...

**Comment by fubuloubu** [comment]
To be honest, parameter has a pretty well-recognized meaning outside of even programming. It came to my mind because at my old job we would have parameters with specific access control that we used to tune the software to have specific characteristics...

Maybe `@tuneable(addr1[, addr2[, ...]])`?

**Comment by DavidKnott** [comment]
I like `@updatable`.  And I don't think no access restrictions should be allowed because then someone could accidentally open up their variables to everyone if they're not careful.

**Comment by fubuloubu** [comment]
Totally, there should be an exception `@updateable parameters require at least one address for access restriction`

I was also thinking perhaps a static-sized array should be allowed, e.g.
```python
owners: address[5]

@updateable(owners)
transaction_limit: wei_value
```
which gives
```python
def set_transaction_limit(_transaction_limit: wei_value):
    assert msg.sender in owners
    self.transaction_limit = _transaction_limit
```
Although I'm pretty sure the `item in fixed_array` syntax doesn't work yet for viper, even though it would be a static gas computation

**Comment by DavidKnott** [comment]
I agree that static arrays should be allowed in `@updateable`.  I also think support for `in` should be added.  It'll just be syntactic sugar for:
```
owners: address[5]
for i in range(0,5):
    owners[i]

**Comment by fubuloubu** [comment]
@DavidKnott needs a `post beta` tag

**Comment by fubuloubu** [comment]
We have parameters!
