### ISSUE TITLE
Readthedocs is not updating

### ISSUE THREAD

**Issue by chgue** [ethereum/vyper#416]
### What's your issue about?
It seems like that the online documentation differs from /docs.
E.g. https://viper.readthedocs.io/en/latest/index.html differs from https://github.com/ethereum/viper/blob/master/docs/index.rst

### How can it be fixed?
Webhooks might be missing due to migration from https://eth-viper.readthedocs.io to https://viper.readthedocs.io/.

#### Cute Animal Picture
![](http://elelur.com/data_images/mammals/coati/coati-03.jpg)

**Comment by DavidKnott** [comment]
There never was a web hook, I'll talk to Vitalik about putting the `readthedocs` webhook in.

**Comment by chgue** [comment]
Ah didn't even notice that :) Thanks!

**Comment by fubuloubu** [comment]
@DavidKnott can probably close this, I just saw the latest docs PR get updated online: http://vyper.readthedocs.io/en/latest/types.html?highlight=as_wei_value

**Comment by jacqueswww** [comment]
@fubuloubu @DavidKnott I think it hasn't updated again, as the docs still say viper instead of vyper.

**Comment by fubuloubu** [comment]
Ugh

**Comment by jacqueswww** [comment]
@DavidKnott I unfortunately can't set the webhooks up for this. Would you have a look ? :smile_cat:
