### ISSUE TITLE
Suggestion: replace .v.py with a custom viper extension

### ISSUE THREAD

**Issue by federicobond** [ethereum/vyper#455]
Relying on the .py extension may bring problems down the road with both people and tools confusing Viper source code with Python. Possible alternatives: .viper, .vi

#### Cute Animal Picture

![article-2418451-1bc5dd92000005dc-964_634x421](https://user-images.githubusercontent.com/138426/32641944-a939efec-c5af-11e7-9bf7-2ed2429217eb.jpg)

*That's a dog with a cute hair extension.*

**Comment by fubuloubu** [comment]
We had `.vy` in mind. However, someone needs to do all the work of creating GitHub syntax highlighters, vim plugins, etc etc with our language. If you want to be that person, be my guest.

The language is still growing and changing however, so I think the idea was to create a formal syntax spec a little later on to base all of these things on. I welcome any work someone is willing to do to figure out what would be required when we reach that point though.

**Comment by federicobond** [comment]
Good, thanks for taking the time to respond @fubuloubu, I really appreciate it. For the moment I am more focused on Solidity, and some of these suggestions come from the lessons I learned along the way. It becomes much more difficult to change things once the language starts getting traction.

**Comment by jacqueswww** [comment]
@federicobond Very valid point, I have been really fond of the `.v.py` because it just highlights immediately - we will definitely reach the point to adopt `.vy` and I'll help with syntax highlighting templates where I can.
 @fubuloubu So it's looking up for using `.vy ` looking at it's uniqueness: https://github.com/search?utf8=%E2%9C%93&q=extension%3Avy+NOT+nothack&type=Code

**Comment by fubuloubu** [comment]
Is there a way to register that extension with GitHub? Perhaps we should do that now

**Comment by jacqueswww** [comment]
This is the guide: https://github.com/github/linguist/blob/master/CONTRIBUTING.md I found. I see solidity's PR is still pending: https://github.com/github/linguist/pull/3755

**Comment by fubuloubu** [comment]
Dang, the requirement to have 1000s of usage examples will definitely require a lot of promoting in Beta phase. Totally makes sense from GitHub's standpoint, but it looks like we can't do anything now to get Viper in there other than to keep doing what we're doing and making a great language.

I think with the potential name change issue we have as well as not being in Beta yet, `.v.py` works for now.

**Comment by chgue** [comment]
Out of curiosity I created a bare-bones [vim plugin](https://github.com/chgue/vim-viper) for `.vy` files. Should cover most syntax cases but I haven't tested it thoroughly. The extension can be changed easily, especially considering the name change issue @fubuloubu mentioned.

**Comment by jacqueswww** [comment]
@chgue are you still interested in keeping that vim plugin maintained ?

I have started updating all the outdated things, like the name & keywords. And will gladly PR it over to your repo - if you feel like maintaining it. Otherwise I will run with my own copy.
