### ISSUE TITLE
VIP: Change internal decorator to private

### ISSUE THREAD

**Issue by DavidKnott** [ethereum/vyper#471]
## Preamble
    VIP: <to be assigned>
    Title: Change internal to private
    Author: David Knott
    Type: Standard Track
    Status: Draft
    Created: 2017-11-15

## Simple Summary
Change `@internal` keyword to `@private` as it's more descriptive.  @jacqueswww 

## Motivation
This change would make Viper's syntax clearer because most programming languages choose to use `private` when only allowing other functions within the same class (or in our case contract to the call the function).  Also, because Viper doesn't support inheritance there will be no need to maintain support for both `@internal` and `@private` like Solidity does to differentiate visibility between only callable within a given contract and callable by the given contract and contracts that inherit from it.

## Specification
There'd be a syntax change from `@internal` to`@private`.

## Backwards Compatibility
This would break backwards compatibility as `@internal` would no longer be supported.  I don't see this as a big deal because Viper is not currently used in production.

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/)

**Comment by jacqueswww** [comment]
I like the wording of 'private' & 'public'. If everyone thinks this a good idea, I am willing to pledge some time to get it done :smile:

**Comment by fubuloubu** [comment]
I agree. Private/public, internal/external. Makes sense to me!

**Comment by jacqueswww** [comment]
@DavidKnott Off Topic, how do we pick numbers for VIPs ? Do we just use the issue numbers?

**Comment by jacqueswww** [comment]
@DavidKnott @fubuloubu starting on this now, I generally like to pick issues with the oldest date on - so doing the same system for VIPs.
