### ISSUE TITLE
VIP: Decorators should be Macros

### ISSUE THREAD

**Issue by fubuloubu** [ethereum/vyper#472]
## Preamble

VIP: 472
Title: Decorator Macros
Author: @fubuloubu
Type: Standard Truck
Status: Draft
Created: 2017-11-15

## Simple Summary
Decorators should be implemented in Viper syntax, not LLL

## Abstract
Replace current decorators with macros that provide equivalent functionality using Viper syntax. These macros would be executed during a pre-processor step in the compiler. The compiler will contain an option to output the pre-processed viper code for auditing purposes, if desired.

## Motivation
This reduces compiler code complexity in the intermediate stages (LLL), and makes it simpler to implement new decorators as macros for features the community needs.
One such example is: `@updatable(user1, user2, ...)` which creates a setter for variable with the associated decorator restricted to the given addresses (or list of addresses).

## Specification
Create a preprocessor step in the viper compiler that takes as input a string of viper code (containing macros) and outputs the same string to the next step in the compiler with the designed substitutions. It should do nothing other than these substitutions (e.g. no type checking, syntax checking, etc.)
These macros should be modular, easy to specify (using python triple quote syntax with format, e.g. Python 3 compliant), and clear as to their intent.

## Backwards Compatibility
It's still early, better to change the compiler structure now before we get too much further.

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/)

**Comment by DavidKnott** [comment]
I could see `@public` and `@internal` being implemented in Viper, but how could `@constant` be implemented given that there are some pretty fancy things that can be done in python at compile time and with `LLL` at runtime to ensure state changes don't work?

**Comment by fubuloubu** [comment]
I'm not sure I understand the second part of what you're saying, but I absolutely agree with the first part: there is most likely no way we can implement `@constant` as a macro

**Comment by fubuloubu** [comment]
With the preprocessor, we just don't do the substitution for `@constant`. Would work the same way as it does now!

**Comment by DavidKnott** [comment]
I love the idea of `@updatable`, so if I'm understanding your idea correctly you're suggesting adding the ability to create macro decorators while keeping the existing decorators as they are now?

**Comment by fubuloubu** [comment]
Well, not all decorators have to be macros, but the advantage to rewrite them is that they'll be written in native code, and easier to understand. Public globals work like this already, and the other decorators are essentially lll macros as written (making them harder to debug). Making as many decorators as we have (and future ones) be macros for viper code snippets (instead of lll) just makes it easier to debug/audit. I agree that it would be mostly the same under the hood

**Comment by fubuloubu** [comment]
`updateable()` being a more complex decorator would be easier to understand written as a Viper macro than a lll macro

**Comment by fubuloubu** [comment]
TODO:
2 PRs, one for pre-processor, another for moving current code

**Comment by daniel-jozsef** [comment]
Hey, new guy here. I can't say a lot about compiler internals (yet), but I honestly, really don't like the idea of @updatable. At all.

Generally, I think it's a bad idea to implement overly complex checks and behaviors at the language level. There is no actual need for @updatable, as it can easily be added as a private function call. The proposed behavior is too simplistic on one side (definitely unsuitable for any DAO-ish system), and at the same time, too complex for most use cases (check if sender is contract owner or not).

I think most attempts at bringing logic into the language layer would result in similar, overly restrictive and at the same time too costly designs.

And to be honest, too many macros (well, macros in general, especially if programmers can define their own) would break Viper's core premise of "no modifiers". Decorators should correspond to EVM-level features such as payable.

Also, hardcoding Ethereum addresses in contract code, which this decorator would encourage, is an antipattern in my opinion.

**Comment by fubuloubu** [comment]
That macro would create a setter in a defined style, it's more for the writer than the reader/auditor. The developer would share the code post-macro evaluation, so I think this assuages your concerns.

No addresses would be hard-coded, globals would be referenced instead.

**Comment by fubuloubu** [comment]
The point of macros is to define common patterns at the compiler level instead of allowing all sorts of weird syntax and stuff to be defined externally

**Comment by jacqueswww** [comment]
@fubuloubu at his stage I am considering to close this proposal. Reading the whole suggestion now, you could just replace the word `decorator` for `modifer` and it's in direct contradiction of our no-modifier rule. 

What do you think? Can we close this?

**Comment by fubuloubu** [comment]
Yeah, it definitely dives down the path of modifiers.

**Comment by fubuloubu** [comment]
Note: a language inheriting Vyper could do this though...
