### ISSUE TITLE
Proposal to improve syntax for logging events

### ISSUE THREAD

**Issue by federicobond** [ethereum/vyper#476]
I am finding the syntax for logs in Viper particularly confusing. To declare a log event, you do:

```
MyEvent = __log__(args...)
```

The expectation then, if you are used to other programming languages, would be that `MyEvent` becomes a top-level identifier, but instead, `MyEvent` is accessible only as a property of the magic `log` object:
```
log.MyEvent(args...)
```
This presents additional problems. Users may be inclined to ask what the value of the `log` object is by itself, what is the value of just `log.MyEvent`, etc.

My proposal is to just remove this dot and replace it with space, thus making `log` a keyword. Then, logging of events becomes:
```
log MyEvent(args...)
```
Then, it becomes clear that we are accessing the MyEvent identifier declared above, and also opens the door to treating `MyEvent(args...)` as a value later on:
```
e = MyEvent(args...)
if success:
    log e
```

This syntax is consistent with how you raise an exception in Python, and I believe most programmers will find it more intuitive than the current one.
```
raise MyException()
```

#### Cute Animal Picture

![thinkstockphotos-92911769](https://user-images.githubusercontent.com/138426/32916130-dc9653f4-caf9-11e7-8e0f-841881c8632d.jpg)

**Comment by fubuloubu** [comment]
I'm not opposed to this. Basically, `log` becomes like `assert` but expects a log type (e.g. `__log__`) after it, right?

I think it makes sense, but this would probably need to venture into custom syntax territory as I'm not sure this passes Python parsing (we currently use Python as our lexer via the `ast` module)

**Comment by federicobond** [comment]
Right. And yes, probably need to move to a custom lexer, although you can probably build something using the same tools that cpython uses, and you will need it to have flexibility in evolving in the syntax.

**Comment by jacqueswww** [comment]
Yes having `log<space>EventName` does feel like it's against python3 like syntax. What about somethin simple like:

**Comment by federicobond** [comment]
Why does `log event` feel like Python 2? You mean because of the change in `print`?

**Comment by federicobond** [comment]
My problem with your first suggestion (and the way Solidity does it) is that it's easy to confuse event logging with a normal function call. The `log ` prefix makes it clear that it's about something else, and will raise an error if you try to log a function call.

**Comment by fubuloubu** [comment]
@federicobond Function calls in viper come from somewhere e.g. `self.myFunctionCall()`, `self.contract.myFunctionCall()`, or `contract.myFunctionCall()` if `contract` is passed as an input

Although this only lends more credence to the current `log.MyEvent()` syntax lol

**Comment by jacqueswww** [comment]
Yes it does seem so, full circle ? @fubuloubu what do you think of `MyEvent.log()` vs. existing `log.MyEvent`?

**Comment by fubuloubu** [comment]
I like `log.MyEvent()` because it's like `log` is dispatching the event

**Comment by fubuloubu** [comment]
Just noticed this was never closed.
