### ISSUE TITLE
VIP: Any length bytes as map keys. 

### ISSUE THREAD

**Issue by jacqueswww** [ethereum/vyper#477]
## Preamble

    VIP: 477
    Title:  Any length bytes as map keys.
    Author: Jacques Wagener
    Type: Standard Track
    Status: Draft
    Created: 2017-11-15

## Simple Summary
Facilitate using `bytes`, of any length, to be used as key values for the mapping type.

## Abstract
Currently only BaseTypes (1 word / 32bytes in memory) can be used as keys for a map structure. This proposal proposes to introduce allowing the usage of any sized `bytes` type to be used as keys for a mapping type.

## Motivation

Allowing any length bytes as keys, allow cleaner usage of keys when compound or short string data might be necessary. Examples:
-  mapping multiple nicknames to a name. `self.nicknames['jacques'] = 'jacques'`
- require a lengthier compounded key. `self.info[concat(a, b)] = v`

## Specification

Example usage:
```python
mapped_bytes: num[bytes <= 5]

def set(k: bytes <= 5, v: num):
    self.mapped_bytes[k] = v


def get(k: bytes <= 5) -> num:
    return self.mapped_bytes[k]
```

## Backwards Compatibility
This change is backwards compatible because existing programs will still compile, previously invalid programs using `bytes` type as key will now work.

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/)

**Comment by jacqueswww** [comment]
@fubuloubu  @DavidKnott can probably close this now ? Or what do you think is the best way to lay VIPs to rest?

**Comment by fubuloubu** [comment]
I guess we should probably update the header to have a `VIP` number and set the status to implemented or something of that nature
