### ISSUE TITLE
Docs: Add example of logs

### ISSUE THREAD

**Issue by jessebmiller** [ethereum/vyper#487]
### What's your issue about?

There is no documentation on how to log events. It would be good to have some.

### How can it be fixed?

Add some plausible event logging to at least one of the examples
Also cover it under "Viper in Depth". Maybe in an "Events" section.

#### Cute Animal Picture

![2e84e12471abed26c87a170f56117f56--griffon-bruxellois-mattress](https://user-images.githubusercontent.com/471702/33111077-974305f6-cf11-11e7-8ebd-4b1efbb00b3a.jpg)

**Comment by DavidKnott** [comment]
@jessebmiller This definitely needs to be done, is this something you're interested in doing?

**Comment by jessebmiller** [comment]
Yeah, I'd be up for that. Would help if someone could point me to examples in the wild, or previous discussions of the feature.

**Comment by DavidKnott** [comment]
`ERC20.v.py` uses Viper logging to implement an ERC20 token.  For more in depth uses I'd look to `test_logging.py` as there aren't many examples of logging in the "wild."  If you have any questions please let me know!

**Comment by jessebmiller** [comment]
Thanks that sounds like a good start.

**Comment by gbisaga** [comment]
I am just getting started but if nobody else picks this up I would be happy to. I have been learning Solidity development and I am really disappointed with the language - consequently I am very excited to see an EVM language explicitly designed for safety. I haven't installed vyper yet (or is it "viper"?) because I normally only work in Windows, so I'm starting with getting Virtual Box etc. I would love to help the project in any way I can.

**Comment by DavidKnott** [comment]
Welcome @gbisaga! Docs can always be improved 😄.  I'd first get Vyper working in a virtual environment, and then you can start adding to the docs / picking up issues.  If you have any questions please use the Vyper gitter channel, our community is quite responsive!

**Comment by gbisaga** [comment]
I've been looking at this. I do have some questions, I'll try the gitter channel.

**Comment by gbisaga** [comment]
@DavidKnott I'm confused. What happened to "Viper in Depth"? I have found a short amount of text on readthedocs:

http://ethereum-viper.readthedocs.io/en/latest/viper-in-depth.html

but its source file seems to be gone:

https://github.com/ethereum/vyper/blob/master/docs/viper-in-depth.rst

The "stable" branch has this source file, but the "master" branch does not. I'd be happy to get started on the project by contributing documentation, and I think I know enough now to get something started on events, but I'm not sure where to put it. Would you recommend I just create an events.rst under the /docs directory?

**Comment by jacqueswww** [comment]
@gbisaga yes for now just create a separate logging entry please.
