### ISSUE TITLE
Change project name

### ISSUE THREAD

**Issue by fubuloubu** [ethereum/vyper#501]
### What's your issue about?
ETH Zurich, a university in Switzerland, already has a programming language named [Viper](http://viper.ethz.ch/). On October 30th I was contacted by a member of their faculty with a request for us to change our name in order avoid potential confusion with the myriad of tools available for that project. Their project has the potential to target the Ethereum ecosystem for formal verification purposes, so a name change was important to them.

Over the past month we have discussed many possible name changes, including (for posterity):
* Adder/Blackadder
* Anaconda
* Serpent 3.0
* Ophidian/Ophidiam

In the end, `vyper` was chosen as our desired project name, in order to disambiguate with the other Viper project and match our `.vy` file extension choice.

### How can it be fixed?
In order to accomplish the name change, we need to do the following
* Acquire project names at the various services we use e.g. PyPI, ReadTheDocs, snapcraft, etc. (Please list all below)
* Change the name on GitHub
* Communicate to the development community the name change, how to update git remotes, etc.
* Communicate to the wider Ethereum community about the name change, and market the project in order to build recognition

Please list below if there are further concerns or comments/questions. This must be a concerted effort by our entire community in order to be successful.

**Comment by jacqueswww** [comment]
* Change the python module/binary and all import statements to vyper ?

**Comment by fubuloubu** [comment]
@jacqueswww honestly completely forgot about that lol

**Comment by DavidKnott** [comment]
I have `eth-vyper` pypi and `vyper` read the docs.

**Comment by fubuloubu** [comment]
@DavidKnott @jacqueswww @vbuterin What do you think the best way is to explain and market the name change to the wider community? And at what point in time? (first beta, first release, etc)

**Comment by DavidKnott** [comment]
For explaining the name change I think we should just tell the community what happened.  In terms of releases I think Vyper is ready beta nowish.

**Comment by fubuloubu** [comment]
@jacqueswww @DavidKnott I think we have all our ducks in a row on this, just need to finish #627 and #630. Can you guys think of anything else that needs to get done?

**Comment by fubuloubu** [comment]
Lol, who marked this "Easy Pickings"?

**Comment by jacqueswww** [comment]
This has been done. Wooooo :champagne: :fireworks:
