### ISSUE TITLE
[Documentation] Broken link to testing strategy in README.md

### ISSUE THREAD

**Issue by sdtsui** [ethereum/vyper#512]
Heyo, I noticed that the link to 'testing strategy' is no longer on `master`, and points to an open link.

![](https://puu.sh/ytMqd/f0d0756a65.png)

Where is this supposed to point? I can also make a PR changing this to point to somewhere straightforward, like `tests/conftest.py`. Let me know what you folks think. Thanks!!

**Comment by DavidKnott** [comment]
@sdtsui Eventually we'll have an docs page dedicated to testing and then the link will  be to there.

**Comment by sdtsui** [comment]
@DavidKnott - cool, thanks! I'll re-engage on this after I've written some draft docs for testing and send over to you.

**Comment by jacqueswww** [comment]
Closing in favour of #912.
