### ISSUE TITLE
VIP: Change public global getter from `get_var` to `var`

### ISSUE THREAD

**Issue by DavidKnott** [ethereum/vyper#518]
## Preamble

    VIP: <to be assigned>
    Title: Change public global getter from `get_var` to `var`
    Author: David Knott
    Type: Standard Track
    Status: Draft
    Created: 2017-11-27

## Simple Summary
I'd like to change the getter syntax for global variables.

## Motivation
I think changing the public getter from `get_var` to `var` will make Viper cleaner and easier to use.  It'll also make Solidity compatibility easier as right now custom getters have to be written to Solidity ABI's.

## Specification
Internally the change would look like this:
```
in contract:
x: public(num)
proposed getter in compiler:
@public
@constant
def x() -> num:
    return x
current getter in compiler:
@public
@constant
def get_x() -> num:
    return x
```
The developer facing side will look like this:
```
in contract:
x: public(num)
proposed getter created:
c.x()
current getter created:
c.get_x()
```
## Backwards Compatibility
This VIP will break all contracts using the `public` getter for global variables, though I'm not too worried about this as Viper is not widely used yet. 

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/)

**Comment by fubuloubu** [comment]
We were talking about auto setters through `@upgradable(address1, ...)`. Is operator overloading supported in viper? (I didn't think so, overloading is a potentially buggy process that could lead to user error and obscurity)

Also requires #516 to be solved first, put it in dependancies

Last, change it to VIP in the title please!

**Comment by DavidKnott** [comment]
@fubuloubu I solved #516 but I didn't like how `vipercoin.v.py` had to be changed.  I'd like to solve this issue before #516.

**Comment by fubuloubu** [comment]
well, `@updatable()` isn't anything right now, perhaps `@constant` produces `def var()` and that one would produce `update_var(new_val)`, which I think is an okay style choice if well explaining in the documentation.

**Comment by jacqueswww** [comment]
:+1: from me, removing the `get_` seems clear enough to me.

**Comment by fubuloubu** [comment]
I guess I still don't understand how this jives with #516, which is basically disallowing functions with the same name as globals. This is specifically creating functions with the same name as globals. Perhaps it happens "behind the scenes" i.e. the syntax is disallowed in viper but the code produces it, however this is sort of weird dichotomy because then if someone wanted to use a getter inside their code for whatever reason they wouldn't be able to.

I guess just comment how this VIP and the proposed solution to #516 make sense together

**Comment by jacqueswww** [comment]
@fubuloubu good point... it would seems weird if this produced same function names as variables.

**Comment by fubuloubu** [comment]
Well, not weird necessarily, just weird if we then disallowed that behavior as a result of #516 but then created that behavior as a result of this VIP lol
