### ISSUE TITLE
VIP: Error Logs

### ISSUE THREAD

**Issue by fubuloubu** [ethereum/vyper#523]
## Preamble

VIP: 523
Title: Error Logs
Author: @fubuloubu
Type: Standard
Status: Draft
Created: 2017-11-27

## Simple Summary
Create an Error log to manage and debug runtime errors

## Abstract
Send out a log containing the line number in the source code and an error message after a `revert` type Exception that cancels further processing

## Motivation
The motivation behind this VIP is to help with debugging by having statements that localize your attention in the failing method invocation to a specific line in source code, and an error message that helps you understand what went wrong. We would most likely be unable to describe errors in a more detailed way than this unless we built these Error logs more dynamically, or used another method to show the values of any operand(s) in memory.

## Specification
Internal Use Only
We should attempt to add LLL statements (or a helper) for creating an Error log after every `revert` in our LLL IR. This log should be of type `Error: __log__({line: num, msg: bytes <= 40})` where `line` corresponds to the line number in the Viper source code corresponding to the potential `revert` statement, and `msg` contains a description of the runtime error.
This log would be invoked AFTER the revert occurs in LLL, via a push to memory (refer to @DavidKnott for implementation) so a client running any code that creates a runtime issue can see a log helping them debug what happens.
Error messages should be unique! (Perhaps we can leverage a Python class for this?)

## Backwards Compatibility
Backwards compatible, should not cause any functional changes

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/)

**Comment by jacqueswww** [comment]
@fubuloubu I like it! It could be seen as a 'compile with debug symbols' type of system.

**Comment by fubuloubu** [comment]
@jacqueswww i.e. opt-out (to save gas costs)?

Yeah, I'm game with that.

**Comment by fubuloubu** [comment]
Optional behavior:

If someone uses:
```python
assert variable == condition
```
We push out "Assert Error"

But if someone specifies a string (like in Python):
```python
assert variable == condition, "I don't like this"
```
Pass through that bytestring instead

**Comment by jacqueswww** [comment]
Closing in favour https://github.com/ethereum/vyper/issues/889 / Phase 2 reason string support.
