### ISSUE TITLE
Viper setup script exited with error in ethereum setup command

### ISSUE THREAD

**Issue by WouterBoekel** [ethereum/vyper#535]
### What's your issue about?

I'm trying to build viper in a virtual environment using the viper documentation. I've gotten until "make", after cloning viper using git command. I get an output error:

**error: Setup script exited with error in ethereum setup command: 'tests_require' must be a string or list of strings containing valid project/version requirement specifiers; Unordered types are not allowed**

Here's the complete output, also containing the error at the end:
(viper-venv) Wouters-MacBook:viper Wouter$ make
python setup.py install
running install
running bdist_egg
running egg_info
writing viper.egg-info/PKG-INFO
writing dependency_links to viper.egg-info/dependency_links.txt
writing requirements to viper.egg-info/requires.txt
writing top-level names to viper.egg-info/top_level.txt
reading manifest file 'viper.egg-info/SOURCES.txt'
writing manifest file 'viper.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.11-x86_64/egg
running install_lib
running build_py
creating build/bdist.macosx-10.11-x86_64/egg
creating build/bdist.macosx-10.11-x86_64/egg/viper
copying build/lib/viper/functions.py -> build/bdist.macosx-10.11-x86_64/egg/viper
copying build/lib/viper/compile_lll.py -> build/bdist.macosx-10.11-x86_64/egg/viper
copying build/lib/viper/server.py -> build/bdist.macosx-10.11-x86_64/egg/viper
copying build/lib/viper/premade_contracts.py -> build/bdist.macosx-10.11-x86_64/egg/viper
copying build/lib/viper/opcodes.py -> build/bdist.macosx-10.11-x86_64/egg/viper
copying build/lib/viper/compiler.py -> build/bdist.macosx-10.11-x86_64/egg/viper
creating build/bdist.macosx-10.11-x86_64/egg/viper/signatures
copying build/lib/viper/signatures/__init__.py -> build/bdist.macosx-10.11-x86_64/egg/viper/signatures
copying build/lib/viper/signatures/event_signature.py -> build/bdist.macosx-10.11-x86_64/egg/viper/signatures
copying build/lib/viper/function_signature.py -> build/bdist.macosx-10.11-x86_64/egg/viper
copying build/lib/viper/__init__.py -> build/bdist.macosx-10.11-x86_64/egg/viper
copying build/lib/viper/types.py -> build/bdist.macosx-10.11-x86_64/egg/viper
creating build/bdist.macosx-10.11-x86_64/egg/viper/parser
copying build/lib/viper/parser/stmt.py -> build/bdist.macosx-10.11-x86_64/egg/viper/parser
copying build/lib/viper/parser/parser_utils.py -> build/bdist.macosx-10.11-x86_64/egg/viper/parser
copying build/lib/viper/parser/__init__.py -> build/bdist.macosx-10.11-x86_64/egg/viper/parser
copying build/lib/viper/parser/parser.py -> build/bdist.macosx-10.11-x86_64/egg/viper/parser
copying build/lib/viper/parser/expr.py -> build/bdist.macosx-10.11-x86_64/egg/viper/parser
copying build/lib/viper/utils.py -> build/bdist.macosx-10.11-x86_64/egg/viper
copying build/lib/viper/optimizer.py -> build/bdist.macosx-10.11-x86_64/egg/viper
copying build/lib/viper/exceptions.py -> build/bdist.macosx-10.11-x86_64/egg/viper
byte-compiling build/bdist.macosx-10.11-x86_64/egg/viper/functions.py to functions.cpython-36.pyc
byte-compiling build/bdist.macosx-10.11-x86_64/egg/viper/compile_lll.py to compile_lll.cpython-36.pyc
byte-compiling build/bdist.macosx-10.11-x86_64/egg/viper/server.py to server.cpython-36.pyc
byte-compiling build/bdist.macosx-10.11-x86_64/egg/viper/premade_contracts.py to premade_contracts.cpython-36.pyc
byte-compiling build/bdist.macosx-10.11-x86_64/egg/viper/opcodes.py to opcodes.cpython-36.pyc
byte-compiling build/bdist.macosx-10.11-x86_64/egg/viper/compiler.py to compiler.cpython-36.pyc
byte-compiling build/bdist.macosx-10.11-x86_64/egg/viper/signatures/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.macosx-10.11-x86_64/egg/viper/signatures/event_signature.py to event_signature.cpython-36.pyc
byte-compiling build/bdist.macosx-10.11-x86_64/egg/viper/function_signature.py to function_signature.cpython-36.pyc
byte-compiling build/bdist.macosx-10.11-x86_64/egg/viper/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.macosx-10.11-x86_64/egg/viper/types.py to types.cpython-36.pyc
byte-compiling build/bdist.macosx-10.11-x86_64/egg/viper/parser/stmt.py to stmt.cpython-36.pyc
byte-compiling build/bdist.macosx-10.11-x86_64/egg/viper/parser/parser_utils.py to parser_utils.cpython-36.pyc
byte-compiling build/bdist.macosx-10.11-x86_64/egg/viper/parser/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.macosx-10.11-x86_64/egg/viper/parser/parser.py to parser.cpython-36.pyc
byte-compiling build/bdist.macosx-10.11-x86_64/egg/viper/parser/expr.py to expr.cpython-36.pyc
byte-compiling build/bdist.macosx-10.11-x86_64/egg/viper/utils.py to utils.cpython-36.pyc
byte-compiling build/bdist.macosx-10.11-x86_64/egg/viper/optimizer.py to optimizer.cpython-36.pyc
byte-compiling build/bdist.macosx-10.11-x86_64/egg/viper/exceptions.py to exceptions.cpython-36.pyc
creating build/bdist.macosx-10.11-x86_64/egg/EGG-INFO
installing scripts to build/bdist.macosx-10.11-x86_64/egg/EGG-INFO/scripts
running install_scripts
running build_scripts
creating build/bdist.macosx-10.11-x86_64/egg/EGG-INFO/scripts
copying build/scripts-3.6/viper-serve -> build/bdist.macosx-10.11-x86_64/egg/EGG-INFO/scripts
copying build/scripts-3.6/viper -> build/bdist.macosx-10.11-x86_64/egg/EGG-INFO/scripts
changing mode of build/bdist.macosx-10.11-x86_64/egg/EGG-INFO/scripts/viper-serve to 755
changing mode of build/bdist.macosx-10.11-x86_64/egg/EGG-INFO/scripts/viper to 755
copying viper.egg-info/PKG-INFO -> build/bdist.macosx-10.11-x86_64/egg/EGG-INFO
copying viper.egg-info/SOURCES.txt -> build/bdist.macosx-10.11-x86_64/egg/EGG-INFO
copying viper.egg-info/dependency_links.txt -> build/bdist.macosx-10.11-x86_64/egg/EGG-INFO
copying viper.egg-info/requires.txt -> build/bdist.macosx-10.11-x86_64/egg/EGG-INFO
copying viper.egg-info/top_level.txt -> build/bdist.macosx-10.11-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/viper-0.0.2-py3.6.egg' and adding 'build/bdist.macosx-10.11-x86_64/egg' to it
removing 'build/bdist.macosx-10.11-x86_64/egg' (and everything under it)
Processing viper-0.0.2-py3.6.egg
Removing /Users/Wouter/viper-venv/lib/python3.6/site-packages/viper-0.0.2-py3.6.egg
Copying viper-0.0.2-py3.6.egg to /Users/Wouter/viper-venv/lib/python3.6/site-packages
viper 0.0.2 is already the active version in easy-install.pth
Installing viper script to /Users/Wouter/viper-venv/bin
Installing viper-serve script to /Users/Wouter/viper-venv/bin

Installed /Users/Wouter/viper-venv/lib/python3.6/site-packages/viper-0.0.2-py3.6.egg
Processing dependencies for viper==0.0.2
Searching for ethereum==2.1.0
Reading https://pypi.python.org/simple/ethereum/
Downloading https://pypi.python.org/packages/5c/0d/1ca85eb4ddcac8ef9612d7f635ebb37b7e651a86a4c03705c7b681d168b6/ethereum-2.1.0.tar.gz#md5=48421849d21063b7b17fe2933762aee6
Best match: ethereum 2.1.0
Processing ethereum-2.1.0.tar.gz
Writing /var/folders/q4/r9xymw_93cx9vwy7drzl6qm00000gn/T/easy_install-5bluyu2a/ethereum-2.1.0/setup.cfg
Running ethereum-2.1.0/setup.py -q bdist_egg --dist-dir /var/folders/q4/r9xymw_93cx9vwy7drzl6qm00000gn/T/easy_install-5bluyu2a/ethereum-2.1.0/egg-dist-tmp-xz5snwe1
error: Setup script exited with error in ethereum setup command: 'tests_require' must be a string or list of strings containing valid project/version requirement specifiers; Unordered types are not allowed
make: *** [init] Error 1

Is anyone familiar with this error and could help me out to resolve it?

#### Cute Animal Picture

![ljhivtx](https://user-images.githubusercontent.com/5228546/33516553-f5da6828-d774-11e7-91bd-5f8444225810.jpg)

Any help is appreciated, thanks in advance!

**Comment by fubuloubu** [comment]
It looks like an issue with [pyethereum](https://github.com/ethereum/pyethereum). You should get on their gitter and ask what's up with it, and report back here!

Just quickly browsing, it looks like this is the problem:

```python
# setup.py:
...
setup_requires=[
        #    'pytest-runner==2.7'
],
...
```

**Comment by sbmandava** [comment]
Same issue...

Installed /root/viper-venv/lib/python3.6/site-packages/viper-0.0.2-py3.6.egg
Processing dependencies for viper==0.0.2
Searching for ethereum==2.1.0
Reading https://pypi.python.org/simple/ethereum/
Downloading https://pypi.python.org/packages/5c/0d/1ca85eb4ddcac8ef9612d7f635ebb37b7e651a86a4c03705c7b681d168b6/ethereum-2.1.0.tar.gz#md5=48421849d21063b7b17fe2933762aee6
Best match: ethereum 2.1.0
Processing ethereum-2.1.0.tar.gz
Writing /tmp/easy_install-jkj47wyw/ethereum-2.1.0/setup.cfg
Running ethereum-2.1.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-jkj47wyw/ethereum-2.1.0/egg-dist-tmp-r58bpu_t
error: Setup script exited with error in ethereum setup command: 'tests_require' must be a string or list of strings containing valid project/version requirement specifiers; Unordered types are not allowed
Makefile:4: recipe for target 'init' failed
make: *** [init] Error 1

**Comment by WouterBoekel** [comment]
Thanks for the advice! I looked a bit into pyethereum but decided to try a fresh install of my macbook. After installing High Sierra I followed the viper installation instructions and everything works fine now. No idea what the problem really was, but a fresh install fixed it. Yippeee!

**Comment by fubuloubu** [comment]
I think you would probably find that the version of `pyethereum` was recently updated to 2.1.5, which fixed the problem you were encountering with their setup

**Comment by fubuloubu** [comment]
Please close @WouterBoekel

**Comment by jacqueswww** [comment]
Closing, `pyethereum` is now `py-evm`.
