### ISSUE TITLE
VIP: Safe External Contract Calls

### ISSUE THREAD

**Issue by DavidKnott** [ethereum/vyper#542]
This is the suggested template for new VIPs.

## Preamble

    VIP: <to be assigned>
    Title: Safe External Contract Calls
    Author: David
    Type: Standard Track
    Status: Draft
    Created: 2017-12-4

## Simple Summary
We can use the `STATICCALL` opcode to make external contract calls safer.

## Abstract
External contract calls (primarily those that change state) are dangerous but we can make them safer by having developers think about how they external contract calls and wether or not they want to trust the contract they're calling to.

## Motivation
Many attacks have involved external contract calls so it's important for us to think carefully about how we can make them as safe as possible

## Specification
The `static` and `modifiable` keywords will allow developers to declare addresses that state changing external contract calls can always be made to.  If an address is `static` no state changes may be made (`STATICCALL` opcode is used), if an address is `modifiable` state changes may be made( `CALL` opcode is used).
```
    contract_1 = """
lucky: public(num)
@public
def set_lucky(_lucky: num):
    self.lucky = _lucky
"""

    contract_2 = """
class Bar():
    def set_lucky(_lucky: num): pass
modifiable_bar_contract: modifiable(Bar)
static_bar_contract: static(Bar)
@public
def __init__(contract_address: contract(Bar)):
    self.modifiable_bar_contract = contract_address
    self.static_bar_contract = contract_address

@public
def trusted_set_lucky(_lucky: num):
    self.modifiable_bar_contract.set_lucky(_lucky)

@public
def untrusted_set_lucky(_lucky: num):
    self.static_bar_contract.set_lucky(_lucky)
    """

    c1 = get_contract(contract_1)
    c2 = get_contract(contract_2, args=[c1.address])
    c2.trusted_set_lucky(7)
    assert c1.get_lucky() == 7
    # Fails after attempting a state change after a call to an untrusted address
    assert_tx_failed(lambda: c2.untrusted_set_lucky(5))
```

## Backwards Compatibility
This VIP is not backwards compatible as it will make multiple state changing external contract calls to untrusted addresses invalid.

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/)

**Comment by DavidKnott** [comment]
@fubuloubu Made the `static` and `modifiable` updates to the example.  Let me know if you've got any questions

**Comment by fubuloubu** [comment]
Looks good if tests are added. Personally I think the syntax could be nicer, but that requires a custom parser I believe

**Comment by jacqueswww** [comment]
@DavidKnott @fubuloubu so one question I had here that we have to make sure... Is there a scenario where one would want to declare per-method *static* or *modifiable* instead ? Or can we safely assume we want this only on a contract level?

**Comment by DavidKnott** [comment]
There are definitely situations where we'd want to do it on a by method basis.  Like if someone's interacting with an ERC20 token it'll have one address and checking the allowance should be `static` but `transferFrom` should be `modifiable`.  It'll add quite a bit of verbosity but we could consider implementing static/modifiable at the external contract definition level or on a case by case basis at the function call level.
``` python
# External contract level
class Bar():
    def set_lucky(_lucky: num): modifiable
    def get_luck(): static

# Case by case on function call
modifiable(bar_contract.set_lucky(7))
static(bar_contract.get_luck())
```
Doing it at the external contract level seems like a good balance to me.

I'd also think we should not allow `modifiable` contracts to change state more than once in any given function (switching from `CALL` to `STATICCALL` after one state changing call).

**Comment by jacqueswww** [comment]
Something to think about! using `static` and `modifiable` at that level will also the problem of having `pass` there the whole time :) I actually really like that idea.  And the we perhaps drop marking the whole contract as modifiable & static ?
So yes, I vote for only implementing the first example ;)

**Comment by fubuloubu** [comment]
:+1: for getting of `pass` lol
