### ISSUE TITLE
Exponent with units is not correct

### ISSUE THREAD

**Issue by yzhang90** [ethereum/vyper#547]
### What's your issue about?

The following program is rejected by the compiler:
```
@public
def foo():
    a : num(wei)
    b : num(wei**2)
    a = 2
    b = a**2
```

### How can it be fixed?

In arithmetic pow, it calls `combine_units` which only handles multiplication and division, in my point of view.

#### Cute Animal Picture

![image](https://user-images.githubusercontent.com/5641590/33633497-b22bffb0-d9d6-11e7-894e-c4fba7b3acb4.png)

**Comment by fubuloubu** [comment]
to reword, you think `num(wei**2)` is causing the issue?

**Comment by yzhang90** [comment]
Look at https://github.com/ethereum/viper/blob/b0cec59d24051e3bb3577475211c277e78c68a23/viper/parser/expr.py#L290. First, exponent should be a pure value instead of unit. You already fixed that. Second, a**b should *multiply* the unit of `a` b times. However, I think `combine_units` only *add* or *subtract* the exponent of the unit instead of doing multiplication. Back to the example, the compiler thinks the unit of a**2 is wei instead of wei**2, and that's why the program is rejected. Basically, you did it correctly when paring unit https://github.com/ethereum/viper/blob/b0cec59d24051e3bb3577475211c277e78c68a23/viper/types.py#L237, but not correctly when you perform unit arithmetic(pow).

**Comment by yzhang90** [comment]
By the way, I think it is hard to check the unit type of the following program:
```
def foo(a:num):
    b:num(wei)
    c = b ** a
```
It is not possible to determine the unit of `c` at compile time ( it is `wei`**a). It is better to reject this program.

**Comment by fubuloubu** [comment]
> By the way, I think it is hard to check the unit type of the following program:
>```python
>def foo(a:num):
>     b:num(wei)
>     c = b ** a
>```
>It is not possible to determine the unit of c at compile time ( it is wei**a). It is better to reject this program.

I agree with this

**Comment by DavidKnott** [comment]
@yzhang90 Could you explain why it's not possible to determine `c` at compile time (to me it's just `num(wei)`)?

**Comment by fubuloubu** [comment]
Depends on your interpretation, but `wei**2` is different than `wei`, so having `wei**n` is the not detectable at compile time.

I think we can discuss this further whether to allow. I'm an engineer, so I have a strong aversion to mixing units lol

**Comment by yzhang90** [comment]
@DavidKnott  As what @fubuloubu already mentioned, 
```
   a: num(sec)
   b = a * a
```
The unit of `b` should be  sec^2.  `b=a**2` should have the same unit.
Consider the following program:
```
def foo(a:num):
    b:num(sec)
    c:num(sec**2)
    c = b ** a
```
If the argument `a` is 2, then the last assignment is correct, Otherwise, it is not.

**Comment by denis-bogdanas** [comment]
I'm not sure if the test for units and exponents is correct:

https://github.com/ethereum/vyper/blob/master/tests/parser/types/numbers/test_num.py#L63

    @public
    def foo() -> int128(wei):
        a: int128(wei)
        b: int128
        c: int128(wei)
        a = 2
        b = 2
        c = a ** b
        return c

Shouldn't c be of type `int128(wei**2)` ?

**Comment by fubuloubu** [comment]
@denis-bogdanas Thanks for pointing that out. I believe this is supposed to fail actually, since `b` can be other values besides `2`, which would cause the units not to be able to be determined statically.

@jacqueswww Looks like a problem to me. What do you think?

**Comment by jacqueswww** [comment]
@denis-bogdanas good catch thanks. Will have a look ;)

**Comment by jacqueswww** [comment]
@denis-bogdanas yes it should be wei**2, will se why it doesn't except.
