### ISSUE TITLE
Support `continue` statement inside a `for` block

### ISSUE THREAD

**Issue by adhikasp** [ethereum/vyper#552]
### What's your issue about?

Viper currently doesn't support `continue` statement inside of a `for` block.

Example

```python
@public
def func():
    for i in range(10):
        if i == 5:
            continue
```

Result in

```
viper.exceptions.StructureException: line 5: Unsupported statement type
            continue
------------^
```

#### Cute Animal Picture

![a baby ducks](https://i.pinimg.com/736x/1f/c7/8e/1fc78e8c32d80d7a481687c4da4df4bc--cute-ducklings-baby-ducks.jpg)

**Comment by fubuloubu** [comment]
Does `break` work?

**Comment by DavidKnott** [comment]
@fubuloubu `Break` works how it's supposed to

**Comment by DavidKnott** [comment]
@adhikasp Great catch, `continue` is a reserved word in `utils.py` but I don't think it's currently supported.

**Comment by DavidKnott** [comment]
@adhikasp `continue` has been added, closing
