### ISSUE TITLE
Need support for packing List Type arugment

### ISSUE THREAD

**Issue by yzhang90** [ethereum/vyper#554]
### What's your issue about?
```
@public
def foo(x:num[2]): 
    pass 
@public 
def bar(): 
    x:num[2] 
    self.foo(x)
```
The program fails to compile because packing List Type argument is not supported.

#### Cute Animal Picture

![image](https://user-images.githubusercontent.com/5641590/33744248-f8a65d82-db75-11e7-86e3-9d2b487c70ed.png)

**Comment by jacqueswww** [comment]
On it.
