### ISSUE TITLE
Path to python3.6 didn't work when setting up a virtualenv before installing Viper, python3.6 did

### ISSUE THREAD

**Issue by jamesray1** [ethereum/vyper#558]
* viper Version: haven't installed yet (having an issue)
* pyethereum Version: N/A
* OS: Linux 4.13
* Python Version (python --version): 3.6.3
* Environment (output of `pip freeze`):
asn1crypto==0.22.0
cryptography==1.9
duplicity==0.7.12
enum34==1.1.6
idna==2.5
ipaddress==1.0.17
keyring==10.4.0
keyrings.alt==2.2
lockfile==0.12.2
nose==1.3.7
pycrypto==2.6.1
pygobject==3.24.1
Pyste==0.9.10
pyxdg==0.25
SecretStorage==2.3.1
six==1.10.0
unity-lens-photos==1.0
vboxapi==1.0
virtualenv==15.1.0

### What's your issue about?

When following the steps to install Viper [here](https://viper.readthedocs.io/en/latest/installing-viper.html), I got stuck at this command:
```
virtualenv -p /usr/local/lib/python3.6/bin/python3 --no-site-packages ~/viper-venv
The path /usr/local/lib/python3.6/bin/python3 (from --python=/usr/local/lib/python3.6/bin/python3) does not exist
```

```
$ whereis virtualenv
virtualenv: /usr/bin/virtualenv /usr/share/man/man1/virtualenv.1.gz
```

**Comment by fubuloubu** [comment]
Do you have python 3.6 installed?

**Comment by jamesray1** [comment]
I used `virtualenv -p python3.6 --no-site-packages ~/viper-venv` and it worked fine.
