### ISSUE TITLE
VIP: Custom Parser

### ISSUE THREAD

**Issue by fubuloubu** [ethereum/vyper#563]
## Preamble
VIP: 563
Title: Custom Parser
Author: @fubuloubu @DavidKnott @jacqueswww 
Type: Standard
Status: Draft
Created: 2017-12-08

## Simple Summary
Implement a custom parser for Viper that doesn't directly tie us to Python-only syntax, enabling a more focused grammer for our langauge

## Abstract
We've been discussing this for a while. A custom parser would allow us to define our syntax more precisely rather than leveraging Python syntax and being tied to only what Python's syntax can provide. We will continue to use Python as a template due to it's clarity and ease of reading, but we need to make decisions that diverge from Python and a custom Parse will enable that.

## Motivation
There are specific things that have been discussed where this is necessary:
* Clarifying the external contract type
* Changing the mapping type for greater clarity
* Custom Types
* etc...

## Specification
We may be able to leverage a Python-compatible lex/yacc library like [ply](https://github.com/dabeaz/ply). We should also leverage some of the work the [k-framework](https://github.com/kframework/viper-semantics) guys are doing in order to infer a grammar that is consistent and free of formalized conflicts

## Backwards Compatibility
Try to maintain backwards compatibility initially, however some of the VIPs this one will enable will be breaking changes in the syntax.

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/)

**Comment by daniel-jozsef** [comment]
Please don't. Let's not turn this into another Solidity. :(

**Comment by fubuloubu** [comment]
We're already running into limitations of the underlying python syntax, and for future growth there will be a need to violate the syntax in subtle and not-so-subtle ways. Viper is definitely a different language from Python, we will try to stick to the syntax as closely as possible but there are different situations that we need a custom parser to handle.

**Comment by DavidKnott** [comment]
I don't think having a custom parser will negatively effect clarity, given how different writing smart contract code is to python code (particularly in terms of security) it would be helpful to customize certain parts of the parser.  Here are a couple examples where a customer parser could come in handy:
1) Using a more descriptive keyword than `class` for defining external
2) Changing the syntax of logging to make it clearer, as `MyLog: __log__({arg1: num})` is limited by python syntax

**Comment by thomkeh** [comment]
The danger of a custom parser is bugs. (There were 8 critical bugs in the Serpent compiler when Augur ordered an audit...)

External contracts could be nicely specified if [this suggestion](https://github.com/ethereum/viper/issues/454#issuecomment-343431272) was implemented. You could say that you can only inherit from Contract and ExternalContract and there can only be one Contract per file. The inheritance would basically do nothing.

More descriptive keywords could be realized by the preprocessor that is mentioned in [this proposal](https://github.com/ethereum/viper/issues/472).

For the mapping syntax, something like this should be possible: `Mapping[KeyType, ValueType]`.

**Comment by mslipper** [comment]
One potential solution is to copy the existing Python grammar, modify it to match the Viper language, then generate a parser from that grammar using a tool like [ANTLR](http://www.antlr.org/). This confers a number of benefits:

- Generated parsers have been around forever and are used regularly in security-critical applications.
- Development is simplified considerably. The Viper team can focus on the language's syntax and features without spending time maintaining a bespoke parser.
- Parser generators favor a grammar-first development workflow. The grammar won't be just another document to maintain - it'll be an integral part of the language. Having an up-to-date grammar simplifies third-party tool development (i.e., static analysis tools, syntax highlighters, etc.) considerably.

If there's interest, I'd be happy to build a small prototype.

**Comment by fubuloubu** [comment]
@mslipper :+1: I think this is the approach we were getting at. Thanks for suggesting a tool!

Is there an easy way to integrate this with our Python flow (e.g. ANTLR wrapper module) so that the build process could be managed 100% in Python? ANTLR is a Java program, but I see some evidence that this is possible [here](https://github.com/antlr/antlr4/blob/master/doc/python-target.md)

**Comment by fubuloubu** [comment]
Meeting Minutes:

1. Can we use custom keywords in the Python AST module?
2. Is there a better way to segment/streamline work with an external Module to handle Lexing/Parsing

**Comment by mslipper** [comment]
@fubuloubu ANTLR is written in Java, but it'll generate a parser in any language it supports. The `python-target` you linked is the exact solution you're looking for 😄. For build flow, I'd suggest adding a target to your `Makefile` that runs ANTLR prior to making the egg and running tests. That way there is no Java dependency for Viper's users, only developers.

**Comment by fubuloubu** [comment]
We were discussing this along with a few other things in the call we had today. I think we're still a little reluctant to move to a custom solution fully. We were trying to figure out if there was a way to modify or extend the AST module to get what we're looking for, I think to do that we need a summary of the changes we are looking to make.

From the original post above, these are (with examples):
1. Clarifying the external contract type #541
```python
my_contract: contract(
    foo(),
    bar() -> num,
)
```
2. Changing the mapping syntax #564
```python
my_map: map(basetype1 -> basetype2)
```
3. Allowing custom types/type aliasing #300
```python
wei := num("wei")
fee: wei
```

We also chatted a bit today about #584, and I believe my proposed solution may be able to sidestep all of this by changing how types are handled a bit. I think most of our reasons for wanting a custom parser have more to do with being able to specify and easily work with different kinds of globals. Check out the bottom of that issue and feel free to add to the discussion.

**Comment by maurelian** [comment]
I've started working on [defining the grammar in ANTLR](https://github.com/maurelian/solidity-antlr4/blob/master/Vyper.g4). I'm following a similar approach used to create a [js-solidity parser](https://github.com/federicobond/solidity-parser-antlr).

This will enable us to generate a parser to use in our [Surya](https://github.com/ConsenSys/surya/issues/15) tool. 

So far I've just been extracting the grammar from documentation and examples, but if the vyper project itself might make use of it in the future, it would be better to ensure the names and structure of nodes is similarly defined. Would someone from the core team be willing to spend 30 minutes walking me through the parser code, or even collaborate on defining the grammar?

**Comment by jacqueswww** [comment]
@maurelian sure, glad to help - we can arrange a call time on gitter.

This will be a good start to define a grammer: https://github.com/python/cpython/blob/master/Parser/Python.asdl

**Comment by fubuloubu** [comment]
One approach I've been wanting to take is a conversion step from the Python AST to a Vyper-specific AST. This can be defined in a friendly way for ANTLR or the K framework.

```python
from vyper import ast
# Parses with Python ast, then Vyper ast
print('Vyper AST:', ast.parse(code))
# Prints out the grammer, perhaps in an ANTLR/K friendly format
print('Vyper AST Grammer rules:', ast.grammer)
```

**Comment by jakerockland** [comment]
Arrived here from what I've been following in #300. Curious on what the status is for the pathway to implementing this. From previous calls/conversations was the consensus on moving forward with a solution built with [Sly](https://github.com/dabeaz/sly) @fubuloubu? That's what it seemed from the convo with @charles-cooper on #300, which is the pathway I'd be in favor of as well.

**Comment by jacqueswww** [comment]
I don't think a custom parser at this point is a good idea, we can plan this for the 0.2 release. But at this stage there is plenty of other "not as flashy" issues to work on. Using the tokeniser for class isn't the most practical solution, but can be done without too much trouble. There is a reason we want to keep vyper parsable by the python ast, and that is that it will always stay firmly rooted in python.
Happy to discuss further on the next call.

**Comment by jakerockland** [comment]
@fubuloubu @jacqueswww Thank you both for all the input here! Would be great to loop back on this on the next call but definitely doesn't have to be a deep dive as there are a lot of hotter button issues that need to be resolved. Was mostly just curious what the state of this issue was 😄 👍

**Comment by charles-cooper** [comment]
A resource for researching different parser generators and tools https://wiki.python.org/moin/LanguageParsing

**Comment by charles-cooper** [comment]
Of the options in the above link, the following seem reasonably modern/maintained, and also use grammars defined as some variant of EBNF (rather than python code):
https://github.com/erikrose/parsimonious
https://github.com/lark-parser/lark/
https://github.com/neogeny/TatSu/
https://github.com/pyparsing/pyparsing/

lark, pyparsing and tatsu have pre-written python grammar examples:
[lark example](https://github.com/lark-parser/lark/blob/4e6f92b03bfef56fc83260f539d763f1dea3496e/examples/python3.lark)
[tatsu example](https://github.com/neogeny/TatSu/blob/0e8d806f51eb01ad9d78ebdde346df594238f246/examples/g2e/python.ebnf)
[pyparsing example](https://github.com/pyparsing/pyparsing/blob/ed2f5ec744ddc25242f947be8ba798d9fca6a674/examples/pythonGrammarParser.py)

**Comment by pipermerriam** [comment]
We have been using https://github.com/erikrose/parsimonious for `eth-abi` for a bit and I'm in the process of using it to define the grammar for the s-expression format of webassembly.  My experience thus far is quite positive, though I have little to compare it to. The library is quite small and simple.

**Comment by charles-cooper** [comment]
I'm kind of liking tatsu, it lets us create our VyperAST module by just annotating the grammar (https://tatsu.readthedocs.io/en/stable/mini-tutorial.html#object-models) and it has abstractions for ast traversal (https://tatsu.readthedocs.io/en/stable/mini-tutorial.html#one-rule-per-expression-type) and code generation (https://tatsu.readthedocs.io/en/stable/mini-tutorial.html#code-generation). Not sure how powerful the latter is but I can see its potential.

**Comment by fubuloubu** [comment]
Just noticed TatSu is a refactor of [Grako](https://pypi.org/project/grako/3.99.9/), so it has a LOT more pedigree than the GitHub would lead you to believe!

**Comment by fubuloubu** [comment]
Also, to summarize a discussion we had, this PR will be split into a few "stages". The stages of this VIP concerning actually replacing the use of the AST module is beyond the scope of the v0.1 release, but the early stages will prepare for this to make it as seamless as possible.

**Comment by jacqueswww** [comment]
Closing in favour of #1363.

**Comment by fubuloubu** [comment]
Can we make #1363 a VIP then? Capture the important bits of this one?

**Comment by jacqueswww** [comment]
@fubuloubu We can, but we haven't really ever had to do a VIP for internal before?

**Comment by fubuloubu** [comment]
That's true! If it doesn't change syntax, than it's just a refactor. If there are any syntax changes, we should make sure to capture those separately as VIPs so people can stay informed.
