### ISSUE TITLE
How to delete mapping?

### ISSUE THREAD

**Issue by stupidkitten** [ethereum/vyper#570]
Is there any way to delete a mapping?

For example I have the next struct:

`test: public({`
`    some_map: num256[bytes32],`
`    variable: num`
`}[num]) `

In Solidity there is `delete test[id];`
I saw the solutions like `test[id].variable = 0`

But how to clean a mapping inside a mapping? 

* viper Version: 0.0.2

**Comment by fubuloubu** [comment]
When you "delete" a mapping entry, you really just reset it to default values. Therefore a good solution would be an easier way to reset an entire struct (or other mapping member) to the default values for it's type signature using the standard syntax in Python:
```python
del test[id]
```
Although your example is an array not a mapping.

**Comment by jacqueswww** [comment]
Created https://github.com/ethereum/vyper/issues/570 that basically solves this, so closing this issue ;)
