### ISSUE TITLE
Error with make while installing. "Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1"

### ISSUE THREAD

**Issue by jamesray1** [ethereum/vyper#573]
Possibly related: https://github.com/ethereum/viper/issues/558

* viper Version: 0.0.2
* pyethereum Version: N/A
* OS: Linux 4.13
* Python Version (python --version): 3.6.3
* Environment (output of `pip freeze`):
asn1crypto==0.22.0
cryptography==1.9
duplicity==0.7.12
enum34==1.1.6
idna==2.5
ipaddress==1.0.17
keyring==10.4.0
keyrings.alt==2.2
lockfile==0.12.2
nose==1.3.7
pycrypto==2.6.1
pygobject==3.24.1
Pyste==0.9.10
pyxdg==0.25
SecretStorage==2.3.1
six==1.10.0
unity-lens-photos==1.0
vboxapi==1.0
virtualenv==15.1.0

### What's your issue about?
So while following the instructions [here](https://viper.readthedocs.io/en/latest/installing-viper.html) but using `virtualenv -p python3.6 --no-site-packages ~/viper-venv` instead of `virtualenv -p /usr/local/lib/python3.6/bin/python3 --no-site-packages ~/viper-venv` as per https://github.com/ethereum/viper/issues/558 I got an error included in the `make` output. 

```
Running scrypt-0.8.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-s1fil5fa/scrypt-0.8.0/egg-dist-tmp-r9nmeje4
scrypt-1.2.0/libcperciva/crypto/crypto_aes.c:6:10: fatal error: openssl/aes.h: No such file or directory
 #include <openssl/aes.h>
          ^~~~~~~~~~~~~~~
compilation terminated.
error: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
Makefile:4: recipe for target 'init' failed
make: *** [init] Error 1
```

I assume that to **fix this** `#include <openssl/aes.h>` needs to include the proper name of the directory that is intended to be included.

I found this: https://stackoverflow.com/questions/26077905/fatal-error-openssl-aes-h-no-such-file-or-directory#28973037.

This command (`sudo apt-get install libssl-dev1`) should probably be included in the installation instructions, or alternatively include it in the script after an assert to check if it's already installed. After running the command and running `make` again I got another error, which I've reported in a separate issue, https://github.com/ethereum/viper/issues/574, which is now resolved.

The full output of the command is available [here](https://gist.github.com/jamesray1/a906fc45fa970d3a0d28896c0437747a), as well as previous commands.

#### Cute Animal Picture
![screenshot from 2017-12-12 10-45-04](https://user-images.githubusercontent.com/16969914/33859762-8a7b8c08-df29-11e7-91fb-e9e517c4adb3.png)

**Comment by fubuloubu** [comment]
there are some packages you need to install in your distribution's package manager prior to trying to install viper, not sure if that list is fully up to date.

**Comment by jacqueswww** [comment]
@jamesray1 has this issue been resolved? If you only want the command line compiler, it's easiest to install using the snap `snap install vyper --edge`.

**Comment by jamesray1** [comment]
I think this was resolved.
