### ISSUE TITLE
"in" list doesn't check whether variable type matches the list subtype

### ISSUE THREAD

**Issue by yzhang90** [ethereum/vyper#581]
### What's your issue about?
```
@public
def testin(x: address) -> bool:
    y = 1
    s = [1, 2, 3, 4]
    if x in s:
        return True
    return False
```
This program is allowed by the Viper compiler. However the type of the varialbe `x` doesn't match the list subtype `num`.

### How can it be fixed?

Add type check in `build_in_comparator`. Pay attention to the situation when list is of MixedType.

#### Cute Animal Picture

![image](https://user-images.githubusercontent.com/5641590/33868959-c58d5758-decb-11e7-8820-abf134b6c7f2.png)

**Comment by mslipper** [comment]
@fubuloubu @DavidKnott if y'all verify this issue I can implement the fix.

**Comment by fubuloubu** [comment]
What do you mean by verify? We were talking about this in gitter, and we agree it's a problem.

**Comment by mslipper** [comment]
Oh my bad, I'll hop on Gitter. By verify I meant agree it's a problem 😄.
