### ISSUE TITLE
"in" List throws exception when list is of MixedType

### ISSUE THREAD

**Issue by yzhang90** [ethereum/vyper#582]
### What's your issue about?
```
@public
def testin(x: num) -> bool:
    y = 1
    s = [1, 2.0, 3, 4]
    if x in s:
        return True
    return False
```
The above program fails to compile due to the error "Unexpected type: '<viper.types.MixedType object at 0x7efe4e01ab70>'"

### How can it be fixed?

The list `s` is of MixedType and in `build_in_comparator`, it attempts to create a tmp list with MixedType and then fails...

#### Cute Animal Picture

![image](https://user-images.githubusercontent.com/5641590/33869229-43cb5f7e-decd-11e7-941b-452c2e0309ce.png)

**Comment by fubuloubu** [comment]
Related: #581

**Comment by jacqueswww** [comment]
@DavidKnott we can close this issue now - mixed lists/conversions are not supported anymore ;)
