### ISSUE TITLE
`as_wei_value` taking string as denomination

### ISSUE THREAD

**Issue by jonchoi** [ethereum/vyper#595]
![image](https://user-images.githubusercontent.com/9872658/34238740-efa45160-e635-11e7-82b7-237de4fd010e.png)

In the simple casper contract, we use the `as_wei_value()` helper function. I was confused about `ether` being used as a param because it looks like a variable. So I started searching for instances of this variable, just to realize that you can use `gwei` or `ether` etc as a denomination unit.

I propose we take those as strings to make it clear that they're not declared variables within the contract. (i.e. `"ether"`, `"gwei"` instead of `ether`, `gwei`)

[Denominations](http://ethdocs.org/en/latest/ether.html#denominations)
![image](https://user-images.githubusercontent.com/9872658/34238788-2f7fa014-e636-11e7-8f62-cae47040f247.png)

(Spoke with @vbuterin and @DavidKnott about this, who seem to agree)

**Comment by fubuloubu** [comment]
100% on using strings instead of keywords.

My suggestion in general for labels is to use strings, e.g. `num("ether")`

---

I think the "types are classes" solution could implement this quite easily:
```python
type wei = num("wei")
type Kwei = 1e3 * wei
type Mwei = 1e3 * Kwei # = 1e6 * wei
...
type ether = 1e3 * finney # = 1e6 * szabo = ...
```

Which you could use in contracts like so:
```python
fee: Gwei
price: ether

@payable
def buy():
    # Implicit to '("wei") > (1e18 * "wei") + (1e9 * "wei")' behind the scenes
    assert msg.value >= price + fee
    # NOTE perhaps types >wei allow decimals up to X precision (based on their multiplier)?
    ...
```

Please note this is not current syntax, just an example of something we are discussing.

**Comment by DavidKnott** [comment]
`As_we_value` Now takes a string, closing.
