### ISSUE TITLE
Disambiguating variable declaration and assignment

### ISSUE THREAD

**Issue by jonchoi** [ethereum/vyper#596]
In python, variable declaration and variable assignment look the same. For the purposes of making a safety first smart contract programming language, we may consider requiring a different syntax for explicit declaration.

For example,
This is allowed now:
```
a = 0
...
if condition:
    a = 2
```
vs
using keywords such as `var` like in Swift
```
var a = 0
if condition:
    a = 2
```
or declaring explicitly with type: (and disallowing assignment with type recasting)
```
a: num = 0
if condition:
    a = 2
``` 

For reading more complex code, this will facilitate a safer collaborative coding (and auditing) experience.

Discussed with @DavidKnott and @vbuterin. More suggestions & feedback welcome.

**Comment by yzhang90** [comment]
Please take a look at `Variable declaration and initialization` section in https://github.com/ethereum/viper/issues/545. There, we proposed that "A variable can be declared only with a statement of the form `<varname>: <type> = <initial_value>`, which also initializes it." After discussing with @fubuloubu , we think `<varname>: <type>` is also allowed and the variable will automatically be initialized to default value (zero value).

**Comment by jacqueswww** [comment]
@jonchoi since this issue was created. We have now converted to using statically defined variables. It's not `var` but I believe this serves the same purpose.  Let me know and then we can probably close this issue.

**Comment by jacqueswww** [comment]
Closing issue, we our assignments are pretty clear now :)
