### ISSUE TITLE
Taking tuples as params

### ISSUE THREAD

**Issue by jonchoi** [ethereum/vyper#602]
Right now, I understand we can return tuples like so:
`def extract_msg_from_vote(vote_msg: bytes <= 1024) -> (num, bytes32, num, num, bytes):`

But we cannot take tuples as params like so:
`def do_something_with_vote(vote: (num, bytes32, num, num, bytes)) -> bool`

While you could unpack the tuple and pass in as individual params, seems ideal to be able to take return types from methods as params of other methods.

Curious if the maintainers have thoughts on this.

And thanks @DavidKnott and @vbuterin for discussions.

**Comment by fubuloubu** [comment]
I think structs are a better candidate for this pattern, and having named struct types would be hella key to that e.g.
```python
type myStruct = {a: num, b: bool, c: bytes}
myMap: myStruct[address]

def foo() -> myStruct:
    return self.myMap[msg.sender]

def bar(s: myStruct):
    d: num = s.a
    ...
```

**Comment by jonchoi** [comment]
Definitely agree. Would love structs but given that we don't have structs yet, was suggesting an intermediate solution with an existing data structure. If we can have structs, problem solved.

**Comment by fubuloubu** [comment]
We have structs, just not named struct types. I think that is pretty key to this process.

I've been playing around with the thought of a struct-based typeclass system for building arbitrary types, but that would require a lambda or function pointer type built in to LLL, and I'm not that familar with it yet.

**Comment by jacqueswww** [comment]
Closing this in favour of: #300
