### ISSUE TITLE
Support tuple assign

### ISSUE THREAD

**Issue by jonchoi** [ethereum/vyper#605]
![image](https://user-images.githubusercontent.com/9872658/34324317-26b38c62-e8a1-11e7-889c-028b479a777b.png)

Can't return `(num, num, bytes)` without `bytes` being limited, but can't return `bytes < 1024` as part of a tuple.

This is related to the discussion on structs / tuples (https://github.com/ethereum/viper/issues/602)

**Comment by jonchoi** [comment]
Talked with @DavidKnott, this might actually be that Viper doesn't support:
```
x, y = self.returns_tuple()
```
What's the suggested pattern for doing something like this?

**Comment by DavidKnott** [comment]
@jonchoi I think it makes sense to consider adding support for:
```
x: type
y: type
x, y = self.returns_tuple()
```
Down the road

**Comment by jonchoi** [comment]
https://github.com/ethereum/vyper/issues/545
https://github.com/ethereum/vyper/issues/596

**Comment by jacqueswww** [comment]
@jonchoi at the point in time, it was decided to only support returning tuple (to stay compatible with solidity contracts that do the same).  +1 for adding support for tuple assignment (I really like it from python hehe).

**Comment by jacqueswww** [comment]
Assignment to tuple is now supported :smile:
