### ISSUE TITLE
RLPList documentation

### ISSUE THREAD

**Issue by jonchoi** [ethereum/vyper#606]
![image](https://user-images.githubusercontent.com/9872658/34324385-c2547e2c-e8a3-11e7-900e-3ded75cd2ecb.png)

**Comment by djrtwo** [comment]
You find anything on this?

**Comment by djrtwo** [comment]
Guess I'll use the source as documentation for now.
https://github.com/ethereum/vyper/blob/master/viper/functions.py#L521

**Comment by fubuloubu** [comment]
P.S. @DavidKnott can we refactor RLP with this? https://github.com/ethereum/pyrlp

**Comment by DavidKnott** [comment]
@fubuloubu We can use it for tests, our `RLPList` uses Vyper LLL to decode rlp while pyrlp uses python.

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0xbef3d6dc201b8d2f98663ec157bd88a6b2b994c9cc95f8c2c254706b2c3fcb95](https://etherscan.io/tx/0xbef3d6dc201b8d2f98663ec157bd88a6b2b994c9cc95f8c2c254706b2c3fcb95)
