### ISSUE TITLE
Bytecode with params

### ISSUE THREAD

**Issue by mattermat** [ethereum/vyper#607]
Is there a way to compile the bytecode of a contract with parameters already initialized?
It is possible to compile contracts to bytecode, but how can I do the same with the `__init__` function filled with parameters?

**Comment by fubuloubu** [comment]
I know there is a way, I can't respond to that way now. It involves encoding the deployment arguments along with the compile Bytecode.

But also you could rewrite your contract where there is no `__init__` function and it will work fine (just in case you weren't aware that it's optional). Hope that helps until you can get a more complete answer

**Comment by mattermat** [comment]
Thanks for the answer. For the use I'm thinking, I need the `__init__` function, so I have to wait for a more complete answer. I keep in mind that vyper is still in development, so no problem! In the meanwhile I'll start to study web3py package, for a wider understanding of technical details of ethereum :)

**Comment by fubuloubu** [comment]
Web3.py can handle that complexity for you. All you need is to provide the bytecode and the args when deploying using a contract handler class like [this](http://web3py.readthedocs.io/en/stable/contracts.html#web3.contract.Contract.deploy).

This method is language agnostic, since it leverages EVM bytecode and not a specific compiler like Solidity or Vyper.

**Comment by jacqueswww** [comment]
@mattermat I marked this as post beta for now.  As one can just deploy the contract and specify the init arguments on deployment. This works both in python or javascript web3 environments.

**Comment by jacqueswww** [comment]
Closing as this can be done with constants now.
```
SOME_PARAMETER: constant(uint256) = 111
```
Which solves the OP.
