### ISSUE TITLE
bash: /usr/bin/viper: No such file or directory

### ISSUE THREAD

**Issue by Karamya** [ethereum/vyper#621]
* viper Version: 0.0.2
* pyethereum Version: 2.1.3
* OS: linux
* Python Version (python --version): 3.6.1
* Environment (output of `pip freeze`):

arrow==0.10.0
asn1crypto==0.22.0
attrs==17.4.0
binaryornot==0.4.4
bumpversion==0.5.3
cffi==1.10.0
coincurve==6.0.0
conda==4.3.24
cookiecutter==1.5.1
coverage==4.4.2
cryptography==1.8.1
ethereum==2.1.3
future==0.16.0
idna==2.5
jinja2-time==0.2.0
packaging==16.8
pbkdf2==1.3
pluggy==0.6.0
poyo==0.4.1
py==1.5.2
py-ecc==1.4.2
pycosat==0.6.2
pycparser==2.17
pycryptodome==3.4.6
pyethash==0.1.27
pyOpenSSL==17.0.0
pyparsing==2.1.4
pysha3==1.0.2
pytest==3.3.1
pytest-cov==2.5.1
pytest-runner==3.0
PyYAML==3.12
repoze.lru==0.7
requests==2.14.2
rlp==0.6.0
scrypt==0.8.0
six==1.10.0
viper==0.0.2
whichcraft==0.4.1

### What's your issue about?
I followed the instructions given in https://viper.readthedocs.io/en/latest/installing-viper.html

Please include information like:

* make test works well and I get an output
617 passed in 38.34 seconds

However, when I enter the command
`viper examples/crowdfund.v.py`
I get an output
bash: /usr/bin/viper: No such file or directory

**Comment by DavidKnott** [comment]
@Karamya Are you using a python 3.6 virtual environment?

**Comment by Karamya** [comment]
yes, I am using a virtual environment with python 3.6.1
