### ISSUE TITLE
VIP: Standardize type conversions

### ISSUE THREAD

**Issue by DavidKnott** [ethereum/vyper#629]
## Preamble

    VIP: <to be assigned>
    Title: Standardize type conversions
    Author: David Knott
    Type: Standard Track
    Status: Draft
    Created: 2018-01-11

## Simple Summary
Right now Vyper type conversions are not uniform, they are performed by built in functions with different syntax:
`decimal` 
`bytes_to_num`
`as_num128` (int128
`as_num256` (uint256)

## Abstract
I propose standardizing how type conversions are performed in Viper.

## Motivation
Standardizing type conversion will simplify both the developer experience and the compiler by  decreasing the amount of build in functions.

## Specification
```
convert(input, new_typ)
decimal => convert(1, decimal) => 1.0
bytes_to_num =? convert('\x00', num) => 0
```

## Backwards Compatibility
This change won't be backwards compatible, if it's implemented it should be done in the next release.

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/)

**Comment by fubuloubu** [comment]
I like it v v much

**Comment by fubuloubu** [comment]
@jacqueswww I think this one is complete?

**Comment by jacqueswww** [comment]
Yes it is :) Marking it as done and closing the issue.
