### ISSUE TITLE
Coveralls.io Integration is broken

### ISSUE THREAD

**Issue by fubuloubu** [ethereum/vyper#636]
### What's your issue about?
Coveralls integration is broken:
[![Coverage Status](https://coveralls.io/repos/github/ethereum/vyper/badge.svg?branch=master)](https://coveralls.io/github/ethereum/vyper?branch=master)

### How can it be fixed?
I think when we moved to `vyper` we forgot to port coveralls

#### Cute Animal Picture

![panda and giraffe](https://i.pinimg.com/originals/c2/d6/bb/c2d6bbc15876a4909e331a67e8b9b1e2.jpg)

**Comment by DavidKnott** [comment]
@fubuloubu Fixed coveralls, thanks making this issue  👍. Closing.
