### ISSUE TITLE
constant function allows to call non-constant local function

### ISSUE THREAD

**Issue by yzhang90** [ethereum/vyper#638]
### What's your issue about?

```
f:num

@public
def a (x:num)->num:
    self.f = 100
    return x+5

@constant
@public
def b():
    p = self.a(10)
```
This program should be rejected since `b` is a constant function. It should not call `a` which modifies the storage.

#### Cute Animal Picture

![image](https://user-images.githubusercontent.com/5641590/35161536-24dc6a48-fd06-11e7-843d-0a1b20feea76.png)

**Comment by jacqueswww** [comment]
Good catch, as always ;) awesome picture! :)

**Comment by jacqueswww** [comment]
Starting on this ;)
