### ISSUE TITLE
VIP: Support full range of allowable Wei values

### ISSUE THREAD

**Issue by pdaian** [ethereum/vyper#653]
## Preamble

    VIP: 653
    Title: Support full range of allowable Wei values
    Author: Philip Daian, phil@linux.com
    Type: Standard Track
    Status: Draft
    Created: 2018-01-30

## Simple Summary

Currently, Vyper's `wei_value` type is defined in the compiler as of base type `num`.  This occurs in `viper/viper/types.py`:

``    'wei_value': BaseType('num', {'wei': 1}, False),``

This proposal aims to replace the `num` type with `num256`, supporting the full allowable range of wei values defined in the EVM semantics.

## Abstract

I will present an example of several behaviors of the current wei_value type and its related conversions that I believe to be unintuitive, and which may have the potential to introduce errors, and propose a potential solution.

## Motivation

Consider the following highly confusing test:

```
from viper import compiler
from ethereum.tools import tester as t
from ethereum.slogging import configure_logging

MAX_UINT256 = (2 ** 256) - 1

#configure_logging(':trace')
s = t.Chain()
s.head_state.set_balance(t.a1, MAX_UINT256 * 3)


code = """
@payable
@public
def f() -> num256: return (as_num256(msg.value))
@payable
@public
def g() -> wei_value: return (msg.value)
"""

sol_code = """
contract A{
    function f() payable returns(uint256) {
        return msg.value;
    }
}
"""

t.languages['viper'] = compiler.Compiler()

c = s.contract(code, language='viper')
c_solidity = s.contract(sol_code, language='solidity')

assert(c_solidity.f(value=MAX_UINT256, sender=t.k1) == MAX_UINT256) # this works
try:
    assert(c.f(value=MAX_UINT256, sender=t.k1) == MAX_UINT256)          # this doesn't :(
    exit(1)
except:
    print("failed as expected :(")
assert(c.f(value=int(MAX_UINT256 / 3), sender=t.k1) == int(MAX_UINT256/3))          # but this does, even though it's out of num range :O
assert(c.g(value=int(MAX_UINT256 / 3), sender=t.k1) == 0)                           # but, this returns 0 :O
```

This tests shows several issues prompting this proposal:

- Incompatibility with Solidity: Solidity can for now process higher values than Vyper, as demonstrated by the first two assertions.
- Clamp inconsistency/lack of appropriate clamp: When converting wei_value to num_256, clamp_ge is used; this clamp however only checks the sign bit of the input, and does not validate the remainder of the integer, accepting values that would otherwise raise a `ethereum.abi.ValueOutOfBounds` if encoded as the alleged base-type num through the ABI.  This violates programmer expectation.
- Unintuitive behavior in conversions: wei_values can be input as any value in the allowable 256-bit range.  When converted, wei_values can be converted to num256 if they are unsigned.  If not converted, wei_values that would otherwise fail conversion can be used, and when used as call values, will send the corresponding *positive* values; this doesn't make much sense if interpreting wei_value as signed.
- Changes break tests: The Solidity-compatible ERC20 token tests were silently broken by 827c7c5c44934511d630703ed3b8a0af11299301 .  One example affected line was here: https://github.com/ethereum/vyper/blob/master/tests/examples/tokens/ERC20_solidity_compatible/test/erc20_tests_1.py#L357 Again, this breaking change likely did not even enter the mind of reviewers/integrators due to confusion from the above.
- Semantic incompatibility: There is nothing I am aware of in the EVM semantics itself that precludes the values in question here.  If not on Ethereum, such values are certainly possible on private test networks or non-mainnet blockchain deployments.  Ideally, Vyper should behave as expected on all such blockchains.  Furthermore, such large values are useful in testing for overflow conditions, even on codebases that may never expect to encounter these conditions in practice.

## Specification

Redefine ``'wei_value': BaseType('num', {'wei': 1}, False),`` as ``'wei_value': BaseType('num256', {'wei': 1}, False),``, propagating all related clamp changes.

## Backwards Compatibility

Any normal use of wei_value on mainnet is unaffected, as the allowed balance ranges are not possible with current ETH supply.

Any values with leading bit 0 are also unaffected by this change.

Any use of wei_value not using conversion to another type is also unaffected, as wei_values are passed in directly as values in calls.

## Copyright

Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/)

**Comment by haydenadams** [comment]
This should apply to currency_value and custom unit types as well.

[`on_chain_market_maker.v.py`](https://github.com/ethereum/vyper/blob/master/examples/market_maker/on_chain_market_maker.v.py) is a good example of why this is the case.
```Python
total_eth_qty: public(wei_value)
total_token_qty: public(currency_value)
invariant: public(int128(wei * currency))
token_address: address(ERC20)

@public
@payable
def initiate(token_addr: address, token_quantity: currency_value):
    self.token_address = token_addr
    self.token_address.transferFrom(msg.sender, self, convert(token_quantity, 'uint256'))
    self.total_eth_qty = msg.value
    self.total_token_qty = token_quantity
    self.invariant = msg.value * token_quantity
```

This will fail due to overflow if funded with just 20 ETH and 20 ERC20 tokens (18 decimals).

`invariant = total_eth_qty * total_token_qty = (20*10**18) * (20*10**18) = 4E38
`
`max_int128 = 2^128 = 3.4E38
`

Using uint256 for wei_value and currency_value, and allowing the invariant to be set as 
`invariant: public(uint256(wei * currency))` would fix this and also remove the need for conversions when interacting with ERC20s:

`self.token_address.transferFrom(msg.sender, self, token_quantity)
`

looks much cleaner than

`self.token_address.transferFrom(msg.sender, self, convert(token_quantity, 'uint256'))
`
