### ISSUE TITLE
as_bytes32(address) not casting to bytes32 as expected

### ISSUE THREAD

**Issue by wski** [ethereum/vyper#661]
When trying to use the `as_bytes32(address)` followed by `slice(bytes32Address, start=0, len=5)` the compiler is complaining that the first argument is not bytes as expected `line 27: Expecting bytes for argument 1 of slice`

For example

```py
@private
def _addTag (addr: address, ign: bytes32) -> bytes32:
    return concat(ign, slice(as_bytes32(addr), start=0, len=5))
```
is throwing

```
line 26: Expecting bytes for argument 1 of slice
    return concat(ign, slice(as_bytes32(addr), start=0, len=5))
----------------------------------^
```

I'm probably missing something, I get the same error on other operators, but wanted to open an issue in the case this is a real problem.

**Edit**
I was able to get this to work by first concatenating the argument in the function then trying to slice it. 

For example this doesn't work

```py
@public
def testing (a: bytes32):
    b = slice(a, start=0, len=16)
``` 

But this does
```py
@public
def testing (a: bytes32):
    test = concat('', a)
    b = slice(test, start=0, len=16)
```

**Comment by DavidKnott** [comment]
@wski Thanks for creating an issue, currently `slice` only works with the `bytes` type and not `bytes32`.  Though I don't see why slice shouldn't work with `bytes32` as well.

**Comment by wski** [comment]
Oh that make sense since `concat` is returning bytes! Thank you @DavidKnott

**Comment by NIC619** [comment]
Any updates on `bytes32` slicing?
