### ISSUE TITLE
Add 'python_requires' to setup.py

### ISSUE THREAD

**Issue by fubuloubu** [ethereum/vyper#665]
### What's your issue about?
Should we add `python_requires` to our `setup.py`?
https://packaging.python.org/tutorials/distributing-packages/#python-requires

### How can it be fixed?
If so, it should be >`python3.6` due to our dependancy on PEP 484

**Comment by paultiplady** [comment]
PEP 484 is supported in Python3.5 as well - I had to upgrade from 3.4 to 3.5 to get it for an unrelated project. Unless there's something more specific that's 3.6-only?

https://docs.python.org/3.5/library/typing.html

**Comment by fubuloubu** [comment]
@paultiplady I think you're right, Python3.5 should work. To minimize supported versions, I think mandating 3.6 may be beneficial (at least for now). Either that, or we need to develop a framework for testing both of those on Travis

**Comment by paultiplady** [comment]
Tox is the standard way of doing that, perhaps you can crib a Travis/Tox config from an established project like Requests?

https://github.com/requests/requests/blob/master/tox.ini
https://github.com/requests/requests/blob/master/.travis.yml

Appreciate that might be more work than the MVP of only supporting 3.6 though.

**Comment by fubuloubu** [comment]
If you want to submit a PR for adding tox support for 3.5, I can get behind supporting 2 versions. They're not that much different

**Comment by jacqueswww** [comment]
Discussed, add `> 3.6` for now.
