### ISSUE TITLE
Vyper or Viper?

### ISSUE THREAD

**Issue by BenKaufman10** [ethereum/vyper#667]
I think this issue is extremely underestimate.
Even though it's just a name, it can cause many issues.
I've already noticed a few problems caused by that and I think it's time to decide.
So Vyper or Viper? (Personally I think Vyper looks better)

#### Cute Animal Picture

> 🐿

**Comment by fubuloubu** [comment]
Vyper! We've had a heck of a time transferring over, but that is almost complete! Next steps include informing the community and getting the name out there, so people will know that we had a name change.

@DavidKnott will be presenting Vyper at ETH Denver next week, that should help!

**Comment by jacqueswww** [comment]
Vyper! ;)

**Comment by BenKaufman10** [comment]
So lets make it a 100 😉

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jacqueswww** [comment]
Closing, as it's settled on Vyper ;)
