### ISSUE TITLE
Update viper.tools to vyper.tools

### ISSUE THREAD

**Issue by fubuloubu** [ethereum/vyper#670]
### What's your issue about?
Our online IDE, https:viper.tools/, references our old name and should be upgraded.

Also, that URL is referenced a bunch of places in documentation/code

### How can it be fixed?
@holgerd77 created the original website, github is [here](https://github.com/viper-online)
Not sure if this is where we get it updated, or if there's some sort of DNS update that needs to get made, but something in the setup specifies this. We could also fork this repository and put it underneath the Ethereum GitHub so it remains a public project.

Alternatively, adding Vyper to Remxi (as desribed in #529 and #278) would help us tremendously,
by reducing duplication efforts for tooling between Solidity and Vyper.

#### Cute Animal Picture
![baby viper](http://2.bp.blogspot.com/-QeWo9btA2ss/UkRiunUud9I/AAAAAAAAI58/nPzSmGZXjdA/s1600/curl+viper.jpg)

**Comment by holgerd77** [comment]
Hi, for short-term at least, I already reserved vyper.online, can do the switch next week and will also add a forwarder from the old domain for the transition period.

Adding ``Vyper`` to Remix also definitely makes sense, still not sure, if I have time to take this into my work portfolio atm - thought about this already - maybe I'm at least able to help.

**Comment by holgerd77** [comment]
Addition: also posted this on Gitter, if someone else has tooling for vyper, I'm also happy to add some DNS entries for that and integrate it in the domain above.

We can also move this domain to foundation mid-term if desired, just registered it to have it for usage.

**Comment by fubuloubu** [comment]
Awesome, thanks @holgerd77

Yeah, for long term it would be great to move to something @DavidKnott has control over, as I think you're locked to a particular release of Vyper?

Not sure how to integrate with remix, but definitely open to helping that process.

**Comment by jacqueswww** [comment]
Thanks @holgerd77

**Comment by holgerd77** [comment]
Hi, I now moved the site to https://vyper.online, and added a forwarder for http://viper.tools, also updated the API to the latest ``Vyper`` version and switched to the renamed ``vyper`` GitHub repository.

I will now let this settle a bit, will then in the upcoming days also install a script on the server which pulls the latest ``Vyper`` versions and restarts, so that the online compiler will stay up-to-date automatically without the necessity for manual updates.

**Comment by fubuloubu** [comment]
@holgerd77 thanks so much!!

**Comment by fubuloubu** [comment]
We need a PR for docs now

**Comment by holgerd77** [comment]
Ok, I've now added a script being run through cron once a day (night) which should update the ``vyper`` submodule automatically. Will have to verify in the upcoming days if this works properly.

Also submitted the PR above.

**Comment by jacqueswww** [comment]
Excellent! @holgerd77 much appreciated ;)

**Comment by jacqueswww** [comment]
All is updated and seems to run. Closing issue :smile:
