### ISSUE TITLE
Vyper in depth missing from docs sidebar

### ISSUE THREAD

**Issue by maurelian** [ethereum/vyper#672]
### What's your issue about?

Some really important parts of the docs are missing. I think previously they might have been listed under "Vyper in depth" in the sidebar. 

![image](https://user-images.githubusercontent.com/23033765/36109086-60726fbe-0fec-11e8-891d-273a40eba3a4.png)

I can still find the content I want (Types and built-in functions) by searching, but they are much harder to find if you don't know what you're looking for. 

### How can it be fixed?

Magic. 

#### Cute Animal Picture

![image](https://user-images.githubusercontent.com/23033765/36109212-bd663f16-0fec-11e8-971e-5a2a29ad217c.png)

**Comment by fubuloubu** [comment]
By this do you mean better navigation in the sidebar, or more content in the docs?

**Comment by maurelian** [comment]
Sorry, bad issue report. I mean that the content exists, but it's not listed in the sidebar.
I think it previously was. 

For example, no amount of clicking will get me to these pages: 

* http://vyper.readthedocs.io/en/latest/types.html
* http://vyper.readthedocs.io/en/latest/built-in-functions.html

**Comment by jacqueswww** [comment]
Good point, let's get them into the navbar!

**Comment by jacqueswww** [comment]
Starting on this.

**Comment by maurelian** [comment]
I still don't see them.

**Comment by jacqueswww** [comment]
@maurelian pretty sure it's in master. The site just doesn't seem to auto build one merge.

@DavidKnott do you know how I can push docs to readthedocs ?
