### ISSUE TITLE
VIP: Change number syntax

### ISSUE THREAD

**Issue by DavidKnott** [ethereum/vyper#674]
## Preamble
    VIP: <to be assigned>
    Title: Change number type syntax
    Author: David Knott
    Type: Standard Track
    Status: Draft
    Created: 2018-02-12
    Requires (*optional): <VIP number(s)>
    Replaces (*optional): <VIP number(s)>

## Simple Summary
Changing Vyper's number syntax will make Vyper types more intuitive as they'll provide more information about what's going behind the scenes.

## Abstract
Right now `num` and `num256` are confusing because `num` says nothing about the `int128` type behind it and `num256` doesn't say wether it's signed or unsigned.

## Specification
```
num => int128
num256 => uint256
```

## Backwards Compatibility
This is a breaking change though it won't effect compatibility with deployed contracts because it'll have no effect on Vyper's abi output.

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/)

**Comment by jacqueswww** [comment]
As discussed, I think we need this so there is no confusion about the underlying types. So :+1: from me - I am also here to help with the change.

**Comment by jacqueswww** [comment]
Also as we've discussed I am happy with leaving it int128 because of the straight forward way the internal decimal conversion the works :smile:

**Comment by jacqueswww** [comment]
@DavidKnott starting on this.

**Comment by jacqueswww** [comment]
@DavidKnott can be marked as done & approved now.

**Comment by jacqueswww** [comment]
Approved & Implemented :smile:
