### ISSUE TITLE
Payable should not be constant

### ISSUE THREAD

**Issue by fubuloubu** [ethereum/vyper#675]
### What's your issue about?
This compiles:
```python
@public
@constant
@payable
def get_real() -> decimal:
    return 0.0
```
I don't think `@payable` and `@constant` should be allowed to be together because changing the balance of ether of the smart contract is modifying the underlying state.

### How can it be fixed?
Add an exception if they're both present

#### Cute Animal Picture
![baby rhino](https://www.gannett-cdn.com/-mm-/2029718f4118781dc0c3283af0e2d030be823a9d/c=140-0-3371-2429&r=x404&c=534x401/local/-/media/2016/10/17/IAGroup/DesMoines/636123108878450705-RRW85964.JPG)

**Comment by fubuloubu** [comment]
So we have something in the compiler that checks for state-changing opcodes in `@constant` functions?

**Comment by maurelian** [comment]
That would be good. Ideally, constant would also use the `STATICCALL` opcode.

**Comment by maurelian** [comment]
Oh, you're right. 🤦‍♂️

**Comment by jacqueswww** [comment]
I agree we should probably prevent that ;)

**Comment by jacqueswww** [comment]
Closing as PR is merged.
