### ISSUE TITLE
Cannot convert from address to num256

### ISSUE THREAD

**Issue by lorenzb** [ethereum/vyper#680]
* vyper Version: 0.0.3 (commit 4d33dc4140f7d0c339876afb6af7b417bd0ed8e0)
* pyethereum Version: 2.3.0
* OS: osx & linux
* Python Version (python --version):
Python 3.6.3
* Environment (output of `pip freeze`):
```asn1crypto==0.24.0
attrs==17.4.0
bumpversion==0.5.3
certifi==2018.1.18
cffi==1.11.4
chardet==3.0.4
coincurve==7.1.0
coverage==4.5.1
cytoolz==0.9.0
ethereum==2.3.0
ethereum-abi-utils==0.4.7
ethereum-serpent==2.0.7
ethereum-utils==0.6.2
future==0.16.0
idna==2.6
Jinja2==2.10
MarkupSafe==1.0
numpy==1.14.0
pbkdf2==1.3
pluggy==0.6.0
py==1.5.2
py-ecc==1.4.2
pycparser==2.18
pycryptodome==3.4.11
pyethash==0.1.27
pylru==1.0.9
pysha3==1.0.2
pytest==3.4.0
pytest-cov==2.5.1
pytest-runner==4.0
PyYAML==3.12
repoze.lru==0.7
requests==2.18.4
rlp==0.6.0
scrypt==0.8.6
six==1.11.0
toolz==0.9.0
urllib3==1.22
vyper==0.0.3
web3==3.13.4
```
### What's your issue about?

The new `convert(x, 'num256')` function doesn't accept an `x` of type address.
It's possible to work around this by doing `convert(convert(my_address, 'bytes32'), 'num256')`

This seems unnecessarily cumbersome. It would be nice if a direct conversion were possible.

### How can it be fixed?

I suspect that this line is the culprit:
https://github.com/ethereum/vyper/blob/4d33dc4140f7d0c339876afb6af7b417bd0ed8e0/vyper/types/convert.py#L37

#### Cute Animal Picture
![valentine](https://i.pinimg.com/736x/8c/87/f1/8c87f181412dd85b618ffa21da105ed3.jpg)

**Comment by fubuloubu** [comment]
What use cases do you envision for this conversion?

**Comment by lorenzb** [comment]
My particular use case stores an address in an array of num256s. Other use cases I can think of involve performing any kind of arithmetic on addresses.

More importantly, the `convert(addr, 'num256')` syntax is unambiguous and the conversion is safe with no information being lost in the process. Therefore, I believe that we shouldn't forbid the programmer from performing it.

**Comment by fubuloubu** [comment]
A single address in an array of `num256`? An address is 20 bytes whereas `num256` is 32, why do you need the array? If you're storing multiple addresses in an array, you can just do so with an array of addresses.

Why would you want to arithmatic on an address?

These are not use cases that were considered when designing the address type, and I'm still not seeing the utility. It's not a matter of "can we do it?" but "why?"

**Comment by haydenadams** [comment]
@fubuloubu 

In Solidity, I've used addresses converted to integers combined with blockhash to generate pseudo-random numbers that are deterministic based on user address. I wouldn't say it should be super high priority, but it's potentially useful and something I might want to use again.

**Comment by fubuloubu** [comment]
Hmm, that's actually interesting because you can't front-run it since msg.sender is not a controllable environment variable...

Definitely a corner case, but it would be interesting to see an example of that for my own purposes.

**Comment by jacqueswww** [comment]
starting on this.
