### ISSUE TITLE
Make a release/tag on github when updated version in setup.py

### ISSUE THREAD

**Issue by djrtwo** [ethereum/vyper#681]
### What's your issue about?
Cutting a release/tag via github can be useful in certain environments when trying to specify an exact state of the codebase.

### How can it be fixed?
Release 0.0.3 via github and release future versions via github.
Add this to your release process.

#### Cute Animal Picture
![cute picture](https://s-media-cache-ak0.pinimg.com/originals/2e/4a/56/2e4a56af69d65b7b1a6f790f1a3a2599.jpg)

**Comment by karlfloersch** [comment]
@DavidKnott !!!!!!!!!

**Comment by jacqueswww** [comment]
Tagging and releasing is cool, if we have a goal to do this for ie. "stable release for beta auditing" for example. 
If someone wants a frozen part of the code base they could just use the commit hash right?

**Comment by jacqueswww** [comment]
That being said, we at some point need tagging & releasing for pypi for example so @DavidKnott: "You got the power" :stuck_out_tongue:

**Comment by djrtwo** [comment]
bump

**Comment by jacqueswww** [comment]
@djrtwo I think the best option is that we start release tags, once we mark Vyper as beta, this is hopefully soon ;) as I don't see any critical features missing (anymore).

**Comment by djrtwo** [comment]
Sooner the better! We are using it in some Casper repos and it would be
very useful. Even an alpha tag

**Comment by djrtwo** [comment]
@jacqueswww Should we close this issue or should the tag/release process make it into the readme or something?

**Comment by fubuloubu** [comment]
We should have a "how to contribute" section

**Comment by jacqueswww** [comment]
I think we can close it for now. I want to to take a simple approach for now to just tag a release every 1-1.5 months. Which hopefully means 0.0.5 will effectively be the beta.

**Comment by fubuloubu** [comment]
@jacqueswww I would disagree. Per PEP 440 (which we are following), we should at least be revved to 0.1.0 before we begin beta (maybe `0.1.0b1` to start). We have to rev the beta number for every collection of released fixes until it is fully released. We could also do a major version to start, e.g. `1.0.0b1` to make it more clear this is aiming for first major release.

Just tagging every month or so is not the correct approach, it should be tired to feature updates per PEP 440.

**Comment by fubuloubu** [comment]
:+1:
