### ISSUE TITLE
Why aren't nonce and storageRoot members of an address?

### ISSUE THREAD

**Issue by jamesray1** [ethereum/vyper#682]
## Preamble

    VIP: <to be assigned>
    Title: Make nonce and storageRoot members of the address type
    Author: James
    Type: Standard Track
    Status: Draft
    Created: 2017-02-16

## Simple Summary
According to [here](https://viper.readthedocs.io/en/latest/types.html?highlight=types#members) nonce and storageSize are not members of the address type. However, it would be useful if they were.

## Abstract
A short description of the technical issue being addressed.

## Motivation
The motivation is critical for VIPs that add or change Vyper's functionality. It should clearly explain why the existing Vyper functionality is inadequate to address the problem that the VIP solves as well as how the VIP is in line with Vyper's goals and design philosopy.

## Specification
The technical specification should describe the syntax and semantics of any new feature. The specification should be detailed enough to allow any developer to implement the functionality

## Backwards Compatibility
All VIPs that introduce backwards incompatibilities must include a section describing these incompatibilities and their severity. The VIP must explain how the author proposes to deal with these incompatibilities.

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/)

**Comment by jacqueswww** [comment]
@jamesray1 I don't believe this information is available on the EVM. So we can't really add it . I could find any opcodes to retrieve this information, the CREATE opcode only returns the address of a new contract onces it's been created. The key derivation occurs within the ethereum client itself.

**Comment by fubuloubu** [comment]
Confirmed neither are available in solidity either.

**Comment by jamesray1** [comment]
Makes sense, although disappointing.

**Comment by jamesray1** [comment]
I wanted to have this to write code for EIP https://github.com/ethereum/EIPs/pull/887

**Comment by jacqueswww** [comment]
Closing as this can not be implemented.
