### ISSUE TITLE
Rename event keyword

### ISSUE THREAD

**Issue by jacqueswww** [ethereum/vyper#695]
This is the suggested template for new VIPs.

## Preamble

    VIP: 695
    Title: Rename dunder log define function to event.
    Author: Jacques Wagener 
    Type: Standard Track 
    Status: Draft
    Created: 2018-03-08
   
## Simple Summary

Rename `__log__` keyword on definition of a event to `event` keyword instead.

## Motivation
As a few users have pointed out, the `__log__` keyword in defining an event is not as clear as using `event({arg1: int128})` style defintions.

## Specification
```
MyLog: __log__({arg1: indexed(bytes <= 3)})
```
Becomes
```
MyLog: event({arg1: indexed(bytes <= 3)})
```
The emitting of a log event will remain the same:
```
log.MyLog("123")
```

## Backwards Compatibility
This is not backward compatible (full rename).

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/)

**Comment by fubuloubu** [comment]
Note: the syntax for "emitting"/logging an event is still `log.MyLog('arg')`

**Comment by jacqueswww** [comment]
Yes I feel the event / log keyword combination will work well.

**Comment by fubuloubu** [comment]
(put it in the issue lol)

**Comment by BenKaufman10** [comment]
Hey, I think we can close this issue now.
