### ISSUE TITLE
Fix convert for nulls in a bytearray

### ISSUE THREAD

**Issue by jacqueswww** [ethereum/vyper#705]
### What's your issue about?
There seems to be a strange scenario where parsing a zero byte string cause convert to fail.

```python
@public
def zero_bytes(inp: bytes <= 1) -> int128:
    return convert(inp, 'int128')
```
Test case
```python
    assert c.zero_bytes(b'\x01') == 1
    assert c.zero_bytes(b'\x00') == 0
```

See https://github.com/ethereum/vyper/pull/696 for more details.

### How can it be fixed?

Busy investigating

#### Cute Animal Picture
![](https://img.purch.com/w/660/aHR0cDovL3d3dy5saXZlc2NpZW5jZS5jb20vaW1hZ2VzL2kvMDAwLzAyNC8xODgvb3JpZ2luYWwvc2xlZXBpbmcta2l0dGVuLmpwZw==)

**Comment by jacqueswww** [comment]
I have investigated this, and it seems we purposefully don't allow leading zero byte arrays:

```
              /* bytearray to number, verify no leading zbytes */ 
              [with,
                _sub,
                352 <inp>,
                [with,
                  _el1,
                  [mload, [add, 32, _sub]],
                  [with,
                    _len,
                    [clamp, 0, [mload, _sub], 32],
                    [seq,
                      [assert, [or, [iszero, _len], [div, _el1, [exp, 256, 31]]]],
                      [clamp, [mload, 96], [div, _el1, [exp, 256, [sub, 32, _len]]], [mload, 64]]]]]]],
```

**Comment by fubuloubu** [comment]
@DavidKnott @vbuterin do you guys know why?

**Comment by jacqueswww** [comment]
I am going to remove the restriction for now, as there are definitely use cases where this is necessary - ie. slicing bytes from a longer bytearray.
