### ISSUE TITLE
ERC20 decimals is not public

### ISSUE THREAD

**Issue by BenKaufman10** [ethereum/vyper#708]
### What's your issue about?
Is there any reason in the ERC20 standard in Vyper the ``decimals`` is not public?
Like here: https://github.com/ethereum/vyper/blob/master/examples/tokens/ERC20.v.py
In line 17 ``decimals: int128`` is not public.
Also decimals is not accessible from the premade ERC20 contract.
However, in the vypercoin implementation the decimals is public.
If there is no reason for that I will add it to the code and submit a PR.

### How can it be fixed?

``decimals: public(int128)``
And adding it to the premade contract as well.

#### Cute Animal Picture
![image](https://user-images.githubusercontent.com/10667901/37700397-09d31d6e-2cf4-11e8-8da5-8aa233bbbf49.png)

**Comment by jacqueswww** [comment]
Agreed, these should be added as they seem to be part of the standard.
