### ISSUE TITLE
VIP: Change bytes length notation

### ISSUE THREAD

**Issue by jacqueswww** [ethereum/vyper#714]
## Preamble

    VIP: 714
    Title: Change bytes length notation
    Author: Jacques Wagener
    Type: Standard Track
    Status: Draft
    Created: 2018-03-22

## Simple Summary
Change the bytes decleration syntax to resemble a lists' syntax.

## Abstract
Change the byte length syntax on declaring a bytearray.

## Motivation
The motivation is critical for VIPs that add or change Vyper's functionality. It should clearly explain why the existing Vyper functionality is inadequate to address the problem that the VIP solves as well as how the VIP is in line with Vyper's goals and design philosopy.

## Specification
Currently bytearray size are set using the the smaller-than-or-equal operator `<=`. This VIP will replace it to use the square bracket to indicated the byte size.
From
```python
abytearray: bytes <= 3
```
To
```python
a: bytes[3]
```

This makes it slightly more readable and standardised - because list lengths use the same square bracket subscript notation e.g.

```python
alist: int128[7]
```

## Backwards Compatibility
Not backwards compatible. Fully override the old style.

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/)

**Comment by fubuloubu** [comment]
I'm on board!

**Comment by fubuloubu** [comment]
One thing to consider: mappings

`a: bytes[4][address]` and `b: int128[bytes[3]]`

Does that look okay? I think it does

**Comment by jacqueswww** [comment]
@fubuloubu I think it does. But I want this VIP and https://github.com/ethereum/vyper/issues/564 and to happen before we go beta.

From my side it's the last 2 big changes before, I am happy with the syntax to go beta.
