### ISSUE TITLE
Need support for integer division in Vyper

### ISSUE THREAD

**Issue by yzhang90** [ethereum/vyper#716]
### What's your issue about?

I noticed that a recent change Vyper where `/` returns `decimal` instead of `int128`. However, if a developer do want to use integer division (int128 // int128), he/she has to use `floor` to do the conversion. However, this conversion can potentially waste gas because '/' will first multiply DECIMAL_DIVISOR and `floor` will divide DECIMAL_DIVISOR. On the other hand, EVM opcode `DIV` performs the integer division. 

### How can it be fixed?

Introduce operator `//` for integer division and it can be directly translated to DIV opcode in EVM.

#### Cute Animal Picture

![image](https://user-images.githubusercontent.com/5641590/37781506-d56b3acc-2dbe-11e8-9e06-be4edc25e3b3.png)

**Comment by fubuloubu** [comment]
Potential solution: add optimization that `int128 = floor(int128/int128)` should use `DIV` opcode directly instead of more complex math, e.g. catch and remove clamp in that limited circumstance in our optimization module

**Comment by jacqueswww** [comment]
@fubuloubu yes, was thinking the same, the only problem comes when it's a nested expression.

**Comment by fubuloubu** [comment]
That's why optimization is the right solution. If it's not simple to figure out, don't do the optimization! Positive confirmation.

**Comment by yzhang90** [comment]
@fubuloubu why not use `//` to replace `floor(int128/int128)` instead of optimizing `floor` function?

**Comment by fubuloubu** [comment]
Because from an auditabile you perspective, it may be easy to miss that extra `/` and misunderstand what the command is doing. That was our concern with `//`.

Vyper is ease of audit, not ease of writability.

**Comment by daniel-jozsef** [comment]
I think decimal numbers in a smart contract are a luxury. Ethereum is integer-based, and 99% of all use cases ever call for integers, not decimals.

I think the best solution would be to disallow integers and decimals to co-mingle.

decimal / decimal = decimal (decimal division)
integer / integer = integer (integer division)
decimal / integer = ERROR
integer / decimal = ERROR

**Comment by fubuloubu** [comment]
You know, this is probably a stronger and simpler approach. It makes auditability the main goal, and it would be simpler to describe. No implict conversions at all.

What difficulties exist with this approach?

**Comment by daniel-jozsef** [comment]
I don't see any issue beyond code becoming more verbose (which, for Vyper, is more a requirement than a problem). Existing code not compiling after the change should not be an issue since Vyper is still in alpha.

**Comment by fubuloubu** [comment]
Sounds good to me!

**Comment by jacqueswww** [comment]
Please just format as VIP, thanks ;)
