### ISSUE TITLE
Signed256 should be int256

### ISSUE THREAD

**Issue by BenKaufman10** [ethereum/vyper#720]
Currently the syntax for signed integer is ``int128`` for the 128 version and ``signed256`` for the 256 version. I think this is a bad syntax, as they both represent signed integer. I think we should go with one syntax and as this is the standard in Solidity (and also most commonly used in Vyper) I believe we should change ``signed256`` to ``int256``. 

### How can it be fixed?
Change ``signed256`` to ``int256``.

#### Cute Animal Picture

![image](https://user-images.githubusercontent.com/10667901/37846599-248f03ba-2edf-11e8-82da-93052e794dd2.png)

**Comment by fubuloubu** [comment]
`signed256` should be unsupported syntax. I agree if we had a typed, it should be `int256`

@jacqueswww, you know what's up with this?

**Comment by BenKaufman10** [comment]
As I understood from @jacqueswww the signed256 is needed for Solidity compatibility.
I don’t think it’s widely use in Solidity but we should at least leave an option just in case.

**Comment by jacqueswww** [comment]
Yes I believe it's here for compatibilit and will probably be extended some more if required (probably just to be converted). But renaming it to the right convention for now seem good.

**Comment by daniel-jozsef** [comment]
Is there an actual use case for this specific piece of Solidity compatibility in the first place? The last thing I want to see is Solidity's messed up menagerie of types to crawl their way over into Vyper in the name of compatibility.

If there is a real world use case of contract interop needing a signed 256 bit type (or any other new types), I'd mark it with a compiler warning of being "deprecated" or "unsupported" or "discouraged" or something similar. Maybe throw an error unless a compiler flag (say, --enable-compat-types) is explicitly given!

As for the name itself, int256 sounds like the right choice, but it comes with readability risks, as it's confusable with uint256 by someone unfamiliar with Vyper.

**Comment by jacqueswww** [comment]
@daniel-jozsef I completely agree. I think we should proceed with the renaming, and we will not do any additional effort - there is nothing useful you can do with in256 at this stage.
