### ISSUE TITLE
The latest docs changes have not been uploaded to http://vyper.readthedocs.io.

### ISSUE THREAD

**Issue by jamesray1** [ethereum/vyper#725]
https://github.com/ethereum/vyper/blob/master/docs/logging.rst has not been uploaded to http://vyper.readthedocs.io/en/latest/vyper-by-example.html.

**Comment by BenKaufman10** [comment]
It's not just the logging, no docs update was uploaded to the docs site.
This includes the update for the compatibility breaking changelog which is extremely important.

**Comment by jacqueswww** [comment]
We already have ticket for this, closing. https://github.com/ethereum/vyper/issues/416
