### ISSUE TITLE
VIP: Change binary literal format

### ISSUE THREAD

**Issue by jamesray1** [ethereum/vyper#732]
This is the suggested template for new VIPs.

## Preamble

    VIP: 732
    Title: Change binary literal format 
    Author: jamesray1
    Type: Standard Track
    Status: Draft
    Created: 2018-03-30
    
## Simple Summary
Change the byte string literal format type to use python's `0b` format.

## Abstract
Change bytes variable assignment from `someBytes = "00010110"` to `someBytes = 0b00010110` and also support hexadecimal format and octal format, but not decimal format.

## Motivation
Python has a know literal type for representing bytes, it stands to reason to use it.
```
>>> a = 0b111
>>> a
7
```

## Specification
Before:
```
someBytes: bytes[1] = "00010110"
```
After:
```
someBytes: bytes[1] = 0b00010110
```

## Backwards Compatibility
Not backwards compatible.

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/)

**Comment by fubuloubu** [comment]
In favor
