### ISSUE TITLE
Errors don't tell me where they occur, e.g.: Typecasting from base type int128(wei) to int128 unavailable

### ISSUE THREAD

**Issue by jamesray1** [ethereum/vyper#734]
To find the error I have to cut half of the program and see if the error disappears, or not, and if not, cut the other half, and so on, until I find the error.

**Comment by jacqueswww** [comment]
@jamesray1 could you please add an example that trigger the exception you are talking about, thanks.

**Comment by fubuloubu** [comment]
@jamesray1 does that mean this issue is no longer a problem?

**Comment by jamesray1** [comment]
No I fixed the error and the SMC compiles now, but I had a few errors where it didn't give a line number. I want to see line numbers where errors occur, the error-causing code copied in, arrows, and descriptions/explanations, etc. Rust's error system is great.

**Comment by jacqueswww** [comment]
@jamesray1 please provide clear snippets we can replicate and thus fix it effectively, thanks.
