### ISSUE TITLE
Remove dependency on pyethereum

### ISSUE THREAD

**Issue by ChihChengLiang** [ethereum/vyper#735]
### What's your issue about?

This is a blocker for pyethereum Casper branch.

Vyper depends on [pyethereum 2.1.3](https://github.com/ethereum/vyper/blob/master/setup.py#L26), this introduces errors to the installation.

```
error: ethereum 2.1.0 is installed but ethereum==2.1.3 is required by {'vyper'}
```

### How can it be fixed?

Move pyethereum to dev_requirements.txt.

The pyethereum is mainly imported in two places of the codebase. Mostly it is imported in `scripts/`, removing it should not affect the functionality of the package. It is also imported in [parser_utils](https://github.com/ethereum/vyper/blob/master/vyper/parser/parser_utils.py#L3), which should be replaceable with constants in `vyper/opcodes`

#### Cute Animal Picture

![](https://i.imgur.com/EYuLW94.gif)

**Comment by fubuloubu** [comment]
We can probably pull the opcodes from `py-evm`

**Comment by ChihChengLiang** [comment]
Thanks for the feedbacks @jacqueswww @fubuloubu . I made pull request https://github.com/ethereum/vyper/pull/741 which pyethereum is removed from installation and constants are added from `py-evm`. it is ready for review now.
