### ISSUE TITLE
Disallow implicit conversion during comparison

### ISSUE THREAD

**Issue by yzhang90** [ethereum/vyper#737]
### What's your issue about?
Vyper will do implicit conversion during comparison (i.e., `int128` to `decimal` if one of the argument is `int128` and the other is `decimal`).  However, this behavior would cause [problems](https://github.com/ethereum/casper/issues/67). It is better to only allow strict comparison. The developer should explicitly convert the arguments and make sure that the two arguments are of the same type.

### How can it be fixed?
Remove the implicit conversion logic in the `compare` method in `expr.py`.

#### Cute Animal Picture

![image](https://user-images.githubusercontent.com/5641590/38141628-ab3f8b5e-33fe-11e8-999c-46ac6ff41238.png)

**Comment by fubuloubu** [comment]
Agreed

**Comment by jacqueswww** [comment]
Merge with https://github.com/ethereum/vyper/issues/716, as a VIP ;)

**Comment by jacqueswww** [comment]
@yzhang90 I am busy implementing this now, does this mean - we only need to make explicit conversion necessary for comparison ? Other arithmetic can still use implicit conversion?

**Comment by fubuloubu** [comment]
I think the overall strategy was to disallow implicit conversions between different integer types, except with literals.

**Comment by yzhang90** [comment]
Working on the VIP. sorry for the delay. Should be able to finish it by this afternoon.
