### ISSUE TITLE
Vyper doesn't allow function overloading

### ISSUE THREAD

**Issue by BenKaufman10** [ethereum/vyper#738]
### What's your issue about?
I tried implementing the ERC827 proposed standard using Vyper but when I tried to implement the new version for transfer presented in it I encountered this error: 
``Duplicate function or event name: transfer`` even though the parameters were different. It also happens even if the return type is different. I think it's a bug but if it was done intentionally I think we should change it since overloading is very useful and will probably become a part of more standards which in the end Vyper will have to support.

#### Cute Animal Picture

![image](https://user-images.githubusercontent.com/10667901/38142101-c46f78d8-3443-11e8-958c-d02e09ddb04f.png)

**Comment by jacqueswww** [comment]
This is against one of the core principles of vyper, and I personally don't think it should ever be done in a contract. It's a bit dissapointing that this happens in a proposed standard. Perhaps we should mention this on the EIP. Especially because using something so specific in standard really messes with future implementations.

**Comment by jacqueswww** [comment]
The vyper version of this contract the contract writer would just have to implement the second transfer function.

**Comment by BenKaufman10** [comment]
Thanks, so I believe this must be specified in the main page of the docs in the section of features Vyper does not support. Currently it only has "Operator overloading: Operator overloading makes writing misleading code possible.". This is extremely misleading as it talks on a specific overloading, that can (and did) make people think regular function overloading is fine.
I will update the docs and comment on the ERC proposal.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jacqueswww** [comment]
We can consider this, but I really think it causes a lot ambiguity. @fubuloubu what do you think?

**Comment by BenKaufman10** [comment]
Personally I don't think it really matters, but maybe we should stay on the safe side to minimize the chances for a problem to occur. Thinking about that overloading might make the code harder to search through so maybe it's better to keep it banned.

**Comment by jacqueswww** [comment]
The biggest problem I have with function overloading, if for a general programming use case. Is that it's super easy to miss which function is actually called. Secondly overloaded functions tend to have different outcomes. As per above example the overloaded one has big consequences as it does an additional call, and therefore the actual outcome can easily mistaken.

**Comment by jacqueswww** [comment]
As a side note, I am very opinionated on these matters (I have often thought about these), and don't want this to discourage others from opening these type of issues ;) I think it's great we are discussing these - this way we have a record for other people to refer to as to why we made these type of decisions  :smile:

**Comment by daniel-jozsef** [comment]
Yep, it's not Vyper that is wrong, it's ERC-827. Those calls should have different names.

**Comment by fubuloubu** [comment]
Agree with @jacueswww and @daniel-jozef

**Comment by jacqueswww** [comment]
Closing and marked as question.

**Comment by fulldecent** [comment]
For documentation purposes, I want to note that the official justification has been added to: https://github.com/ethereum/vyper/blob/master/README.md

> This can cause lots of confusion on which function is called at any given time. Thus it's easier to write missleading code (foo("hello") logs "hello" but foo("hello", "world") steals you funds). Another problem with function overloading is that it makes the code much harder to search through as you have to keep track on which call refers to which function.

---

Function overloading makes code EASIER to search through in the case that the API designer has appropriately named functions. But for obfuscated cases (programmer versus person reading code), then you still need to read all the code anyway.
