### ISSUE TITLE
True False or true false

### ISSUE THREAD

**Issue by BenKaufman10** [ethereum/vyper#742]
Currently, Vyper supports 2 ways to declare true/ false values. One is the python syntax ``True``, ``False``, and one which Vyper compiler explicitly support ``true``, ``false``.
This is a bit confusing on what should be used, what do you think the correct syntax should be?
Do you think the other syntax should be disabled?

#### Cute Animal Picture
![image](https://user-images.githubusercontent.com/10667901/38170064-7007ea40-3584-11e8-86c6-faa741d79a7b.png)

**Comment by fubuloubu** [comment]
@jacqueswww I'm thinking we disallow the lowercase versions. Do you know why they're allowing as syntax?

**Comment by jacqueswww** [comment]
Should only be 'True'.

**Comment by BenKaufman10** [comment]
The weird thing is that the lowercased one is explicitly specified by the compiler and widely used in the source code. Do you think there is a special reason for that or we can just remove it?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by daniel-jozsef** [comment]
I'd say sticking to the Pythonic keywords should be good.

One thing to note, lowercase true and false, if not compiler reserved, then could be used to write underhanded code... (reader thinks it's a literal, but it's a variable)

I think lowercase true and false should be unused reserved words. This way we don't get the ambiguity of two distinct sets of boolean literals, and also avoid someone naming a variable "true".

**Comment by denis-bogdanas** [comment]
Same goes with None/null.

**Comment by jacqueswww** [comment]
@daniel-jozsef Yes I agree, the plan is to leave true and false as reserved keywords.

I am thinking of making a banned keyword list in the compiler, what this would do is not allow any case of form some keywords such as "tRue" / "FalsE" etc. :smile_cat:

**Comment by daniel-jozsef** [comment]
Probably, all reserved words should be reserved case-insensitively, but only accepted by the compiler with correct case.

**Comment by jacqueswww** [comment]
@daniel-jozsef I just tested, we are safe no mixed case reserved variable names ;)
