### ISSUE TITLE
Sharding opcodes

### ISSUE THREAD

**Issue by tpmccallum** [ethereum/vyper#745]
Sharding opcode[s] like 0xf5 (PAYGAS), in accordance with pull request 651 [1] don’t seem to be in the opcodes.py file in the master branch.

I have also noticed that the sharding [2] and stable [3] branches are returning a 404.

Wanting to completely understand how Vyper will implement sharding opcodes. The more info the better. Thank you!

[1] https://github.com/ethereum/vyper/pull/651/files
[2] https://github.com/ethereum/vyper/blob/sharding/vyper/opcodes.py
[3] https://github.com/ethereum/vyper/blob/stable/vyper/opcodes.py

**Comment by jacqueswww** [comment]
Hey @tpmccallum ! The sharding branch should have the above opcodes, I looked up this link: https://raw.githubusercontent.com/ethereum/vyper/sharding/viper/opcodes.py

Would you like me to merge 0.0.4 tag into the sharding branch?

**Comment by tpmccallum** [comment]
Hi @jacqueswww !
This is a good question, I don’t see the sharding opcodes mentioned in the yellow paper [1]. Also having trouble locating these opcodes (for sharding implementation) in other languages (such as Solidity). Is @DavidKnott perhaps a few steps ahead of what is available in the available documentation?

Ultimately it would be great to compare and contrast sharding implementation between Solidity and Vyper at this stage (which I would research and then write up [2]).
If you could provide URLs to help me better understand and/or send me off on a research journey I would really appreciate the help.
Thank you

[1] https://ethereum.github.io/yellowpaper/paper.pdf
[2] https://github.com/ethereumbook/ethereumbook/pull/381

**Comment by NIC619** [comment]
Hi @tpmccallum !
Since it's still an early stage in Sharding, there are various designs and experiments underway(mostly happened in https://github.com/ethereum/py-evm) including these opcodes.

Vyper team kindly helps us with the Sharding opcodes we had in mind for testing. You can find some basic documentations through posts in ethresearch forum(e.g, https://ethresear.ch/t/tradeoffs-in-account-abstraction-proposals/263) or implementations in py-evm(e.g, https://github.com/ethereum/py-evm/issues/190).
Sorry for the inconvenience!

**Comment by jacqueswww** [comment]
@NIC619 thanks for answering ;) let me know if you guys need me to update the sharding branch to the 0.0.4 tag (I am quite quick to respond if you ping me on gitter).

**Comment by tpmccallum** [comment]
Hi 
Hey @NIC619 thank you so much for those URLs. Much appreciated.
@jacqueswww I think I have enough information for what I was trying to achieve (writing about the upcoming developments of Vyper and Ethereum). Thank you both so much for your quick and informative answers!
I will keep in touch. I am following the development of Vyper closely, congratulations on all of your hard work. Brilliant!!!
Kind regards
Tim

**Comment by jacqueswww** [comment]
@tpmccallum no problem, please shout if you have any questions - keep up the good work, looking forward to reading *ethereumbook* ! :smile_cat:
