### ISSUE TITLE
VIP: remove casting in signature

### ISSUE THREAD

**Issue by denis-bogdanas** [ethereum/vyper#749]
## Preamble

    VIP: 749
    Title: Remove casting in signature feature
    Author: Denis Bogdanas
    Type: Standard Track
    Status: Draft
    Created: 2018-04-03

## Simple Summary
Remove the ability to cast `uint256` to `int128` in function signature.

## Abstract
Casting in signature:
https://github.com/ethereum/vyper/blob/3eb961ecccb8ced76f19217843bb9ee88f6f8750/tests/parser/types/numbers/test_num256.py#L130

can be completely replaced with plain conversion to `int128`.

## Motivation
Looks like a language redundancy that can be removed. The only diff is that `convert()` also performs a clamp, and requires defining a new variable. None of these should be issues.

## Specification
Replace casting in signature with `convert(x, "int128")` inside function.

## Backwards Compatibility
Casting instances should be replaced.

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/)

**Comment by fubuloubu** [comment]
I 100% agree. This is not a great feature for auditability and should be removed

**Comment by jacqueswww** [comment]
:+1: since uint256 is way more compatible. I vote we remove it before alpha?

**Comment by ben-kaufman** [comment]
Agree. Just add it to the final countdown so we can track it.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jacqueswww** [comment]
New project "fix the beta" :smile:

**Comment by ben-kaufman** [comment]
Oh yeah I see, awesome!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
