### ISSUE TITLE
VIP: Allow declaring custom units

### ISSUE THREAD

**Issue by ben-kaufman** [ethereum/vyper#752]
## Preamble

    VIP: 752
    Title: Allow declaring custom units
    Author: Ben Kaufman ben.kaufman10@gmail.com
    Type: Standard Track
    Status: Draft
    Created: 2018-04-03

## Simple Summary
Add a new keyword ``unit`` to allow declaring custom units like so:

## Abstract
Adding a way to create custom units can make the code more readable and improve security (type-safety).

## Motivation
The motivation for this came as I saw that the Casper contract uses labels incorrectly. they use the ``m`` which stands for meter where they clearly didn't meant to represent meters. This make the code very confusing and might be a bigger issue in the future.
Currently, there are a few units Vyper support, but there are much more measurements Vyper doesn't take in count. For example, in the company.v.py the stocks are labeled as ``currency`` while it actually should be a ``stock``.

## Specification
The proposed ``unit`` declaration is as below:
```
stock: unit
stocks_count: int128(stock)
wei_per_stock: int128(wei / stock)
```
However, it may be declared in a different way such as with a dedicated function.

## Backwards Compatibility
This change is backward compatible

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/)

#### Cute Animal Picture

![image](https://user-images.githubusercontent.com/10667901/38243786-4ce270da-3741-11e8-9ac9-e00a1c8d90b7.png)

**Comment by jacqueswww** [comment]
I think this a decent idea. Perhaps we should consider sometype of predefined unit table ? 
Something like (don't worry about the syntax for now, but just the idea):
```python
units = (
    ('m', 'meter'),
    ('cm', 'centimeter')
)
```
This would force a description on each unit used in the contract.

**Comment by BenKaufman10** [comment]
Sounds good, I think it will be better. I will update the VIP in accordance with a syntax for that. I will also add it to the list of subjects for the next meeting.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by fubuloubu** [comment]
I wamted the unit labels to be double quoted so it's obvious that those are labels and not types or variables

**Comment by fubuloubu** [comment]
Example:
```python
stocks_count: int128("stock")
wei_per_stock: int128("wei" / "stock")
```

I don't think we need an extra syntax to declare a unit, if you made a spelling mistake it will tell you when you compile, because that's the whole point of units.

**Comment by fubuloubu** [comment]
Hmm, a hybrid of the two?

```python
units = (
    ("stock", "one ownership share"),
    # "wei" comes for free (built-in)
)
stocks_count: int128("stock")
wei_per_stock: int128("wei" / "stock")
```

**Comment by fubuloubu** [comment]
If there's ever a misspelling it could find it at the front because it won't exist in the table

**Comment by jacqueswww** [comment]
On that note, we definitely need the built-in units to be listed in the documentation under 'Types/Unit Types'.

**Comment by fubuloubu** [comment]
Idea is that each file extends the base units for itself

**Comment by BenKaufman10** [comment]
The second syntax looks good IMO.
Just wondering, maybe the ``unit`` should be ``vyper.units`` or ``__units__`` to make it more notable. What do you think?


<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by fubuloubu** [comment]
I'm not opposed to `__units__`...

**Comment by jacqueswww** [comment]
Approved, we should only allow basically one layer deep operator (divide/multiply/exponential). 

```
units: {
     stock: "one share",
     m: "meter",
 }
```

**Comment by ben-kaufman** [comment]
Closing as it's implemented. Great work!
