### ISSUE TITLE
Integrate Status OpenBounty

### ISSUE THREAD

**Issue by jacqueswww** [ethereum/vyper#754]
### What's your issue about?

Status (https://github.com/status-im), has offered to support Vyper by means of SNT bounties, to issue these bounties we need to integrate Status OpenBounty (https://openbounty.status.im/).

The bounties will mainly be issued for:

- Logo Competition
- Documentation and tutorials

### How can it be fixed?

- [x] Create bounty label 
- [ ] Install openbounty app on vyper repository (https://openbounty.status.im/).

#### Details on app installation:

Set a your payout address (https://wiki.status.im/Status_Open_Bounty#For_Developers) - after clicking Login (registers your username on openbounty)  on https://openbounty.status.im/.

One of the repository owners need to visit https://github.com/apps/status-open-bounty-app, click install then select 'Only select repositories' and then select 'ethereum/vyper'.

Once the repository has been installed the openbounty will monitor issues for the 'bounty' label, and issue bounties on the issue.

#### Cute Animal Picture
![](https://i.ytimg.com/vi/2Q-KGJSlYVc/hqdefault.jpg)

**Comment by pipermerriam** [comment]
@jpitts is this something you have the permissions to do, or feel free to grant me the necessary permissions if you're into that.

**Comment by jpitts** [comment]
Yes, I can do this. I have installed status-open-bounty-app in the ethereum/vyper repo...

**Comment by fubuloubu** [comment]
@jpitts thanks!

**Comment by jacqueswww** [comment]
@jpitts Sorry to bother again, but I seem to have directed you wrongly.

Please register yourself by clicking 'Login' on https://openbounty.status.im/ and set an ETH address under "My payment details" (Apparently the app requires a valid openbounty user with set address to start scanning issues).
Thereafter reinstall the github app on the repository again https://github.com/apps/status-open-bounty-app.

Thanks so much!

**Comment by fubuloubu** [comment]
@jpitts @pipermerriam can one of you attend the meeting tomorrow (#788) so we can chat about this and finish this up?

**Comment by ben-kaufman** [comment]
@jacqueswww I think we can close this.

**Comment by jacqueswww** [comment]
Yup, thabks for the help @jpitts!
