### ISSUE TITLE
ValueError: bytes must be in range(0, 256) when working with large byte arrays

### ISSUE THREAD

**Issue by SamuelTroper** [ethereum/vyper#777]
* vyper Version: 0.0.4
* OS: linux
* Python Version (python --version): 3.6.3

### What's your issue about?

Hi, I'm experimenting with storing (relatively, for Ethereum) large zip files. I read in the zip file using python in rb and output that into a vyper file, which I then compile afterwards. I have no issue generating the ABI, but when I compile the bytecode I receive a `ValueError: bytes must be in range(0, 256)`.  I've included a sample Vyper output, as well as the Python method I use to generate it as well.

I suspect there may be some issue with the larger sizes behind all this, as I tend to get this issue on larger zip files rather than smaller ones. It is also consistent, with the same files generating the error and ones that don't simply do not. To be clear, this code seems to work with smaller zip files but not larger ones. I've also done some troubleshooting which involved Python checking each byte in the file to ensure it is under 256, which it did successfully verify.

Command Run:

`vyper 18208-8.v.py > output.v.py.byte`

Python generator code:
```
def generateVyperFile(fileName, filePath, directory):
    zipBits = None
    with open(os.path.join(filePath, fileName), 'rb') as readFile:
        zipBits = readFile.read()

    #Generate the vyper file:
    vyperFileString = '''
listingAddress: public(address)
zipBytes: public(bytes[''' + str(len(zipBits)) + '''])

@public
def __init__(_listingAddress: address):
    self.listingAddress = _listingAddress

    self.zipBytes = ''' + str(zipBits)[1:]
                                           
    with open(directory + fileName[:-4] + '.v.py', 'w') as writeFile:
        writeFile.write(vyperFileString)

```

Sample Vyper Code:

```
listingAddress: public(address)
zipBytes: public(bytes[94629])

@public
def __init__(_listingAddress: address):
     self.listingAddress = _listingAddress
     self.zipBytes = 'PK\x03\x04\x14\x00\x00\x00\x08\x00\x8b[remaining bytes removed for readability]'
```

Full output:

```
Traceback (most recent call last):
  File "/home/troper/vyper-venv/bin/vyper", line 4, in <module>
    __import__('pkg_resources').run_script('vyper==0.0.4', 'vyper')
  File "/home/troper/vyper-venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 739, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/troper/vyper-venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1501, in run_script
    exec(script_code, namespace, namespace)
  File "/home/troper/vyper-venv/lib/python3.6/site-packages/vyper-0.0.4-py3.6.egg/EGG-INFO/scripts/vyper", line 31, in <module>
  File "/home/troper/vyper-venv/lib/python3.6/site-packages/vyper-0.0.4-py3.6.egg/vyper/compiler.py", line 8, in compile
  File "/home/troper/vyper-venv/lib/python3.6/site-packages/vyper-0.0.4 py3.6.egg/vyper/compile_lll.py", line 279, in assembly_to_evm
ValueError: bytes must be in range(0, 256)
```

#### Cute Animal Picture

![image](https://user-images.githubusercontent.com/35941672/38773416-bf63f4fe-4019-11e8-9a7c-d0a44919526c.png)

**Comment by fubuloubu** [comment]
So, if I am understanding you correctly, you wish to store large zip files in Ethereum? 94kB, if I am counting correctly. What is the use case for this?

FYI that transaction will take 70mm gas to execute, which exceeds the currently gas limit by 10x. At current prices, it would cost you something like $100 to store that zip file. Why not IPFS?

**Comment by SamuelTroper** [comment]
The python code is an excerpt from a program I'm working on that will convert a mySQL database or a CSV to a series of smart contracts to allow for placing existing databases  and associated files on the Ethereum blockchain. Once I solve this issue or find a workaround I should be releasing a specific use case in less than a week and a more generalized program within a month.

I'm aware of the cost for larger files and have designed the program to allow users to decide if they want to store the largest files directly on the main net or on a private chain or to use another solution such as IPFS. I can see some use cases where users would like the entirety of their data stored on the main net, even if the cost is $100 for a zip file.

I had been testing on a private chain and forgot about the current gas limit on the main net though. I'm going to redesign these zip storage contracts to have several byte arrays which fall under the size that wouldn't exceed the gas limit and I'll see if the same error is thrown when working with those amounts of data. Even if that temporary work around works it still seems to me that there may be some issue with parsing larger series of bytes when compiling the contract.

**Comment by jacqueswww** [comment]
@SamuelTroper can you confirm this is still a bug?

Looking at the error, it looks like some 2 bytes characters are introduced, i.e. the representation is bigger than 1 byte. And we can't pack that - which indicates a problem in the script.
