### ISSUE TITLE
Unable to replicate code and run Unit Tests without ModuleNotFoundError

### ISSUE THREAD

**Issue by ltfschoen** [ethereum/vyper#783]
* vyper Version: 0.0.4
* pyethereum Version: N/A
* OS: osx (macOS 10.12.6
* Python Version (python --version): `Python 3.6.2`
* Environment (output of `pip freeze`):
```
aiohttp==2.3.10
asn1crypto==0.21.0
async-lru==0.1.0
async-timeout==1.2.0
attrdict==2.0.0
attrs==17.4.0
certifi==2017.4.17
cffi==1.7.0
chardet==3.0.2
coincurve==7.0.0
coverage==4.5.1
cryptography==2.2.2
cytoolz==0.9.0.1
eth-abi==1.0.0
eth-account==0.1.0a2
eth-bloom==1.0.0
eth-hash==0.1.1
eth-keyfile==0.5.1
eth-keys==0.2.0b3
eth-rlp==0.1.0
eth-tester==0.1.0b21
eth-utils==1.0.2
ethereum==2.3.1
future==0.16.0
hexbytes==0.1.0
idna==2.5
idna-ssl==1.0.0
lru-dict==1.1.6
more-itertools==4.1.0
multidict==4.0.0
pbkdf2==1.3
pluggy==0.6.0
py==1.5.3
py-ecc==1.4.2
py-evm==0.2.0a14
pycparser==2.18
pycryptodome==3.6.1
pyethash==0.1.27
pypandoc==1.4
pysha3==1.0.2
pytest==3.5.0
pytest-cov==2.5.1
pytest-runner==4.2
PyYAML==3.12
repoze.lru==0.7
requests==2.18.4
rlp==0.6.0
scrypt==0.8.6
semantic-version==2.6.0
six==1.10.0
toolz==0.8.0
trie==1.3.4
urllib3==1.21.1
vyper==0.0.4
web3==4.1.0
websockets==4.0.1
yarl==1.0.0
```

### What's your issue about?

I’ve created a simple version of the Vyper repo that just has the simple auction contract code and its unit tests https://github.com/ltfschoen/vyper-test

If you follow these basic setup instructions to setup Vyper and compile the smart contract, it all works successfully https://github.com/ltfschoen/vyper-test#chapter-0---setup-without-docker-

* Install [PyEnv](https://github.com/pyenv/pyenv)
* Clone the Vyper repo and install Vyper
    ```bash

    mkdir -p ~/code/clones && cd ~/code/clones
    git clone https://github.com/ethereum/vyper.git;
    cd vyper; 
    make; make test;
    ```
* Clone my repo
    ```bash
    cd ~/code/clones;
    git clone https://github.com/ltfschoen/vyper-test;
    ```
* Compile a Vyper contract
    ```bash
    vyper contracts/auctions/simple_open_auction.v.py
    ```

But then when you run these commands to run the Unit Test against the contract contracts/auctions/simple_open_auction.v.py, https://github.com/ltfschoen/vyper-test#chapter-4---unit-tests-,
```bash
pip3 install ethereum==2.3.1 pytest pytest-cov pytest-runner
python setup.py test
pytest -v --full-trace --setup-show
```

When I do this it gives the following error:

```
___ERROR collecting tests/auctions/test_simple_open_auction.v.py___
ImportError while importing test module '/Users/Me/code/blockchain/clones/vyper-test/tests/auctions/test_simple_open_auction.v.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/Users/Me/.pyenv/versions/3.6.2/lib/python3.6/site-packages/_pytest/python.py:411: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
/Users/Me/.pyenv/versions/3.6.2/lib/python3.6/site-packages/py/_path/local.py:668: in pyimport
    __import__(modname)
E   ModuleNotFoundError: No module named ‘test_simple_open_auction’
```

I'd like to know how resolve this so I can help try and integrate Vyper support into Truffle using a wrapper.

#### Cute Animal Picture

 &&&&&&&&&&
&&&&&&&&&&&
&&&   o    o   &&&
&&&      L     &&
  &&&&  C  &&
        &&&&&
     x____|____x
              |
           _/  \_

**Comment by haydenadams** [comment]
Go through the tests folder and delete cache files. Make sure the folder with `conftest.py` is the only folder in tests with an `__init__.py ` file, and delete all others. Then try running the tests with `python -m pytest -v`.

**Comment by ltfschoen** [comment]
Thanks @haydenadams I tried recursively deleting the __pycache__ folder that was created in both the tests/ subdirectory and the tests/auctions/ subdirectory, and the .pytest_cache folder in the project root directory, and then running `find . -name '*.pyc' -delete` just to be sure all the cache files had been removed from all subdirectories. I even added `export PYTHONDONTWRITEBYTECODE=1` to my `~/.bash_profile` so Python cache files would no longer be generated. I then ran both `python -m pytest -v`, and `python3 -m pytest -v` but unfortunately it still gives the same error.

**Comment by ltfschoen** [comment]
If I create a dummy file  in tests/auctions/test_sample.v.py with contents:
```python
# content of test_sample.py
def func(x):
    return x + 1

def test_answer():
    assert func(3) == 5
```
then it additionally gives these errors:
```
ImportError while importing test module '/Users/Ls/code/blockchain/clones/vyper-test/tests/auctions/test_sample.v.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/Users/Ls/.pyenv/versions/3.6.2/lib/python3.6/site-packages/_pytest/python.py:411: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
/Users/Ls/.pyenv/versions/3.6.2/lib/python3.6/site-packages/py/_path/local.py:668: in pyimport
    __import__(modname)
E   ModuleNotFoundError: No module named 'test_sample'
```

**Comment by haydenadams** [comment]
I smashed my head against these errors for a while and then eventually got it working. Follow the install instructions in my repo here:

https://github.com/Uniswap/contracts-vyper

Then you can use the structure of my project and swap out the files for your own.

**Comment by ltfschoen** [comment]
Thanks for your link.
There were a few things I was doing wrong.
Firstly, the implementation file was in contracts/auctions/simple_open_auction.v.py.
So my test should have been in tests/contracts/auctions/test_simple_open_auction.py.
However my test file was: tests/auctions/test_simple_open_auction.v.py
So the file extension that I was using for the test was wrong, and I hadn't included the ../contracts/.. subdirectory.
There is also a fixture `t()` that is defined 
on [Line 65 in conftest.py](https://github.com/ethereum/vyper/blob/master/tests/conftest.py#L65), and I had incorrectly renamed it to `tester` instead of leaving it as `t` in my test file.
Lastly, I'd forgotten that had modified simple_open_auction.v.py and tried to add traditional Python documentation using `"""` syntax as follows, but I hadn't checked if the changes compiled correctly by running `vyper contracts/auctions/simple_open_auction.v.py` before running the unit tests:
````
def __init__(_beneficiary: address, _bidding_time: timedelta):
    """
    :param _beneficiary: Beneficiary address receives money from 
      highest bid when auction period ends
    :type _beneficiary: address

    :param _bidding_time: Participants submit bids during limited time period
    :type _beneficiary: timedelta

    :output N/A: N/A
    """

...
```
So when I ran the Unit Test it encountered an error on the line `t.c = t.s.contract(contract_code, language='vyper', args=[t.accounts[0], FIVE_DAYS])` in my unit test file  when it was trying to compile my contract `vyper.exceptions.StructureException: line 31: Unsupported statement type: <class '_ast.Str'>`. It was telling me that Line 31 in the implementation file was using an invalid commenting syntax, which is because **not all Python 3 functionality is available in Vyper**
Here is the commit with my latest changes: https://github.com/ltfschoen/vyper-test
It's now recognising and processing the test file.

**Comment by ltfschoen** [comment]
I’ve got Travis CI to check my Vyper unit tests as passing with this commit https://github.com/ltfschoen/vyper-test/commit/240728490dd84720cb16a1f5749ba781239794b0, so and I’ve updated the README so it shows the icon representative of whether the Travis CI tests are passing or failing

**Comment by ltfschoen** [comment]
Thanks for your help. I'm going to close this issue now that it's resolved
