### ISSUE TITLE
Meeting 23rd April 2018

### ISSUE THREAD

**Issue by jacqueswww** [ethereum/vyper#788]
### Meeting Details

General Bi-Weekly meeting. 
Start: Monday 23rd April 2018, 14:00 UTC (https://time.is/UTC)
Hangouts: https://meet.google.com/czc-kuep-jda

### Agenda

 - VIP Discussions:
   - https://github.com/ethereum/vyper/issues/781 - Fallback functions
   - https://github.com/ethereum/vyper/issues/770 - Denote static call per method
   - https://github.com/ethereum/vyper/issues/764 - uint256 operations
   - https://github.com/ethereum/vyper/issues/765 - Initial values
   - https://github.com/ethereum/vyper/issues/769 - Storage variable layout
- Other: 
   - json lll parser / bin https://github.com/ethereum/vyper/issues/790
- Progress: https://github.com/ethereum/vyper/projects

**Comment by daejunpark** [comment]
Do you also want to discuss about https://github.com/ethereum/vyper/issues/769? At least, just to make sure we're on the same page?

**Comment by ltfschoen** [comment]
Apologies as I will not be able to join this meeting
