### ISSUE TITLE
Expose LLL IR

### ISSUE THREAD

**Issue by ralexstokes** [ethereum/vyper#790]
The current compiler `v0.0.4` doesn't expose the LLL IR as it's own target. An implication of this is that you can't author LLL and then generate bytecode in an easy manner.

It would be ideal to eventually expose the LLL as a separate module that the vyper frontend (and any other frontend) could consume.

**Comment by djrtwo** [comment]
Important for Casper contract to remove it's reliance upon the Serpent compiler.

https://github.com/ethereum/casper/issues/69
https://github.com/ethereum/casper/issues/73

**Comment by fubuloubu** [comment]
`sighasher` looks like something that might be of more general utility. is that true?

Perhaps we can implement some of these functions as vyper primitives, if that makes sense. Or the portions of them which might make sense as primitives which allows you to compose larger functions out of those new primitives.

What portion of those casper contracts cannot be implemented using Vyper?

**Comment by daniel-jozsef** [comment]
I do think we absolutely need a dedicated LLL compiler. This should be a separate EIP, shouldn't it?

**Comment by jacqueswww** [comment]
@daniel-jozsef for the time being, I will create `vyper-lll` command here.

I think going full parethesis ?

**Comment by fubuloubu** [comment]
lisp away!

**Comment by ralexstokes** [comment]
yeah -- the LLL source should just be a bunch of nested parens :)
