### ISSUE TITLE
We need a logo! (now closed)

### ISSUE THREAD

**Issue by fubuloubu** [ethereum/vyper#794]
# Challenge

Who has some design chops and wants to make us a cool logo?

Solidity has a logo, but we're cooler so we should have a better one!

P.S. we :hearts: you Solidity

---
# Rules

If you have a submission, post it to this issue as an embedded image (hosted from wherever you animals host things) and whomever has the most :+1:'s wins the bounty! Anyone can vote on submissions !

Challenge ends with our beta release (currently June 1st), where the winning submission will be added as a PR to our README/docs.

Closing Date: 1st June 2018

NOTE: Please do not submit a PR yet! Add your submission as a comment below!

NOTE: Please nothing offensive. Keep it clean, Vyperinos!

NOTE: Keep it original. As pointed out in the comments existing Vyper logos do already exist. Please refrain from making them look too similar, we don't want to get involved in any copy infrigement battles :stuck_out_tongue_closed_eyes:  

NOTE: Please also see [Ethereum Branding Guidelines](https://www.ethereum.org/images/logos/Ethereum_Visual_Identity_1.0.0.pdf)

---
# Sponsors

SNT bounty sponsored by Status (https://openbounty.status.im).
ETH Bounty sponsored by @jacqueswww and myself
Feel free to add more bounties if you desire! ETH/ERC20/ERC223 accepted

---
# Brainstorming and Comments

Feel free to add notes with your concepts of what Vyper is and brainstorm concepts.

My design keywords (just for brainstorming):
* Snek (obvs)
* Sharp
* Secure
* Emerald
* Friendly

And some additional insperation: 
https://docs.google.com/document/d/1TSqVXVXVjiVxH5COXgIu90_dSJTQv3_Ka-aI6MYqeIo

NOTE: Anyone can add a comment here just chatting about the designs or whatnot. Official entries should just contain the picture (optionally some comment about it) and are voted on ONLY using :+1:

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0xc74cfeacbd68711b5787a27e55c85e18e577173ea374a8b947c87b7b7a0e4e36](https://etherscan.io/tx/0xc74cfeacbd68711b5787a27e55c85e18e577173ea374a8b947c87b7b7a0e4e36)

**Comment by jtlacci** [comment]
Here's a quick simple concept can mess with the colors or add serif

![Viper logo concept](https://raw.githubusercontent.com/jtlacci/Misc/8d6f49cc/Viper-logo.png)

**Comment by jakerockland** [comment]
Here's my go. 

I like that @JisuPark tried to pay homage to the Solidity logo, and like the consistency that that creates, so I tried to incorporate that in my design. Also [∆](https://math.stackexchange.com/questions/1393965/are-triangles-the-strongest-shape) conveys security/strength. 

[Vyper.svg.zip](https://github.com/ethereum/vyper/files/1953818/Vyper.svg.zip)
Made it green because 🐍

<p align="center"> 
<img src="https://user-images.githubusercontent.com/8602661/39344563-078e6c0a-4998-11e8-9210-933cd81c43b8.png">
</p>

SVG in `.zip`

**Comment by haydenadams** [comment]
I really like the idea of an ethereum logo as the center of a snake eye. Quickly threw this together, but down to make it nice if people are interested!

![vyperv1-01](https://user-images.githubusercontent.com/9343483/39346520-91f1fa50-49bc-11e8-8c6d-c96a3865162d.png)

**Comment by ben-kaufman** [comment]
I am not a designer so just posting here some ideas here for the designers to use.

Maybe we can make something similar to this
![image](https://user-images.githubusercontent.com/10667901/39360079-64b24360-4a25-11e8-9a87-8e7b9de414af.png)

But with a few changes:
1. Green snake, I think one of these colors #2CBD9A #B0E744 59982f can be good.
2. No background of course
3. Maybe flipping the snake so the head is to the right (mirror)
4. Make the snake look more calm and not like he's about to bite
5. I think we can make the snake fit to the gap in the Ethereum logo and make it look like it's wrapping it but still looks like a V.
6. Make the snake teeth look like the bottom part of the ethereum logo.

**Comment by fubuloubu** [comment]
@ben-kaufman 5. would be sickkkk

**Comment by yanncarlier** [comment]
![vyperscratch](https://user-images.githubusercontent.com/227698/39370072-8f1c4362-4a70-11e8-9b89-fd7392534adf.png)

**Comment by Shrinks99** [comment]
Alrighty, here's my take on it.

![asset 21](https://user-images.githubusercontent.com/5672810/39390587-b76f313c-4a64-11e8-9931-d7afd7e5ffb2.png)

Proper versions of the Ethereum branding are hard to find!  The official logomark font is not actually listed anywhere and I had to do some real sleuthing to locate it (It's Print Clearly by the way).  I used the existing Ethereum branding (Solidity, Whisper, Ethereum and Swarm) as a guide for this new logo which takes the shape of a V with two cut outs (snake fangs!) and a geometric pattern that represents scales.

It also works pretty well as a single tone graphic

![asset 3black](https://user-images.githubusercontent.com/5672810/39390693-3182bf92-4a66-11e8-9b8f-1860f66d5262.png)

Proper vectors and assets will be made available upon request, I look forward to feedback!

**Comment by ggcarlosr** [comment]
Good evening here my design I hope you like it, it is based on the given guidelines and gives the clear identity that Vyper needs.


![vyper](https://user-images.githubusercontent.com/37964430/39391699-ba3f4882-4a75-11e8-921b-5d525208ec9d.png)

![vyper2](https://user-images.githubusercontent.com/37964430/39391716-101cd4a4-4a76-11e8-81ca-972d7f9404f6.png)

**Comment by fubuloubu** [comment]
Fantastic submissions so far!!! Thank you so much :)

**Comment by BryaaNz** [comment]
Hello everyone, here is my contribution

![vyper](https://user-images.githubusercontent.com/38763205/39424163-985cba0e-4c75-11e8-974c-fd4d5db65092.jpg)

**Comment by debragail** [comment]
![vyperport](https://user-images.githubusercontent.com/552529/39471338-8cb73c2e-4cf7-11e8-9931-c254319d6dee.jpg)
![vyper](https://user-images.githubusercontent.com/552529/39471346-95bbed7e-4cf7-11e8-8762-45d014173f4b.png)
![vypr](https://user-images.githubusercontent.com/552529/39471355-9fdecfd8-4cf7-11e8-91da-46861557164e.jpeg)

some vyper logos already exist

**Comment by jacqueswww** [comment]
@debragail that is correct. Vyper the Programming language may obviously not have too similar logo (that could be mistaken for copyright infringement).

**Comment by debragail** [comment]
![vyper_log](https://user-images.githubusercontent.com/552529/39471873-88b44b3c-4cfa-11e8-9dd6-3d39d73cc1fc.png)

**Comment by debragail** [comment]
a mean lil python

**Comment by yanncarlier** [comment]
![screenshot from 2018-05-01 22-08-12](https://user-images.githubusercontent.com/227698/39475920-be896ef8-4d8c-11e8-9896-cba30b3633a1.png)

**Comment by tao** [comment]
![Initial](https://raw.githubusercontent.com/tao/viper-logo/master/vyper-1.jpg)

The logo is a a combination of `lambda` and `less than` (< + λ) which resembles a viper snake mouth with a forked tongue, using emerald green `#50c878`. The logo uses the same title font as the ethereum branding, but the logo symbol design differs from the ethereum and solidity one.

![Contrast](https://raw.githubusercontent.com/tao/viper-logo/master/vyper-2.jpg)

Alternative contrast options for light and dark backgrounds.

![Alts](https://raw.githubusercontent.com/tao/viper-logo/master/vyper-3.jpg)

The logo is versatile and can easily be adjusted to match different styles if necessary as the context changes.

![Layout](https://raw.githubusercontent.com/tao/viper-logo/master/vyper-4.jpg)

This image shows the layout of the logo in both horizontal and vertical format.

![Retro](https://raw.githubusercontent.com/tao/viper-logo/master/vyper-5.jpg)

A retro logo for fun :P it just need's some chrome text...

**Comment by fubuloubu** [comment]
Love the creativity @tao!

**Comment by tao** [comment]
Cool, this was my alternate idea but it's a bit harder to get the vertical logo right because the symbol is taller - so it might not work at smaller sizes, maybe some one else can play around with the idea a bit and see what comes out, or I'll have to spend some more time and clean it up a bit later on.

![Alternative](https://raw.githubusercontent.com/tao/viper-logo/master/viper-alt.jpg)

**Comment by mandarvaze** [comment]
@yanncarlier This is the most "friendly" logo IMO. Cheers.

**Comment by foobarbecue** [comment]
![image](https://user-images.githubusercontent.com/854789/39561246-5aa82b7c-4e59-11e8-9b37-12e32ae863f2.png)

**Comment by Alexintosh** [comment]
![b35793a7-70c5-4b6f-a138-d1ee3100b28e](https://user-images.githubusercontent.com/776519/39667991-82670758-5090-11e8-8c08-03dbe7f2cea0.jpeg)

Submission from @dimarconicola art director at [Dexlab](https://github.com/dexlab-io/Organization/).

We used the Ethereum Visual Identity guidelines as a reference for this logo.

The Icon shows a snake nested in a Ethereum-like diamond shape.

The font used and the size proportion between the graphic element and font are the same as indicated by the official guidelines.

Assets will be shared upon request.
Looking forward to hearing your feedback!

**Comment by gbonumore** [comment]
Here is my submission, designer at [Dexlab](https://github.com/dexlab-io/Organization/).

Tried to recreate a snake with ethereum basic shapes, the font is a Roboto light following the official guidelines. Also added a possible gradient version.

Open to feedback & suggestions!

![vyper logo](https://user-images.githubusercontent.com/34310821/39673423-283c8cc4-513c-11e8-84fe-56f012dbd128.jpg)
![vyper logo colored](https://user-images.githubusercontent.com/34310821/39673424-28567c1a-513c-11e8-942c-e3c8851e3b75.jpg)

**Comment by PaulGall** [comment]
![vyper_logo](https://user-images.githubusercontent.com/14868690/39684101-344353ae-5155-11e8-8b24-639ee11d40b5.png)

I'll produce a production quality version by June 1st if it starts getting the votes.

Thoughts: 

1.   A programming language will be platform agnostic with time, so I ignored the Ethereum identity 
     guidelines.

2. I did pay tribute to the language's history: 
        a) Ethereum - eyes 
        b) Python - Flux regular font - but uppercase

3.  The emerald color was inspired by: 

       a) the color of the Guinness Emerald one of the largest and most valuable uncut emeralds
          (i.e. in Alpha like Vyper)
           [https://bit.ly/2JURIVG](url)

       b) the color of the green pit viper
           [https://bit.ly/2jAy0n2](url)
           
       c) I'm from Ireland (the Emerald Isle) and Guinness is a staple :)
           I also just found out the the origin of the "Emerald Isle" was from a poem 
           called "When Erin first Rose" which also mentions a serpent.
           [https://bit.ly/2jAECS0](url)

![vyper_logo-forked](https://user-images.githubusercontent.com/14868690/39684147-77e3041a-5155-11e8-9275-94fe0f16c3b3.png)


I'd like to think it's friendly. 

Best, 

Paul

P.s. Only bounty I want is Vyper Lessons

**Comment by yasueb** [comment]
My inspiration from the design keywords.
![vyper](https://user-images.githubusercontent.com/20157902/40025455-5b27b744-576d-11e8-9629-edfbf715995e.jpg)
![vyper_b w](https://user-images.githubusercontent.com/20157902/40025478-690e8e78-576d-11e8-8df7-93dc4f086aaf.jpg)

**Comment by PaulGall** [comment]
Great job!

**Comment by pipermerriam** [comment]
![screen shot 2018-05-15 at 9 52 46 am](https://user-images.githubusercontent.com/824194/40068398-bff97fe6-5825-11e8-827d-8b7dbc6cfbe4.png)

Alternate version with a top-hat.

**Comment by fubuloubu** [comment]
Just over 2 weeks to go! Here are the current standings:
1. @dimarconicola - 29 votes
2. @Shrinks99 - 27 votes
3. @gbonumore - 26 votes

Introduce your friends to Vyper so we can get more votes from our community members!

**Comment by PaulGall** [comment]
![paul-vyper](https://user-images.githubusercontent.com/14868690/40103298-af1dd10a-5888-11e8-9ed4-27a63efdf976.jpg)

**Comment by PaulGall** [comment]
More along the brand lines. 

Paul

**Comment by ben-kaufman** [comment]
Stealing @fubuloubu format ;)

Just 1 week to go! Here are the current standings:

@Shrinks99 - 38 votes
@dimarconicola - 33 votes
@gbonumore - 29 votes
Introduce your friends to Vyper so we can get more votes from our community members!

**Comment by maxstermade** [comment]
![pg1 3x-100](https://user-images.githubusercontent.com/18520002/40570550-051925d6-605a-11e8-834c-c8f20320c33e.jpg)
![pg2 3x-100](https://user-images.githubusercontent.com/18520002/40570552-07e9cefa-605a-11e8-9bb0-58228ccb746b.jpg)

**Comment by mandarvaze** [comment]
@maxstermade I liked the design, especially with purple/pink shades.

IMO the rounded edges make it look like an elephant. May be try sharp edges for indicate fangs.

**Comment by fubuloubu** [comment]
I agree with @mandarvaze, a little sharpess at the bottom for fangs and that logo will be :+1:

I love the color scheme!

**Comment by haydenadams** [comment]
I think the vote should probably be redone in a new thread, with the top designs from here all submitted simultaneously at the top and no new submissions allowed.

**Comment by fubuloubu** [comment]
That might be a good idea. Although, two of the later submissions actually got more traction than the earlier ones so I think your thesis is actually opposite, but I think you're definitely right in that our voting strategy isn't the most fair to all entrants.

Let's discuss if a better one exists and how that is fair to the current participants who entered the contest under the context of the current rules. To gitter! Gitter.im/Ethereum/Vyper

**Comment by tao** [comment]
I think @Shrinks99 has done the best job so far because it works well with the other logos, but it's probably best to consider the votes and decide yourselves what's best, otherwise you might end up with a [Boaty mcBoatface](https://www.nytimes.com/2016/03/22/world/europe/boaty-mcboatface-what-you-get-when-you-let-the-internet-decide.html) situation in the future if you let the internet choose.

**Comment by fubuloubu** [comment]
I think you're right and that entry is the best logo from a technical perspective and a branding match perspective. I've really enjoyed all of the entries so far, there has been a lot of creativity and some laughs.

I personally was looking forward to seeing alternative designs that dispatched with the current Ethereum branding. I believe diversity of branding and style mirrors diversity of ideas and opinions. The Ethereum diamond is probably firmly cemented as one of the most iconic logos in crypto, it was going to be difficult to overcome that, but I'm really happy we tried different ideas out and had fun with this contest.

The community votes will definitely help make the decision, I think we avoided "Boaty McBoatface" with truly high quality entries. This decision will definitely be difficult to make!

**Comment by Shrinks99** [comment]
@fubuloubu My goal from the beginning was to match the existing branding and geometric (triangle and greyscale focused) style.  IMO the Ethereum graphics need a little work, the brand style guide isn't as complete as it should be and could be expanded upon in many areas ranging from typography to colour schemes.

When obtaining the actual vectors back in 2017 I had a short conversation with Ian Meikle, the original designer.  He said some major changes were being made with the branding although I am unsure if those are still planned as nothing has really changed since then.

Should changes be still coming I think it would be nice for them to have a Vyper logo to work from that is in line with the other assets.  If the changes have been scrapped since then I may consider spending some of my time expanding and diversifying the Ethereum branding a little should my logo be chosen, if they haven't been scrapped I'd be happy to work with them on that if they need more people!  That said I'll have to ask Ian again to get up to speed before anything happens in regard to brand diversification.

**Comment by maxstermade** [comment]
![artboard 5 2x-100](https://user-images.githubusercontent.com/18520002/40579769-7f075a04-60fd-11e8-9a22-32d3ef09e671.jpg)
okay, made some edits based on the comments. Agree with shrinks99(the logotype sucks).

**Comment by toztokens** [comment]
Hey everyone!

Here is my submission. We had a fun little internal competition at our agency! [The Tokens](https://thetokens.agency)

**Rationale**
The design makes use of negative space, giving reference to the Ethereum diamond whilst also doubling as a snake’s head. The emerald stone shape offers solidity and the asymmetrical use of gradient provides depth and dynamism.

An easily identifiable symbol that draws from the aesthetic of the programming family whilst giving Vyper its own powerful personality.

Looking forward to hearing any feedback!


![vy 1 1](https://user-images.githubusercontent.com/39783547/40764221-95f75498-64eb-11e8-8a8d-7389400a5393.jpg)
![vy 1 2](https://user-images.githubusercontent.com/39783547/40764222-962b09c8-64eb-11e8-85de-9e58eac18547.jpg)
![vy 1 4](https://user-images.githubusercontent.com/39783547/40764224-969e908c-64eb-11e8-8c61-4ee1d08e1eed.jpg)
![vy 1 3](https://user-images.githubusercontent.com/39783547/40764223-9660a290-64eb-11e8-8bb1-5153cb984b50.jpg)

**Comment by robbietokens** [comment]
Hey!
We had some fun at our agency, The Tokens, and a few of us created a logo. 
Here is my submission!
Looking forward to hearing feedback and thanks for the opportunity,
Robbie.
robbie@thetokens.agency
website: http://thetokens.agency

--
**Design Rationale**
Utilises the texture of snakeskin to offer depth and intrigue. Still simple, the logo uses negative space to create the shape of a snake’s head and the bold emerald colour for extra vibrance and dynamic.

Incorporating Ethereum's geometric styling but playing with the scale and their relationship to each other, the emerald 'snakeskin' gives it an almost retro feel, but still feels a part of the logo set.
 
---
![vy 3 1](https://user-images.githubusercontent.com/39783510/40764388-2f4a12ca-64ec-11e8-8d2c-652d2aafb436.jpg)
![vy 3 2](https://user-images.githubusercontent.com/39783510/40764389-2f804782-64ec-11e8-82fe-7f1a064d415b.jpg)
![vy 3 3](https://user-images.githubusercontent.com/39783510/40764391-2fb5d2a8-64ec-11e8-90ba-4b44862c84e9.jpg)
![vy 3 4](https://user-images.githubusercontent.com/39783510/40764393-3022c5ac-64ec-11e8-8fa9-49c19b2fb453.jpg)

**Comment by MattTokens** [comment]
And here's mine! Can't wait to hear everyone's thoughts.

**Design Rationale**
Using the shape of a snake to draw immediate connection to Vyper. The application of triangles in this instance represents part of a connected whole, where each triangle adds something to the next, in order to take form.

Being designed around a vertical axis offers the reassurance of security whilst the pose of a striking snake, suggests speed.

![vy 2 1](https://user-images.githubusercontent.com/39783542/40767015-9ec7d81e-64f4-11e8-9633-eb05ff2e043d.jpg)
![vy 2 2](https://user-images.githubusercontent.com/39783542/40767022-a3a00c4e-64f4-11e8-8f0e-33fe754a88c1.jpg)
![vy 2 4](https://user-images.githubusercontent.com/39783542/40767037-a971d90e-64f4-11e8-9202-52e788647674.jpg)
![vy 2 5](https://user-images.githubusercontent.com/39783542/40767047-ad7a6156-64f4-11e8-8882-032071368bcd.jpg)
![vy 2 3](https://user-images.githubusercontent.com/39783542/40767105-db3ec38e-64f4-11e8-81b9-bbbd77d86562.jpg)

**Comment by jacqueswww** [comment]
@robbietokens I really lilke the scales effect on the logo :smiley_cat: :snake:

**Comment by jacqueswww** [comment]
Just wanted to say thanks to everyone that participated in the Logo Bounty!
We will follow up shortly with a nice clean post on what we decided. :smile_cat: :airplane:

**Comment by jacqueswww** [comment]
Hi Everyone!

@fubuloubu and myself decided the logo bounty will be split will be split between our two top entries. We decided this would be the best options, as the race was so close.
Additionally we plan to work with @shrinks99 to make slight alterations to his proposed logo, and make an emerald green version as well.
Follow the thread for to see the final logo :smile: 

I would like to thank everyone in the community that participated, I really enjoyed to see everyone's take on the provided keywords. :clap: :fireworks: :snake:

**Comment by fubuloubu** [comment]
I'd really like to echo how many great entries we received. I was really expressed with the quality of every single entry (even the jokes) and it surpassed my expectations to have so much engagement on this contest.

We hope that you guys decide to stick with us as a community and that you give Vyper a shot if you haven't already and wanted to learn more about it or smart contract development in general.

Cheers!

**Comment by Alexintosh** [comment]
@fubuloubu looking forward to use Vyper as the main smart contract language. 💪

**Comment by fubuloubu** [comment]
@Alexintosh check your gitter
