### ISSUE TITLE
clamp has different behavior on checking the lowerbound and the upperbound

### ISSUE THREAD

**Issue by yzhang90** [ethereum/vyper#802]
### What's your issue about?

`clamp` is compiled to following EVM bytecode:
```
o.extend(compile_to_assembly(code.args[2], withargs, break_dest, height + 3))
o.extend(['SWAP1', comp1, 'PC', 'JUMPI'])
o.extend(['DUP1', 'SWAP2', 'SWAP1', comp2, 'ISZERO'])
o.extend(get_revert())
```
When the value is greater than the upper-bound, the code jump to an invalid pc. When the value is smaller than the lower-bound, the code use REVERT to revert the state. 

### How can it be fixed?

It's better to use REVERT on both cases.

#### Cute Animal Picture

![image](https://user-images.githubusercontent.com/5641590/39583950-dda264f4-4eb6-11e8-8e6a-54278c481932.png)

**Comment by jacqueswww** [comment]
@yzhang90 thanks! :smile_cat:
