### ISSUE TITLE
Issue running Make Test - ImportError: cannot import name 'decode_hex'

### ISSUE THREAD

**Issue by mgbvox** [ethereum/vyper#804]
* vyper Version: Cloned on 5/3/2018. Not sure where to find version.
* pyethereum Version: I don't think it's installed - see the first paragraph after this.
* OS: OSX High Sierra
* Python Version (python --version): Python 3.6.3 :: Anaconda, Inc.
* Environment (output of `pip freeze`): **Posted at the end - it's long**

First note, in attempting to install pyethereum following [this protocol](https://gist.github.com/SerpentChris/e97336a28d29bc03fc39562511b14b82), I kept getting that
py_evm-0.2.0a16 requires pyethash-0.1.27, while I only have pyethash-0.1.23 (when I try to uninstall or upgrade with pip I get an error saying I can't uninstall because they can't determine what's using it... or whatever. Frankly all of this is insanely confusing.) 

**Right. The main issue:**

After cloning ethash in my virtualenv ("vypEnv"), setup building and installing, cloning vyper, navigating to root, apparently successfully running make (though it only seems to be running make init), when I attempt to run **make test** I get:

`Traceback (most recent call last):
  File "/Users/mgb/vypEnv/vyper/.eggs/pytest-3.5.1-py3.6.egg/_pytest/config.py", line 334, in _getconftestmodules
    return self._path2confmods[path]
KeyError: local('/Users/mgb/vypEnv/vyper/tests')

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/mgb/vypEnv/vyper/.eggs/pytest-3.5.1-py3.6.egg/_pytest/config.py", line 365, in _importconftest
    return self._conftestpath2mod[conftestpath]
KeyError: local('/Users/mgb/vypEnv/vyper/tests/conftest.py')

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/mgb/vypEnv/vyper/.eggs/pytest-3.5.1-py3.6.egg/_pytest/config.py", line 371, in _importconftest
    mod = conftestpath.pyimport()
  File "/Users/mgb/vypEnv/vyper/.eggs/py-1.5.3-py3.6.egg/py/_path/local.py", line 668, in pyimport
    __import__(modname)
  File "/Users/mgb/vypEnv/vyper/.eggs/pytest-3.5.1-py3.6.egg/_pytest/assertion/rewrite.py", line 213, in load_module
    py.builtin.exec_(co, mod.__dict__)
  File "/Users/mgb/vypEnv/vyper/tests/conftest.py", line 4, in <module>
    from ethereum.tools import tester
  File "/Users/mgb/vypEnv/vyper/.eggs/ethereum-2.3.1-py3.6.egg/ethereum/__init__.py", line 11, in <module>
    from . import slogging  # noqa
  File "/Users/mgb/vypEnv/vyper/.eggs/ethereum-2.3.1-py3.6.egg/ethereum/slogging.py", line 6, in <module>
    from ethereum.utils import bcolors, is_numeric
  File "/Users/mgb/vypEnv/vyper/.eggs/ethereum-2.3.1-py3.6.egg/ethereum/utils.py", line 13, in <module>
    from rlp.utils import decode_hex, encode_hex, ascii_chr, str_to_bytes
ImportError: cannot import name 'decode_hex'
ERROR: could not load /Users/mgb/vypEnv/vyper/tests/conftest.py

`
With:
make: *** [test] Error 4.

The non-error text just above this reads:
`Using /Users/mgb/vypEnv/vyper/.eggs/attrs-18.1.0-py3.6.egg
running egg_info
writing vyper.egg-info/PKG-INFO
writing dependency_links to vyper.egg-info/dependency_links.txt
writing requirements to vyper.egg-info/requires.txt
writing top-level names to vyper.egg-info/top_level.txt
reading manifest file 'vyper.egg-info/SOURCES.txt'
writing manifest file 'vyper.egg-info/SOURCES.txt'
running build_ext`

I honestly have no idea what's going on. Help.

PIP FREEZE OUTPUT:
aiohttp==2.3.10
appnope==0.1.0
asn1crypto==0.24.0
async-lru==0.1.0
async-timeout==2.0.1
attrdict==2.0.0
backcall==0.1.0
certifi==2018.4.16
cffi==1.11.5
chardet==3.0.4
coincurve==7.1.0
cryptography==2.2.2
cytoolz==0.9.0.1
decorator==4.3.0
eth-abi==1.0.0
eth-account==0.2.2
eth-bloom==1.0.0
eth-hash==0.1.2
eth-keyfile==0.5.1
eth-keys==0.2.0b3
eth-rlp==0.1.2
eth-utils==1.0.3
ethereum==1.6.0
hexbytes==0.1.0
idna==2.6
idna-ssl==1.0.1
ipython==6.3.1
ipython-genutils==0.2.0
jedi==0.12.0
lru-dict==1.1.6
multidict==4.2.0
parso==0.2.0
pexpect==4.5.0
pickleshare==0.7.4
plyvel==1.0.4
prompt-toolkit==1.0.15
ptyprocess==0.5.2
py-ecc==1.4.2
py-evm==0.2.0a16
pycparser==2.18
pycryptodome==3.6.1
pyethash==0.1.23
Pygments==2.2.0
pysha3==1.0.2
PyYAML==3.12
requests==2.18.4
rlp==1.0.1
scrypt==0.8.6
simplegeneric==0.8.1
six==1.11.0
toolz==0.9.0
traitlets==4.3.2
trie==1.3.6
urllib3==1.22
vyper==0.0.4
wcwidth==0.1.7
web3==4.2.0
websockets==4.0.1
yarl==1.2.3

**Comment by jacqueswww** [comment]
Please try now.

**Comment by mgbvox** [comment]
Still getting the same issues (deleted my virtual env and reinstalled vyper). Here's the new error text:

Traceback (most recent call last):
  File "/Users/mgb/vypEnv/vyper/.eggs/pytest-3.5.1-py3.6.egg/_pytest/config.py", line 334, in _getconftestmodules
    return self._path2confmods[path]
KeyError: local('/Users/mgb/vypEnv/vyper/tests')

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/mgb/vypEnv/vyper/.eggs/pytest-3.5.1-py3.6.egg/_pytest/config.py", line 365, in _importconftest
    return self._conftestpath2mod[conftestpath]
KeyError: local('/Users/mgb/vypEnv/vyper/tests/conftest.py')

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/mgb/vypEnv/vyper/.eggs/pytest-3.5.1-py3.6.egg/_pytest/config.py", line 371, in _importconftest
    mod = conftestpath.pyimport()
  File "/Users/mgb/vypEnv/vyper/.eggs/py-1.5.3-py3.6.egg/py/_path/local.py", line 668, in pyimport
    __import__(modname)
  File "/Users/mgb/vypEnv/vyper/.eggs/pytest-3.5.1-py3.6.egg/_pytest/assertion/rewrite.py", line 213, in load_module
    py.builtin.exec_(co, mod.__dict__)
  File "/Users/mgb/vypEnv/vyper/tests/conftest.py", line 4, in <module>
    from ethereum.tools import tester
  File "/Users/mgb/vypEnv/vyper/.eggs/ethereum-2.3.1-py3.6.egg/ethereum/__init__.py", line 11, in <module>
    from . import slogging  # noqa
  File "/Users/mgb/vypEnv/vyper/.eggs/ethereum-2.3.1-py3.6.egg/ethereum/slogging.py", line 6, in <module>
    from ethereum.utils import bcolors, is_numeric
  File "/Users/mgb/vypEnv/vyper/.eggs/ethereum-2.3.1-py3.6.egg/ethereum/utils.py", line 13, in <module>
    from rlp.utils import decode_hex, encode_hex, ascii_chr, str_to_bytes
ImportError: cannot import name 'decode_hex'
ERROR: could not load /Users/mgb/vypEnv/vyper/tests/conftest.py

**Comment by mgbvox** [comment]
@jacqueswww, does there exist an installation guide for installing vyper de novo on Mac OSX high Sierra? The readthedocs page for installation has never worked for myself or my team - we're currently compiling a how-to step-by-step doc, but it is incomplete. Would be very helpful to have someone from the team write something up.

**Comment by jacqueswww** [comment]
@mgbvox this specific issue is related to a conflict between rlp required by specific version s of py-evm and pyethereum.

I unfortunately don't have easy acces to prep and access the MacOS Installation steps, but will have a good look into the steps. From linux side snap install works really well, if you felt like running it in a rocker image perhaps?

**Comment by mgbvox** [comment]
@jacqueswww how does one run a snap inside a docker image?

Also, when I run:
docker build https://github.com/ethereum/vyper.git -t vyper:1
docker run -it vyper:1 /bin/bash
make test

inside my python virtualenv, I get:
bash: make: command not found

And just running:
vyper examples/crowdfund.v.py

outputs:
0x600035601c52740100000000000000000000000000000000000000006020526f7fffffffffffffffffffffffffffffff6040527fffffffffffffffffffffffffffffffff8000000000000000000000000000000060605274012a05f1fffffffffffffffffffffffffdabf41c006080527ffffffffffffffffffffffffed5fa0e000000000000000000000000000000000060a05260606103986101403934156100a757600080fd5b602061039860c03960c05160205181106100c057600080fd5b50606051602060206103980160c03960c051806040519013585780919012156100e857600080fd5b50606051602060406103980160c03960c0518060405190135857809190121561011057600080fd5b50610140516002556060516101805142018060405190135857809190121561013757600080fd5b600355610180516006556101605160045561038056600035601c52740100000000000000000000000000000000000000006020526f7fffffffffffffffffffffffffffffff6040527fffffffffffffffffffffffffffffffff8000000000000000000000000000000060605274012a05f1fffffffffffffffffffffffffdabf41c006080527ffffffffffffffffffffffffed5fa0e000000000000000000000000000000000060a05263d11711a260005114156100fc5760035442126100af57600080fd5b6001546101405261014051600060c052602060c0200160c052602060c0203381553460018201555060605160016101405101806040519013585780919012156100f757600080fd5b600155005b634bb278f3600051141561013257341561011557600080fd5b600454303112156003544212151661012c57600080fd5b600254ff005b63590e1ae3600051141561023257341561014b57600080fd5b6004543031126003544212151661016157600080fd5b6005546101405261016061014051601e818352015b600154610160511215156101905760015460055560006000f35b6000600060006000600161016051600060c052602060c0200160c052602060c020015461016051600060c052602060c0200160c052602060c020546000f16101d757600080fd5b61016051600060c052602060c0200160c052602060c0206000815560006001820155505b8151600101808352811415610176575b5050606051601e61014051018060405190135857809190121561022d57600080fd5b600555005b5b61014d6103800361014d60003961014d610380036000f3

**Comment by jacqueswww** [comment]
Yes, seems to work. Only tests that'll need additional installions.

The original error in the title `ImportError: cannot import name 'decode_hex'`  has been fixed now.
