### ISSUE TITLE
PyPI version doesn't install

### ISSUE THREAD

**Issue by ldct** [ethereum/vyper#805]
The old version (0.0.2) available on PyPI (https://pypi.org/project/eth-vyper/) specifies a dependency on an old version of `pyethereum` which has a `setup.py` that is incompatible with current versions of pip. Hence, vyper cannot be installed from PyPI.

This issue was actually fixed in https://github.com/ethereum/vyper/pull/741, so uploading a new release to PyPI that includes that should solve this problem.

```
python3 -m venv .
source bin/activate
pip3 install eth-vyper
```

Output:

```
Collecting eth-vyper
  Using cached https://files.pythonhosted.org/packages/9d/b8/7c9005feca3b5825234e020903cd5d5749653090b37b7bb34e16d6c63c89/eth_vyper-0.0.2-py2.py3-none-any.whl
Collecting ethereum==2.1.0 (from eth-vyper)
  Using cached https://files.pythonhosted.org/packages/5c/0d/1ca85eb4ddcac8ef9612d7f635ebb37b7e651a86a4c03705c7b681d168b6/ethereum-2.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    error in ethereum setup command: 'tests_require' must be a string or list of strings containing valid project/version requirement specifiers; Unordered types are not allowed

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/j5/vj2hckyj3vb81ymzw7h3fmnw0000gp/T/pip-build-c8hedbf5/ethereum/
You are using pip version 9.0.3, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```
#### Cute Animal Picture

> put a cute animal picture here.

![image](https://user-images.githubusercontent.com/130362/39634823-5de7e160-4fee-11e8-8e12-f14de87c1b5c.png)

**Comment by jacqueswww** [comment]
@ldct please try installing vyper using `pip install eth-vyper` ?

**Comment by ldct** [comment]
works now! thanks!
