### ISSUE TITLE
Enhancement large project: dataflow-style programming, Zilliqa style

### ISSUE THREAD

**Issue by jamesray1** [ethereum/vyper#807]
See https://docs.zilliqa.com/whitepaper.pdf FMI.

**Comment by jacqueswww** [comment]
@jamesray1 not sure what this has to do with vyper?

**Comment by jamesray1** [comment]
> The  smart  contract  language  in ZILLIQA follows  a dataflow  programming style  which  makes  it ideal for  running  large-scale  computations  that  can  be  easily parallelized. 

So the relation to Vyper is that it is also a smart contract programming language.

**Comment by jamesray1** [comment]
To implement a dataflow programming language as descrobed om tje abobe linked paper, as Christian said in #4072 you would probably have to start from scratch or write a front end.

**Comment by daniel-jozsef** [comment]
So please take this to etheresear.ch. :) This issue tracker is specifically for the Vyper language.
