### ISSUE TITLE
https://vyper.tools/ is not working 

### ISSUE THREAD

**Issue by nikhil5678** [ethereum/vyper#812]
Is this the alternative https://vyper.online/ ??

**Comment by ben-kaufman** [comment]
Yes. To my knowledge vyper.tools never worked. It was a mistake in the documentation which was fixed. Where did you see that?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nikhil5678** [comment]
here https://vyper.readthedocs.io/en/latest/installing-vyper.html

**Comment by ben-kaufman** [comment]
Oh that’s because the fixed documentation are only in GitHub. I recommend you to read only from GitHub because on the site they are outdated. 
@jacqueswww / @fubuloub do you have access to the docs website to update it?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jacqueswww** [comment]
Unfortunately no, @DavidKnott will have to help me with access ;)

**Comment by fubuloubu** [comment]
I thought he was helping you with that?

**Comment by jacqueswww** [comment]
@fubuloubu just gave me access! :smile: I updated read the docs. @nikhil5678 the docs now reflect `vyper.online`.

**Comment by jacqueswww** [comment]
Closing because vyper.tools domain should never be visible from now onwards.
