### ISSUE TITLE
Travis build failing

### ISSUE THREAD

**Issue by mingrammer** [ethereum/vyper#813]
vyper travis build failed for latest PR. It seems to be related to https://github.com/travis-ci/travis-ci/issues/9000

### How can it be fixed?

Could you try to use `sudo: required` as mentioned in above issue: https://github.com/travis-ci/travis-ci/issues/9000#issuecomment-356055219 until the problem is fixed.

**Comment by jacqueswww** [comment]
Strange! Thanks will add it.

**Comment by jacqueswww** [comment]
@mingrammer it looks like we already use `sudo: required` in our travis file?

**Comment by mingrammer** [comment]
@jacqueswww Oh .. I see. You're right. Hmm .. more strange ..

**Comment by jacqueswww** [comment]
Looks all good, I think we can close this issue now?
Rebuild does the trick, and it only happens from time to time.

**Comment by mingrammer** [comment]
A latest build succeed. This problem seems to occur intermittently.

**Comment by mingrammer** [comment]
@jacqueswww Sure!
