### ISSUE TITLE
Address Literals should be force to be checksummed.

### ISSUE THREAD

**Issue by jacqueswww** [ethereum/vyper#819]
### What's your issue about?
As there is currently not a use case were one would *not* need an address to use upper/lower case checksum. We should enforce this.

Shout out to @pipermerriam ;)
### How can it be fixed?

See the `number` method.

#### Cute Animal Picture

![](https://assets3.thrillist.com/v1/image/2558908/size/tmg-article_tall.jpg)

**Comment by ben-kaufman** [comment]
@jacqueswww is this already implemented? if so I think we need to close it and move the task to Done on the project board.
