### ISSUE TITLE
VIP: Use only wei_value for wei parameters

### ISSUE THREAD

**Issue by ben-kaufman** [ethereum/vyper#823]
## Preamble

    VIP: 823
    Title: Use only wei_value for wei parameters
    Author: Ben Kaufman 
    Type: Standard Track
    Status: Draft
    Created: 2018-05-16
    Requires: #653

## Simple Summary
Change all low-level functions using wei to require explicit conversion to ``wei_value``.
Make ``wei_value`` be ``uint256`` to prevent negative values.

## Abstract
This VIP is based upon VIP #653.
Currently, all wei is managed by ``int128``, but all low-level functions with wei parameters like ``raw_call`` and ``send`` expect to receive ``int128``. I propose changing this so they will accept only ``wei_value``.

## Motivation
The current situation has a few flaws:
1. This code will compile
```
@public
def __init__(dest: address):
    send(dest, -1)
```
2. ``wei_value`` can be a negative number (you shall never have negative wei)
```
@public
def __init__(dest: address):
    send(dest, as_wei_value(-1, "wei"))
```
3. Low-level functions expect to receive a number and not ``wei_value``, this means it's implicitly treated as wei. I believe all usage in wei should be explicitly in ``wei_value``.

## Specification
The technical specification should describe the syntax and semantics of any new feature. The specification should be detailed enough to allow any developer to implement the functionality

## Backwards Compatibility
This requires changing low-level functions as well as implementing VIP #653 which will cause backwards incompatibility.

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/)

#### Cute Animal Picture

![image](https://user-images.githubusercontent.com/10667901/40097115-08b463ec-58dd-11e8-839d-585d44674063.png)

**Comment by haydenadams** [comment]
`wei _value` and `currency_value` should both be moved to `uint256`

There is already a VIP for this

**Comment by ben-kaufman** [comment]
Yes but this VIP is mostly about changing the low level functions to accept ``wei_value`` explicitly and not any number.
I also think we should remove ``currency_value`` because now we have custom units

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by fubuloubu** [comment]
I agree, if custom units work you can make your own "currency" unit or whatever you like. Less to support!

**Comment by jacqueswww** [comment]
- Base unit will always be *wei*, secifically `uint256(wei)`.

Allow as_wei_value to support other units:
as_wei_value(x: uint256 or x:int128, "gwei") -> uint256(wei)

- Removing currency1 & currency2 :100:

**Comment by jacqueswww** [comment]
Implemented, closing issue ;)
