### ISSUE TITLE
vyper-run command doesn't work

### ISSUE THREAD

**Issue by ben-kaufman** [ethereum/vyper#839]
* vyper Version: 0.0.4
* pyethereum Version: 0.2.0a16
* OS: MacOS
* Python Version (python --version): 3.6

### What's your issue about?

The vyper-run command stopped working. I believe it is related to this issue ethereum/web3.py#813

```
    from rlp.utils import decode_hex, encode_hex, ascii_chr, str_to_bytes
ImportError: cannot import name 'decode_hex'
```
When downgrading rlp in the py-evm version I got this error:
```
site-packages/vyper-0.0.4-py3.6.egg/EGG-INFO/scripts/vyper-run", line 32, in <module>
AttributeError: module 'vyper.compiler' has no attribute 'Compiler'
```

### How can it be fixed?

Probably some changes to the vyper-run code or the py-evm version are needed.

#### Cute Animal Picture

![image](https://user-images.githubusercontent.com/10667901/40543331-8cec9a16-602c-11e8-8fcb-500782433931.png)

**Comment by fubuloubu** [comment]
I've been having a problem with either `decode_hex` or the `rlp` module for the past little while too. Something weird in setup.

**Comment by ben-kaufman** [comment]
I read it's because RLP version 1.0.0 introduced compatibility breaking changes and py-evm changed the version of rlp (see ethereum/py-evm#595). So when we updated the version it broke the ``vyper-run`` command

**Comment by jacqueswww** [comment]
@ben-kaufman thanks, `vyper-run` has to be converted to pyevm.

@fubuloubu Best advice I have for that error is to start a fresh virtualenv. Unsophisticated, but it works hehe.

**Comment by fubuloubu** [comment]
@jacqueswww it works about half the time for me, very strange environment error I was getting even when I started from scratch. I think it has to do with what order the dependencies are installed.
