### ISSUE TITLE
Remove old convert functions from documentation.

### ISSUE THREAD

**Issue by jacqueswww** [ethereum/vyper#845]
### What's your issue about?
All cases off `as_` needs to be fixed to show `convert()`.

e.g. as_uint256.

#### Cute Animal Picture
![](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS5tZSlHc4HQxlbbJvecrtOqrQj6_Iytx73Gc-88IVm5u1Ig53z)

**Comment by mandarvaze** [comment]
On [gitter](https://gitter.im/ethereum/vyper?at=5b0d86f152e35117cdeedc36), I was pointed to https://github.com/ethereum/vyper/blob/master/tests/parser/functions/test_convert.py for the usage of `convert` function.
It was confirmed that https://github.com/ethereum/vyper/blob/master/docs/built-in-functions.rst needs to be updated.

**Comment by hskang9** [comment]
Nice! [Here](https://github.com/ethereum/vyper/blob/master/vyper/types/convert.py) is the code for how ```convert``` function works
