### ISSUE TITLE
Ethereum Python Summit Wishlist

### ISSUE THREAD

**Issue by fubuloubu** [ethereum/vyper#849]
### What's your issue about?
Wishlist for "next generation" (post-release) Vyper

- [x] Imports and/or package support (ethpm)
  - Linking support
  - Including on-chain deployed libraries
- [x] Extensibility
  - Struct classes
  - Composable Types "Widgets"
- [x] Improve Documatation and Examples
- [x] Built-in Formal Verifier (optimize safemath gas costs, prove properties, etc)
- [x] Library Support

---

Discuss and create issues for above

**Comment by ben-kaufman** [comment]
Sounds cool, regarding the import suggestion, I feel like it's a bit against one of the core values of Vyper as it " requires people to jump between multiple files to understand what a program is doing".
I'm really not sure about that but I'm sure it worth discussion :)

**Comment by fubuloubu** [comment]
Yeah, there is definitely nuance here. In order to be a successful developer language for more than small uses, we need some way of separating concerns where it makes sense and doesn't obfuscate the program.

My suggestion using statements will be for two uses:
* package imports from eth-pm:
```python
from zeppelin.token import ERC20

# variable pointing to an ERC20-compatible token contract
my_token: ERC20
...
```
* importing other local files as self-contained, composed types
```python
import Boardmember

# create a group of 5 Boardmembers, whose functionality is defined in './Boardmember.vy'
board: Boardmember[5]
...
```

In both cases, you will already have a full understanding of exactly what it is you are importing, so you are not going back and forth between files to understand what is going on. Interfaces are easy in this way (e.g. ERC20), and our model for composable object types will have to be flushed out for our v2 release.

**Comment by haydenadams** [comment]
@fubuloubu so basically allow imports but avoid inheritance? Seems like a reasonable compromise

**Comment by haydenadams** [comment]
@fubuloubu so basically allow imports but don't allow inheritance? Seems like a reasonable compromise

**Comment by fubuloubu** [comment]
Exactly. No functional mutation, basically assembling programs like Lego bricks

**Comment by daniel-jozsef** [comment]
So... here's my take on these.

**Imports and/or package support (ethpm)**

Imports... Not like this, please. Not generic imports. It defeats the whole point of Vyper. I see two specific points where imports are a valid use case:

- Calling external contracts by its abi. The abi could be importable, so one doesn't need to craft calls by hand via keccak hashing.

- Deploying new contracts from a factory contract. In order to make builds not-painful, we need a way to import the binary of child contracts, and deploy it.

So... how about this? Vyper should never import Vyper files. We need specific imports to import ABIs and contract binaries. ABIs should be represented as types (classes), while binaries (or in general, strings) should be represented as constants for the programmer.

**Including on-chain deployed libraries**

No. Just no. Not like this.

We really need to rethink libraries from the ground up. Libraries sound good, but are the number 1 security vulnerability of Ethereum. If Vyper gets on the messed up crap Solidity library bandwagon, I'll consider it officially dead to me.

Deployed libraries are a good idea. But we need serious, serious, serious work on the concept, re-architecting it from the ground up, and coming up with a solution that is secure, reliable and auditable.

**Struct classes**

What is the use case where this would be good for anything other than writing unsafe code?

**Composable Types "Widgets"**

I don't understand what this is. ;)

**Library Support**

Please don't.

**Comment by daniel-jozsef** [comment]
Here's a quick thought train about what the philosophy of Vyper should be on code reuse. If more of you agree with me, or find it useful, it could be elevated to a guideline that should inform decisions on requests and questions such as imports, libraries and similar things.

So...

**Daniel's Ethereum smart contract ars poetica**

Ethereum smart contracts run on a very limited platform (the EVM), that in many of its limitations, is comparable to a punchcard computer from the 70s. For this reason, using modern programming paradigms useful on low-security and high capacity (virtually unlimited) systems will yield all of the drawbacks, but none or few of the benefits of these approaches.

So an Ethereum smart contract should follow the traditional Unix application philosophy. A single contract should do a single, very narrowly defined thing. Complex behaviors should emerge from the interplay of multiple separate, independent contracts, as opposed to through one complex contract.

For this reason, in-contract code composition is not only undesirable from a security standpoint, it is useless from a best practice development standpoint. We need to provide tools that make it easy for developers to write contracts that can easily interact with other contracts. An existing, successful example of this paradigm is the built-in cryptographic precompiles in Ethereum, accessible from smart contracts as separate contracts through an ABI and fixed address.

**Comment by fubuloubu** [comment]
Personally, my primary use of packages would be for standard interfaces like `ERC20` and for collecting my compiled smart contract system into one file for testing or front end use. Library support (and libraries in general) I am much less convinced on their overall utility, but @pipermerriam has been convincing me.

I think ultimately, you cannot have a single 1000+ line contract and have it remain understandable without significant effort. Breaking down concepts and composing them where they make sense can make it more readable and safer because the compiler takes care of linking things together. Ultimately there is a limit on complexity of a contract, so most applications will end up defining multiple contracts anyways.

I absolutely agree with you on the Unix philosophy, "do one thing and do it well" should definitely be a principle Vyper contracts adhere to.

**Comment by daniel-jozsef** [comment]
ERC20 is not a package, it's an ABI. We need the ability to import ABIs, not "packages".

As for collecting the smart contract system into one file, I'm not quite sure what you mean. Something like a Truffle migration? That would be a build and deployment toolchain question, which we should clearly demarcate from the compiler.

There's the compiler, which is Vyper specific, and then we could work on toolchain stuff that should be language agnostic, operating on ABIs and EVM binaries.

> Library support (and libraries in general) I am much less convinced on their overall utility, but @pipermerriam has been convincing me

On-chain libraries are useful, but very dangerous. I am extremely against having this functionality as a language citizen. Instead, well-known contracts deployed on the chain could be used for reusable logic, similarly to the EVM precompiles. (Ie. you explicitly call them as contracts.)

As for delegatecall'ing them, that's inherently unsafe. I guess we need the ability to do delegatecalls, but let's not make it too self-evident or enticing. I still remember the Parity multisig... ;)

> I think ultimately, you cannot have a single 1000+ line contract and have it remain understandable

I think you shouldn't have a 1000+ line contract, period. ;) (Likely deployment won't fit into block gas limit anyway.)

**Comment by fubuloubu** [comment]
I think I will close this issue as the original discussion already has sub-issues set up for them.
