### ISSUE TITLE
Add pragma tag

### ISSUE THREAD

**Issue by jacqueswww** [ethereum/vyper#852]
### What's your issue about?
We should add a simple pragma tag. That the current compiler will compare to, and warn the user if the version is not the same.

Format:
```
# pragma: x.y.z
```

Change the severity of the warning based on:
Given version format: x.y.z

z -> Patch, minor changes. As long x.y is the same, should compile the same.
x.y -> major changes, will most likely not compile.

### How can it be fixed?
Also discussed at length in https://github.com/ethereum/vyper/issues/456.

#### Cute Animal Picture
![](https://media.giphy.com/media/11JfYxBmCpQDde/giphy.gif)

**Comment by fubuloubu** [comment]
usually in semantic version aka `[major].[minor].[patch]` "minor" should not be backwards incompatible (although sometimes it can be, depending on the fixes applied), so I would modify that statement a bit.

**Comment by fubuloubu** [comment]
Also, maybe we can do something like `#@version: x.y.z` to do it more natspec-style?

**Comment by jacqueswww** [comment]
Sure that is an option

**Comment by jacqueswww** [comment]
```
# @version x.y.z
```

**Comment by fubuloubu** [comment]
Hmm, it's not bad I suppose. I think these extra variable-looking things are a bit opaque as to why they're there like that (but clear as to their intent).

Could they both be a bit more pythonic with the underbars?
```python
__version__: '>=0.0.4'
__units__: { ... }
```
