### ISSUE TITLE
Write vyper-run, quick start example. WIP

### ISSUE THREAD

**Issue by jacqueswww** [ethereum/vyper#872]
### What's your issue about?

Using vyper-run, one can write a really nice tutorial to get someone new to contract development to write and test something useful on the command line. Having a quick `vyper-run` guide that someone can fast track working with vyper would be great. :smile_cat:  

### How can it be fixed?

Fill this in if you know how to fix it.

#### Cute Animal Picture
^.^

**Comment by ben-kaufman** [comment]
I'm currently working on the documentation, I'll try adding vyper-run to the docs today.
After I'm done with the docs I want to create some tutorial on developing a whole dapp with Vyper (hopefully I'll have time for that), I'll probably add vyper-run there as well.
I am also thinking about adding a vyper-run panel for vyper.online.

**Comment by jacqueswww** [comment]
That would be awesome! :smile:
