### ISSUE TITLE
Adding sourceMap output to the compiler

### ISSUE THREAD

**Issue by fergarrui** [ethereum/vyper#878]
I didn't follow the VIP template because this is more a question than a proposal.
Basically, I am building a (for now) graphical Solidity debugger (https://github.com/fergarrui/ethereum-graph-debugger), and I would like to integrate Vyper and LLL into it.
I had a look to your compiler and I couldn't find an output that I can use to map bytecode to source code (something similar to the sourceMap in Solidity or the JSON ASM output again from Solidity).

Am I missing something?
Do you plan to add this kind of features?
Do you already have debugging tools?

**Comment by jacqueswww** [comment]
Hi @fergarrui ,

This still has to be implemented, do you have reference for what solidity is using?

**Comment by jacqueswww** [comment]
Ha, seem to have found the reference: https://solidity.readthedocs.io/en/develop/miscellaneous.html#source-mappings

**Comment by fergarrui** [comment]
That's the documentation they have, yes.
But I actually use a different thing to map the bytecode and the source code:
```
solc --pretty-json --combined-json asm ContractName.sol
```
That outputs something like:
```
// [...] removing non relevant output
{
            "begin" : 26,
            "end" : 320,
            "name" : "PUSH",
            "value" : "80"
          },
          {
            "begin" : 26,
            "end" : 320,
            "name" : "PUSH",
            "value" : "40"
          },
          {
            "begin" : 26,
            "end" : 320,
            "name" : "MSTORE"
          },
          {
            "begin" : 26,
            "end" : 320,
            "name" : "CALLVALUE"
          },
          {
            "begin" : 8,
            "end" : 17,
            "name" : "DUP1"
          },
          {
            "begin" : 5,
            "end" : 7,
            "name" : "ISZERO"
          }
// [...] removing non relevant output
```

Just with something like that I could start integrating Vyper (I still have many things to do with the debugger, so no rush at all)

**Comment by jacqueswww** [comment]
@fergarrui I see... What do the begin, end, value represent exactly?

**Comment by fergarrui** [comment]
Begin and end represent character indexes in the source code file.
For example, let's say we have this contract in Solidity:

```
pragma solidity ^0.4.23;

import "./CallerCalled.sol";

contract Caller {
    
    function callSomebody(address _calledcalled, address _called, uint _n) public {
        CallerCalled called = CallerCalled(_calledcalled);
        called.callCall(_called, _n);
    }
}

```

And the compiler gave us this output:

```
[...] // many more opcodes here
     {
        "begin" : 230,
        "end" : 258,
        "name" : "CALL"
      },
[...] // many more opcodes here
```
That opcode, refers exactly to the source code between begin and end, that would be `called.callCall(_called, _n)`. The value in `begin` would be the start character index, and `end`, the character index that corresponds to the end of the statement.

Value is only populated for PUSH opcodes, it represents the argument of the opcode, `PUSH` with a 40 `value` would add 40 to the stack but that's not necessary for debugging.

**Comment by jacqueswww** [comment]
@nrryuya I want to start looking into this. Could you elaborate on what tyoe of source map you require for remix?

**Comment by jacqueswww** [comment]
@fergarrui there is a simple _vyper style_ source map avialable now. It contains `breakpoints` for a list of lines with breakpoints and pc_pos_map which maps the PC value to [line_no, coll_offset].

I am closing this issue for now, as a source map is now available - when/if we create a solidity compatible source map this would be a second issue/task.
