### ISSUE TITLE
Calling convert() without assigning the result to a variable causes an error

### ISSUE THREAD

**Issue by rohithpr** [ethereum/vyper#879]
* vyper Version: Master
* pyethereum Version: x.x.x (Not sure how to find this. I built the environment using make in a clean ubuntu install so it's probably the latest. The version of pyethereum shouldn't matter for this issue anyway.)
* OS: Ubuntu
* Python Version (python --version): 3.6.3
* Environment (output of `pip freeze`):

### What's your issue about?

Code:

```python
@public
def foo() -> uint256:
    convert(2, 'uint256')
    return convert(2, 'uint256')
```

On running `vyper filename.py` throws the error: `AttributeError: 'Name' object has no attribute 'value'`

In `parser.py:parse_func`
`code.body` is: `[<_ast.Expr object at 0x7f4ff8fce160>, <_ast.Return object at 0x7f4ff8fce358>]`

Because of the Expression, execution reaches `stmt.py:Stmt.call` and an error is thrown in the line `elif isinstance(self.stmt.func.value, ast.Attribute) and self.stmt.func.value.attr in self.context.sigs:` because `self.stmt.func` is an object of type `Name` and it does not have an attribute `value`.

On assigning the return value of `convert()` to a variable, `code.body` in `parser.py:parse_func` becomes `[<_ast.AnnAssign object at 0x7ff077c7c160>, <_ast.Return object at 0x7ff077c7c3c8>]` and this error does not occur.

---

The issue can also be replicated by calling `max()`, `min()` and other such functions and not assigning their return value to a variable.

---

This issue does not occur if the return value of a `self.method()` is not assigned to a variable.

### How can it be fixed?

- Should code be allowed to call a method but ignore the return value?
- If the above behaviour should not be allowed, the error message should be better.

#### Cute Animal Picture

```
                           ____
  ________________________/ O  \___/
 <_/_\_/_\_/_\_/_\_/_\_/_______/   \
```

**Comment by fubuloubu** [comment]
Better error message is needed. Thanks!
