### ISSUE TITLE
convert(_uint256, 'uint256') fails

### ISSUE THREAD

**Issue by rohithpr** [ethereum/vyper#881]
* vyper Version: master
* pyethereum Version: x.x.x
* OS: osx/linux/win
* Python Version (python --version):
* Environment (output of `pip freeze`):

### What's your issue about?

Compiling either of the following pieces of code causes the error: `Expecting one of ('num_literal', 'int128', 'bytes32') for argument 1 of convert`

```python
@public
def foo() -> uint256:
    a: uint256 = 2 ** 20
    return convert(a, 'uint256')
```

```python
@public
def foo() -> uint256:
    return convert(2 ** 200, 'uint256')
```

If the code is as follows a run time error will occur:

```python
@public
def foo() -> uint256:
    i: uint256 = 200
    return convert(2 ** i, 'uint256')
```

`convert()` should be able to convert a `uint256` into `uint256` without any issues.

### How can it be fixed?

Add `uint256` to the list of tuple of expected arg types for `to_uint256()`.

#### Cute Animal Picture

![elephant](http://img0.etsystatic.com/002/0/5886267/il_fullxfull.406234440_3imn.jpg)

**Comment by fubuloubu** [comment]
I think there are two options for resolution: allow this (which is unnecessary extra code) or raise an error and have the writer remove it (no need to convert to same types).

I vote for option number 2

**Comment by jacqueswww** [comment]
I am not sure convert uint256 to uint256 should be an option?

**Comment by rohithpr** [comment]
@jacqueswww - I've given the reason for this change here: https://github.com/ethereum/vyper/pull/882#issuecomment-395738467

**Comment by rohithpr** [comment]
See #888.
