### ISSUE TITLE
Disallow int128->int128 conversion.

### ISSUE THREAD

**Issue by jacqueswww** [ethereum/vyper#888]
### What's your issue about?

Disallow`int128` to be converted to `int128`, follows https://github.com/ethereum/vyper/pull/882.

### How can it be fixed?

Fill this in if you know how to fix it.

#### Cute Animal Picture
![](https://peopledotcom.files.wordpress.com/2011/06/panda-660.jpg)

**Comment by rohithpr** [comment]
I can pick this up. It should be a pretty minor change.
