### ISSUE TITLE
Write default function documentation

### ISSUE THREAD

**Issue by jacqueswww** [ethereum/vyper#892]
### What's your issue about?

Now that we have fallback/default function support https://github.com/ethereum/vyper/pull/866. We need some solid documentation on using them :smile: 

- more than one example
- notes on not being able to parse parameters and why
- plus points for showing you can still pass calldata along (in proxy scenario).
- send having a gas limit
estimated word count: > 170

### How can it be fixed?
Inspiration:  
https://github.com/ethereum/vyper/blob/master/tests/parser/functions/test_default_function.py
https://solidity.readthedocs.io/en/latest/contracts.html?highlight=fallback#fallback-function

#### Cute Animal Picture
![](https://static.boredpanda.com/blog/wp-content/uuuploads/cute-baby-animals/cute-baby-animals-13.jpg)

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x0b0a1b181acf787695c91e88ee47a0bb446ce1189667297f275b8c79ed69a255](https://etherscan.io/tx/0x0b0a1b181acf787695c91e88ee47a0bb446ce1189667297f275b8c79ed69a255)

**Comment by jakerockland** [comment]
@jacqueswww Looks like this issue probably can be closed?
