### ISSUE TITLE
Remove the words "experimental" and "alpha" in relation to Vyper

### ISSUE THREAD

**Issue by fulldecent** [ethereum/vyper#902]
We are having a healthy discussion in ERC/721 which has mentioned Vyper.

Some members of the Vyper community are that discussion.

Some people in that discussion are stating that Vyper is no longer experimental nor alpha.

I think here is the best place to consider that question so I am opening this issue.

**Comment by ben-kaufman** [comment]
That's right, the first beta was just released. I agree we need to emphasize that.
