### ISSUE TITLE
LLL should show function IDs in hex

### ISSUE THREAD

**Issue by maurelian** [ethereum/vyper#913]
### Version Information

* vyper Version: vyper.online

### What's your issue about?

The LLL IR shows function IDs in decimal. 

Source code:
```
@public 
def onERC721Received(_from: address ,_tokenId: uint256, _data: bytes[164]) -> (bytes[4]):
    return '\xf0\xb9\xe5\xba'
```

LLL: `[eq, [mload, 0], 4038714810 <onERC721Received>],`

This is not helpful.

### How can it be fixed?

Display the function ID in hex.

#### Cute Animal Picture

![image](https://user-images.githubusercontent.com/23033765/41600283-8005bfc8-73a3-11e8-8331-929eb33a1d3c.png)

**Comment by jacqueswww** [comment]
Just a note for later to play with when implementing, one has two options here:
1.) Consider displaying all current int values as hex (in the LLL tree all args are stored as ints).
2.) Take any 4byte sized int and display it as hex.

**Comment by fubuloubu** [comment]
Option 1 is probably okay

**Comment by jacqueswww** [comment]
LLL output displays hex by default now, so closing ;)
