### ISSUE TITLE
Refactor code on type conversion with convert()

### ISSUE THREAD

**Issue by hskang9** [ethereum/vyper#919]
### What's your issue about?

Please include information like:

I found some hard-coded conversion cases in the [utils.py](https://github.com/ethereum/vyper/blob/master/vyper/utils.py) in vyper compiler. 
If hard-coding does not affect the compiling performance, I think it would be better to add those cases in the new type conversion method. 

### How can it be fixed?

Add conversion cases from [utils.py](https://github.com/ethereum/vyper/blob/master/vyper/utils.py) and refactor [utils.py](https://github.com/ethereum/vyper/blob/master/vyper/utils.py) by applying ```convert()```

#### Cute Animal Picture
![pochapeng](https://user-images.githubusercontent.com/12888144/41668868-4f4e4140-74eb-11e8-8c7f-8447881a641c.png)

**Comment by jacqueswww** [comment]
Those are used internally, whilst `convert()` is a runtime conversion within vyper.
