### ISSUE TITLE
VIP: Publish compiler to hub.docker

### ISSUE THREAD

**Issue by cgewecke** [ethereum/vyper#920]
### Version Information

* vyper Version: any / all

### What's your issue about?

How the Vyper compiler is published.

Hi - I code over at Truffle. We'd really like to add the ability to use Vyper contracts in truffle projects. @maurelian Has recently written a nice utility that demonstrates this is possible ([see here](https://github.com/maurelian/truper)). 

We're also about to start supporting dockerized `solc` and have some simple cli and configuration in place to make that possible. It would be  nice if users could run something like:
```
$ truffle compile --list vyper
> [
> "0.1.0-beta.1 ",
> "0.0.4",
> ]

$ docker pull ethereum/vyper:0.1.0-beta.1
$ truffle compile 
```

### How can it be fixed?

Begin publishing compiler releases to [docker hub](https://hub.docker.com/). 

[solc on docker hub](https://hub.docker.com/r/ethereum/solc/) for reference. 

Thanks! This project is awesome :) 

#### Cute Animal Picture

![baby-killer-whales-wallpaper-1](https://user-images.githubusercontent.com/7332026/41675683-30dec842-7478-11e8-83c4-7ef145f4b645.jpg)

**Comment by fubuloubu** [comment]
We have a docker image, not sure if it's published.

We also have a snap!

**Comment by jacqueswww** [comment]
@cgewecke I will have a look at this :-)

**Comment by jacqueswww** [comment]
@cgewecke do you know who has access to the `ethereum` namespace on dockerhub?

**Comment by cgewecke** [comment]
@jacqueswww No, so sorry, I don't.  I'll ask over solidity-dev gitter how they did it super quick.

**Comment by cgewecke** [comment]
@jacqueswww It's believed that chriseth knows.

**Comment by chriseth** [comment]
I just created ethereum/vyper. Please tell me your docker hub username and I can add you.

**Comment by jacqueswww** [comment]
@cgewecke I just pushed the latest master to dockerhub :smile: 

I also added an ENTRYPOINT to the docker file, meaning you can run the compiler with `docker run vyper` - which I believe is how it's intended to be used?

**Comment by cgewecke** [comment]
@jacqueswww Great! Thank you so much :) Exciting. 

FWIW this is how the command is invoked (on my box anyway). Seems normal - same as solc and geth. 
```
docker run ethereum/vyper  # works
docker run ethereum/vyper:latest # also works
```
