### ISSUE TITLE
Installation error on Arch (eth-pm dependency)

### ISSUE THREAD

**Issue by travs** [ethereum/vyper#934]
### Version Information

* vyper Version: not yet installed, just the master branch right now (latest release is `v0.1.0-beta.1`)
* pyethereum Version: x.x.x  (none; is this the issue?)
* OS: osx/linux/win: 4.16.12-1-ARCH
* Python Version (python --version): `Python 3.6.5`
* Environment (output of `pip freeze`): 

```
aiohttp==2.3.10
async-lru==0.1.0
coincurve==7.1.0
cryptography==2.2.2
cytoolz==0.9.0.1
eth-account==0.2.3
eth-bloom==1.0.0
eth-keys==0.2.0b3
eth-utils==1.0.3
hexbytes==0.1.0
ipython==6.4.0
lru-dict==1.1.6
netifaces==0.10.7
plyvel==1.0.4
py-ecc==1.4.3
py-evm==0.2.0a18
pyethash==0.1.27
pysha3==1.0.2
requests==2.19.1
rlp==1.0.1
trie==1.3.7
uPnPClient==0.0.8
vyper==0.1.0b1
web3==4.4.0
websockets==5.0.1
```

### What's your issue about?

Downloaded the repo, and tried to install using `make`, as described in the docs.

The installation progresses to a point but then gives this error:

```
Processing dependencies for vyper==0.1.0b1
Searching for eth-pm==0.1.0-alpha.17
Reading https://pypi.org/simple/eth-pm/
No local packages or working download links found for eth-pm==0.1.0-alpha.17
error: Could not find suitable distribution for Requirement.parse('eth-pm==0.1.0-alpha.17')
make: *** [Makefile:4: init] Error 1
```

Do I need to install `pyethereum` or something? It's listed in the issue template, but didn't see anything in the installation docs.

**Comment by fubuloubu** [comment]
Web3  4.4.0 has a dependancy on eth-pm that was fixed in 4.4.1

@jacqueswww please update ^

**Comment by jacqueswww** [comment]
@travs please try the latest master. There is only a single dependency on pycryptodome now, so should install without a problem. :smile:

**Comment by travs** [comment]
Late reply, but it works for me now :)
