### ISSUE TITLE
Unicode characters are allowed to be a part of identifiers

### ISSUE THREAD

**Issue by rohithpr** [ethereum/vyper#936]
### Version Information

* vyper Version: Master
* pyethereum Version: x.x.x
* OS: osx/linux/win
* Python Version (python --version):
* Environment (output of `pip freeze`):

### What's your issue about?

In Vyper, Unicode characters are allowed to be a part of identifiers (variable names, method names, etc.). This could lead to [Homograph attacks](https://en.wikipedia.org/wiki/IDN_homograph_attack) where a piece of code appears to be acting on one variable but is actually acting on some other variable. Unicode characters should probably be disallowed from being a part of identifiers, especially since Vyper aims to be a language that is easy to audit.

---

FWIW, Solidity throws an error when I try to name a variable with a unicode character.

Code:

```solidity
pragma solidity ^0.4.21;

contract Foo {
    
    function x(int128 i) public view {
        uint256 Other_Balance = 3; // ASCII O
        
        // a bunch of code
        if (i>0) {
            uint256 Оther_Balance = 2; // Unicode О
        }
        
        // a bunch of code
        return Other_Balance; // ASCII O
    }
}
```

Error:
```
browser/Untitled5.sol:10:21: ParserError: Expected ';' but got 'ILLEGAL'
            uint256 Оther_Balance = 2; // Unicode О
                    ^
```

---

Similar code in Vyper, which compiles without throwing any errors:

```python
@public
def foО(i: int128) -> uint256:
    Other_Balance: uint256 = 3 # ASCII O
    
    # a whole bunch of code
    if i > 0:
        Оther_Balance: uint256 = 2 # Unicode О
    
    # a whole bunch of code

    return Other_Balance # ASCII O
```

---

### How can it be fixed?

Disallow Unicode characters in identifiers.

#### Cute Animal Picture

![Baby Elephant](http://kindakind.com/wp-content/uploads/2015/09/animals_elephants_nature_mom_baby_ultra_3840x2160_hd-wallpaper-72234.jpg)

**Comment by rohithpr** [comment]
I'd like to work on this if it is something that has to be fixed.

**Comment by fubuloubu** [comment]
Yes, this is a good issue to work on if you're interested in
