### ISSUE TITLE
Location of function_signature.py is incorrect

### ISSUE THREAD

**Issue by sushantkumr** [ethereum/vyper#937]
### Version Information

* vyper Version: 0.1.0b1 (Master)
* pyethereum Version: x.x.x
* OS: linux
* Python Version (python --version): 3.6.3
* Environment (output of `pip freeze`):

### What's your issue about?

Please include information like:

The file function_signatures.py is currently in the path vyper/vyper/  . For consistency this must be placed along with event_signature.py under vyper/vyper/signatures/.

### How can it be fixed?

Move function_signature.py from **vyper/vyper/** to **vyper/vyper/signatures/**.
Files which have dependency on function_signature.py will have to be fixed. They are listed below:

* vyper/parser/context.py
* vyper/parser/parser.py
* vyper/signatures/event_signature.py

#### Cute Animal Picture

![doggie](https://user-images.githubusercontent.com/10464008/42362474-061044e2-8111-11e8-9355-56d6d7673c3e.jpg)

**Comment by jacqueswww** [comment]
+1, also consider renaming `signature.py` to something else.

**Comment by ehanoc** [comment]
I took a shot at it with PR #942.

Should function_signature.py be renamed though?
