### ISSUE TITLE
ABI JSON fails to be validated

### ISSUE THREAD

**Issue by ehanoc** [ethereum/vyper#950]
## Simple Summary
Seems to be a combination of issues, which i'm still trying to figure out entirely. The direct generated ABI won't go through web3.eth.Contract as valid. An Error will be through as >

`Error: You must provide the json interface of the contract when instantiating a contract object`

Upon investigating into web3.eth.contract, it fails with this : 

`    if(!jsonInterface || !(Array.isArray(jsonInterface))) {
        throw new Error('You must provide the json interface of the contract when instantiating a contract object.');
    }`

Not an Array? We might need to use JSON.parse first. 

## Hack as Solution 

I've managed to deploy the contract doing the following: 

Using JSON.parse on the returned ABI. But only after replacing ' with ". Since JSON.parse will not take in the ABI without it. 

Any thoughts on this? 

## Cute animal 

![g86lsij0li911](https://user-images.githubusercontent.com/1436105/42688512-68b5fdde-8694-11e8-9f9e-05faf8c626aa.jpg)

**Comment by fubuloubu** [comment]
Can you share the line of web3js interaction code you are doing?

**Comment by ehanoc** [comment]
```
// pass abi_path and bytecode as arguments to process

//path to abi.json (output generated from vyper -f abi [...].vy )
const abi_path = process.argv.pop();
const bytecode = process.argv.pop();

var abi;
try {
    abi = fs.readFileSync(abi_path, 'utf8');
} catch(e) {
    console.log('Error:', e.stack);
}

var account;
web3.eth.getAccounts( (err, accounts) => {
    account = accounts[0];
    // Contract object
   //abi = JSON.parse(replaceAll(abi, "'", '"').toLowerCase());
    const contract = new web3.eth.Contract(abi, account);
    contract.deploy({...}) 
```

**Comment by jacqueswww** [comment]
@ehanoc Have a shot with `-f json` :wink:

**Comment by ehanoc** [comment]
@jacqueswww ye, that works. thanks!

**Comment by jacqueswww** [comment]
Closing issue as it's solved ;)
