### ISSUE TITLE
Optimize multiplication operation on Vyper

### ISSUE THREAD

**Issue by hskang9** [ethereum/vyper#965]
## Simple Summary
Optimize multiplication check as recent openzeppelin safemath [implementation](https://github.com/OpenZeppelin/openzeppelin-solidity/pull/522).

## Abstract
One of the things I like Vyper is that it supports safemath from the language.
Its logic is on [expr.py](https://github.com/ethereum/vyper/blob/master/vyper/parser/expr.py).
However, I found a typo in the comment:
from
``` # Checks that: a == 0 || a / b == b``` 
to
``` # Checks that: a == 0 || c(which is a*b) / a == b```

 and a space for gas optimization which was approved in Openzeppelin's SafeMath [implementation](https://github.com/OpenZeppelin/openzeppelin-solidity/blob/master/contracts/math/SafeMath.sol).

## Motivation
If this change is not approved, comment typo is not fixed and vyper uses more gas than solidity with safemath contract.

## Specification
Here is the difference of Opcode to be pushed to LLL parse tree:
### Before
assert(a==0 || (a*b / a) == b)
```
['assert', ['or', ['iszero', left],
['eq', ['div', ['mul', left, right], left], right]]],
['mul', left, right]
```

### After

if (a == 0) { return 0; } // Without verifying a\*b / a == b
assert(a*b/a==b);
```
[  'if', 
   ['eq', left, 0],
   [0], 
  ['seq',
     ['assert', ['eq', ['div', ['mul', left, right], left], right]],
     ['mul', left, right]
  ]
]

```

Reasons and verification is described on the link [here](https://github.com/OpenZeppelin/openzeppelin-solidity/pull/522)

## Backwards Compatibility
This version is compatible with the others but it uses less gas for an arithmetic operation.

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/)

**Comment by jacqueswww** [comment]
Wow good catch picking that up from SafeMath :smile:

**Comment by fubuloubu** [comment]
I'm missing something about this comment in context of the code. How does checking if and only if `a == 0` in order to proceed with any multiplication help?

**Comment by hskang9** [comment]
Oops. I passed out 3 hours ago and checked this. I will implement it right.

**Comment by jacqueswww** [comment]
@fubuloubu so basically you save gas because you immediatly return 0 for `0/x` instead of doing all the checks and the math and return 0 anyways.

**Comment by fubuloubu** [comment]
Okay, that makes way more sense now lol
