### ISSUE TITLE
Blockhash() accepts negative integers

### ISSUE THREAD

**Issue by maurelian** [ethereum/vyper#981]
### Version Information

vyper.online

### What's your issue about?

This line should cause a compiler error:

`    self.a = blockhash(-20)`

### How can it be fixed?

Block numbers should be uint256. 

Also, note that the `BLOCKHASH` opcode puts a 0 on the stack if the looked for block number is greater than or equal to the current block number or more than 256 blocks behind the current block.

This is a dangerous hole. I'm not sure the best way to plug it.

**Comment by ben-kaufman** [comment]
@jacqueswww if you haven't started yet, I'll try to fix this.

**Comment by jacqueswww** [comment]
Sure :)

**Comment by ben-kaufman** [comment]
@maurelian there's already clamp checks to ensure block is not too far in the past and not from the future. I just remove the ability to use `int128` and added test for all 3 cases.
