### ISSUE TITLE
Vyper compiler ABI output produces invalid JSON (due to using single quotes & camel case boolean literals)

### ISSUE THREAD

**Issue by kkom** [ethereum/vyper#989]
### Version Information

* vyper Version: master from`2018-07-31T13:27:06Z` (from `ethereum/vyper` Docker image)
* pyethereum Version: ?? (sorry, can't figure it out...)
* OS: osx (running on Docker)
* Python Version: (python --version): 3.6
* Environment (output of `pip freeze`): N/A

### What's your issue about?

Vyper ABI output uses:

1. single quotes as string wrappers
2. camel case literals as boolean values

This isn't valid JSON according to [the specification](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf) for strings:

<img width="684" alt="double quotes are valid string wrappers" src="https://user-images.githubusercontent.com/5056119/43950180-8b02f690-9c87-11e8-966c-90c3a9d32b81.png">

and booleans:

<img width="365" alt="boolean values are all lowercase string literals" src="https://user-images.githubusercontent.com/5056119/43950181-8b17e938-9c87-11e8-9cd7-8bca6ebcb00b.png">

See example:

```
Highgarden:vyper_quotes kkom$ curl https://raw.githubusercontent.com/ethereum/vyper/master/examples/auctions/simple_open_auction.vy > simple_open_auction.vy
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2255  100  2255    0     0  11912      0 --:--:-- --:--:-- --:--:-- 11931
Highgarden:vyper_quotes kkom$ docker run -v $PWD:$PWD -w $PWD ethereum/vyper -f abi simple_open_auction.vy 
[{'name': '__init__', 'outputs': [], 'inputs': [{'type': 'address', 'name': '_beneficiary'}, {'type': 'uint256', 'name': '_bidding_time'}], 'constant': False, 'payable': False, 'type': 'constructor'}, {'name': 'bid', 'outputs': [], 'inputs': [], 'constant': False, 'payable': True, 'type': 'function', 'gas': 106241}, {'name': 'end_auction', 'outputs': [], 'inputs': [], 'constant': False, 'payable': False, 'type': 'function', 'gas': 71101}, {'name': 'beneficiary', 'outputs': [{'type': 'address', 'name': 'out'}], 'inputs': [], 'constant': True, 'payable': False, 'type': 'function', 'gas': 543}, {'name': 'auction_start', 'outputs': [{'type': 'uint256', 'name': 'out'}], 'inputs': [], 'constant': True, 'payable': False, 'type': 'function', 'gas': 573}, {'name': 'auction_end', 'outputs': [{'type': 'uint256', 'name': 'out'}], 'inputs': [], 'constant': True, 'payable': False, 'type': 'function', 'gas': 603}, {'name': 'highest_bidder', 'outputs': [{'type': 'address', 'name': 'out'}], 'inputs': [], 'constant': True, 'payable': False, 'type': 'function', 'gas': 633}, {'name': 'highest_bid', 'outputs': [{'type': 'uint256', 'name': 'out'}], 'inputs': [], 'constant': True, 'payable': False, 'type': 'function', 'gas': 663}, {'name': 'ended', 'outputs': [{'type': 'bool', 'name': 'out'}], 'inputs': [], 'constant': True, 'payable': False, 'type': 'function', 'gas': 693}]
```

The ABI output isn't accepted by the Parity UI:

<img width="1312" alt="invalid json in parity ui" src="https://user-images.githubusercontent.com/5056119/43950417-23d6bfdc-9c88-11e8-89ae-0f6913f55506.png">

### How can it be fixed?

Single quotes and uppercase boolean values are a Python convention, so I presume a slightly more sophisticated printing method needs to be used. If there is consensus that this issue should be fixed in this way, I'm happy to look into it more.

This demonstrates that, in the case of the `simple_open_auction.vy` contract, fixing these two issues produces valid JSON:

```
Highgarden:vyper_quotes kkom$ docker run -v $PWD:$PWD -w $PWD ethereum/vyper -f abi simple_open_auction.vy | sed 's/'\''/"/g' | sed 's/True/true/g' | sed 's/False/false/g'
[{"name": "__init__", "outputs": [], "inputs": [{"type": "address", "name": "_beneficiary"}, {"type": "uint256", "name": "_bidding_time"}], "constant": false, "payable": false, "type": "constructor"}, {"name": "bid", "outputs": [], "inputs": [], "constant": false, "payable": true, "type": "function", "gas": 106241}, {"name": "end_auction", "outputs": [], "inputs": [], "constant": false, "payable": false, "type": "function", "gas": 71101}, {"name": "beneficiary", "outputs": [{"type": "address", "name": "out"}], "inputs": [], "constant": true, "payable": false, "type": "function", "gas": 543}, {"name": "auction_start", "outputs": [{"type": "uint256", "name": "out"}], "inputs": [], "constant": true, "payable": false, "type": "function", "gas": 573}, {"name": "auction_end", "outputs": [{"type": "uint256", "name": "out"}], "inputs": [], "constant": true, "payable": false, "type": "function", "gas": 603}, {"name": "highest_bidder", "outputs": [{"type": "address", "name": "out"}], "inputs": [], "constant": true, "payable": false, "type": "function", "gas": 633}, {"name": "highest_bid", "outputs": [{"type": "uint256", "name": "out"}], "inputs": [], "constant": true, "payable": false, "type": "function", "gas": 663}, {"name": "ended", "outputs": [{"type": "bool", "name": "out"}], "inputs": [], "constant": true, "payable": false, "type": "function", "gas": 693}]
```

<img width="1312" alt="valid json in parity ui" src="https://user-images.githubusercontent.com/5056119/43950401-1d5eff52-9c88-11e8-80fe-71acac9db278.png">

#### Cute Animal Picture

This is actually my dog, Yoshi!

![yoshi](https://user-images.githubusercontent.com/5056119/43950526-69e36106-9c88-11e8-9f7a-0a67078bcb20.jpg)

**Comment by jacqueswww** [comment]
@kkom the `-f json` output produces the ABI you are looking for, the `-f abi` produces a python format (we kept this, so one can easily paste it into your web3.py setup).

What a beautiful dog! :dog: :smile:

**Comment by kkom** [comment]
Cool! What's the decision-making process here? Submit a pull request and discuss there? Or should we wait for a few more people to chime in on this issue?

**Comment by kkom** [comment]
Sure! I gave it a try: PR https://github.com/ethereum/vyper/pull/995 :)

**Comment by kkom** [comment]
PR https://github.com/ethereum/vyper/pull/995 merged!
