### ISSUE TITLE
make command is not recognized 

### ISSUE THREAD

**Issue by malaravannm** [ethereum/vyper#996]
When I type make command as per installation instructions. Receiving below message in windows.
I am unable to see any make.exe in vyper folder. Please suggest.

(vyper-venv) C:\Users\Malaravan\vyper>make
'make' is not recognized as an internal or external command,
operable program or batch file.

**Comment by fubuloubu** [comment]
You probably do not have GNU make. You will have to install an environment that contains it, such as cygwin or the Ubuntu subsystem for windows.

**Comment by malaravannm** [comment]
Installed cygwin package dlevel for windows and I am able to proceed.  Thanks
