### ISSUE TITLE
`not` operation can be applied to values other than bools

### ISSUE THREAD

**Issue by nrryuya** [ethereum/vyper#999]
## Simple Summary
`not` operation should be applied to only bools for simplicity and security.

## Abstract
Now `not` operation can be applied to not only `bool` but also other types like `int128`, `uint256`, `address`, `bytes`.
(The code below can be compiled in [vyper.online](https://vyper.online/))

![image](https://user-images.githubusercontent.com/22876645/44295085-d97aab00-a2dc-11e8-8bc6-4cf87664438d.png)

However, `not` operation should be applied to only `bool`.

## Motivation
I think "bool operations can only be applied to bools" is a simple design. In addition, it can prevent unexpected behavior. For example, when developers(like me) might make a mistake and code like `not n in [1, 2, 3]` but she means `not(n in [1, 2, 3])` actually, the first code is compiled and have different semantics.

## Specification
Compiler doesn't allow `not` operation used for the variables whose type is other than `bool`.

## Backwards Compatibility
The codes in which `not` is used for the variables whose type is other than `bool` will not be compiled anymore.

**Comment by ben-kaufman** [comment]
Looks like a bug. I wonder what is the result from actually running one of the methods, did you try that?

**Comment by fubuloubu** [comment]
Agree this seems like a bug. I would support reducing scope from a VIP to a normal issue.

**Comment by nrryuya** [comment]
> I would support reducing scope from a VIP to a normal issue.
I see. I modified the title.

**Comment by jacqueswww** [comment]
Starting on this.
